### ISSUE TITLE
Code in section Response Format URL Mappings  doesn't work.

### ISSUE THREAD

**Issue by PingPongSet** [aspnet/AspNetCore.Docs#11220]
The code in this section doesn't work. 

Below works without FormatFilter:
```
  [Route("api/[controller]")]
    public class ProductsController: Controller
    {
        [Route("[action]/{id}.{format?}")]
        [HttpGet]
        public string GetById(int id)
        {
            return id.ToString();
        }
    }
```

From article
```
[FormatFilter]
public class ProductsController
{
    [Route("[controller]/[action]/{id}.{format?}")]
    public Product GetById(int id)
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ebcd752-af71-c483-eebb-0745bd04fb30
* Version Independent ID: 1f678d5d-230b-0ad0-c925-15b13081f553
* Content: [Format response data in ASP.NET Core Web API](https://docs.microsoft.com/en-us/aspnet/core/web-api/advanced/formatting?view=aspnetcore-2.2)
* Content Source: [aspnetcore/web-api/advanced/formatting.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/web-api/advanced/formatting.md)
* Product: **aspnet-core**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Verified the code does not work. PU - please supply code that works with the template generated values controller.

**Comment by serpent5** [comment]
@Rick-Anderson What exactly does "does not work" mean here? I can get this working with the default `ValuesController` with only a couple of minor additions, so I might be able to help if I know what the problem was.

**Comment by Rick-Anderson** [comment]
The `ValuesController` is gone in 3.0. I'd like to see it working with the 3.0 `Weather` controller.

**Comment by serpent5** [comment]
@Rick-Anderson I'm using Preview 6, but the scaffolding still generates `ValuesController`. I found out the `WeatherController` isn't in a preview yet, so I grabbed it from the repo and added it into a local Preview 6 project and had a play with it. Here's what I found:

First, apply the following changes:

1. Add `[FormatFilter]` to the `WeatherController`:

   ```cs
   [FormatFilter]
   public class WeatherController : ControllerBase
   ```

2. Add the XML formatters in `ConfigureServices`:

   ```cs
   services.AddControllers()
       .AddXmlSerializerFormatters();
   ```

With that in place, the following works:

1.     GET https://localhost:5001/api/SampleData/Weather

   Returns JSON as the expected default.

2.     GET https://localhost:5001/api/SampleData/Weather?format=xml

   Returns XML as it's specified in the query-string using `format` (it has to be `format`).

However, this doesn't work:

    GET https://localhost:5001/api/SampleData/Weather?format=json

It returns a 404, which is because there's no `FormatterMapping` for `json`.

I found two ways to resolve this:

1. Add JSON.NET support:

   ```cs
   services.AddControllers()
       .AddXmlSerializerFormatters()
       .AddNewtonsoftJson();
   ```

   This works because it also adds a `FormatterMapping` for `json` ([source](https://github.com/aspnet/AspNetCore/blob/master/src/Mvc/Mvc.NewtonsoftJson/src/DependencyInjection/NewtonsoftJsonMvcOptionsSetup.cs#L87)).

2. Add the `FormatterMapping` manually:

   ```cs
   services.AddControllers()
       .AddXmlSerializerFormatters()
       .AddFormatterMappings(fm => fm.SetMediaTypeMappingForFormat("json", "application/json");
   ```

Of course, adding JSON.NET support for this doesn't make sense. For the second approach, I wonder if this is just something that's been missed from being built-in or whether it's for a specific reason. Perhaps it's something that could be added [here](https://github.com/aspnet/AspNetCore/blob/master/src/Mvc/Mvc.Core/src/Infrastructure/MvcCoreMvcOptionsSetup.cs#L87), using e.g.:

```cs
options.FormatterMappings.SetMediaTypeMappingForFormat("json", "application/json");
```

**Comment by Rick-Anderson** [comment]
@serpent5  great info. When preview 7 ships you can make a sample.

**Comment by serpent5** [comment]
I've edited the explanation for Preview 7 and raised an issue against `aspnet/AspNetCore` as linked above.

**Comment by serpent5** [comment]
@Rick-Anderson The issue I raised was fixed about 3 weeks ago and I've just confirmed it's working in Preview 8 with the instructions above. :tada:

**Comment by Rick-Anderson** [comment]
@serpent5 thanks!

**Comment by Rick-Anderson** [comment]
@serpent5 this made it into the https://docs.microsoft.com/en-us/aspnet/core/web-api/advanced/formatting?view=aspnetcore-3.0 - right?

**Comment by serpent5** [comment]
@Rick-Anderson No docs changes were made. It didn't work in 3.0 because of the bug that was raised and fixed, but it worked afterwards with `WeatherForecastController`.

Looking at this again now, it looks like the example in the docs doesn't work because it's doubling up the `[controller]` token in the route for `ProductsController`. I can look into that a bit more and PR it. Is there anything else you'd like doing with the article/samples?

**Comment by Rick-Anderson** [comment]
>  Is there anything else you'd like doing with the article/samples?
No, that should be good. Thanks.
