### ISSUE TITLE
Guidance on how to log to a message queue for slow data stores

### ISSUE THREAD

**Issue by Fniz** [aspnet/AspNetCore.Docs#11801]
Can you give me more precision regarding this sentence : "If your logging data store is slow, don't write to it directly. Consider writing the log messages to a fast store initially, then move them to the slow store later. For example, log to a message queue that's read and persisted to slow storage by another process."

I want to store log in SQL server, so I suppose it's a slow data store. So I would like what you mean by "log to a message queue".  Do you reffer to RabbitMQ for example ?

Yours sincerely,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7184a308-a254-9350-a5cd-5bced1f369ae
* Version Independent ID: 726e3bf1-f367-d733-8933-bccc04da0e16
* Content: [Logging in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-2.2#built-in-logging-providers)
* Content Source: [aspnetcore/fundamentals/logging/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/logging/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
You could use Azure Storage queues or Azure Service Bus queues --
https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-azure-and-service-bus-queues-compared-contrasted

**Comment by Rick-Anderson** [comment]
@tdykstra do you want to take this issue and update the article to say 
Log to a message queue (such as ...)

**Comment by tdykstra** [comment]
@Rick-Anderson Yes, good idea.

**Comment by Fniz** [comment]
Thank you very much for your answer. Is there non-cloud credible alternative to Azure service bus ?

**Comment by anurse** [comment]
Actually this refers to using in-memory queuing. If you are logging to SQL server, you don't want to do that directly in the `Log` method, since it's synchronous. Instead, you should (synchronously) add the log message to an in-memory queue and have a background worker come along to pull the items out of the queue and do the asynchronous work (pushing data to the SQL server).

**Comment by Fniz** [comment]
Thank you @anurse for your answer. When you talk about an *in-memory queue*, is it kike this for the ConsoleLogger : https://github.com/aspnet/Logging/blob/master/src/Microsoft.Extensions.Logging.Console/Internal/ConsoleLoggerProcessor.cs

**Comment by anurse** [comment]
@Fniz precisely right! Even the console logger ended up finding improvements by using an in-memory queue. A SQL (or other remote) backend would definitely want something similar.

**Comment by anurse** [comment]
FYI: Rather than a special thread, I'd suggest looking at [`IHostedService`](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/hosted-services?view=aspnetcore-2.2#queued-background-tasks) which provides a built-in way to have long-running background tasks in ASP.NET Core. The console logger is more general-purpose (designed to work outside ASP.NET Core) so it uses a custom thread, but if you are in an ASP.NET Core application, `IHostedService` will cooperate better with the rest of the application.

**Comment by wadebee** [comment]
I know this issue is closed but it seems like a common use-case to want to log to a database. In the documentation can you point users to a 3rd party .NET Core logging provider that can queue up async logging?

**Comment by tdykstra** [comment]
@anurse is there a 3rd party provider we can recommend? Or sample code for a queuing provider that uses IHostedService that we could point to?

**Comment by anurse** [comment]
That uses `IHostedService`? No. The [console logger does this](https://github.com/aspnet/Logging/blob/master/src/Microsoft.Extensions.Logging.Console/Internal/ConsoleLoggerProcessor.cs) but it uses a background thread instead. `IHostedService` does require that you are in a "hosted" environment (either ASP.NET Core or the new Generic Host stuff) so perhaps a background thread may be a better option for a logger provider.

**Comment by tdykstra** [comment]
I changed the title to indicate this issue is about guidance for writing (and/or sample code for) a logging provider that uses in-memory queue for fast logging and uses a background process to pull from the queue to write to a slow data store.  This is related to, and could be done along with, #11842

**Comment by john-larson** [comment]
Wouldn't a fire-and-forget call to the log method be enough in terms of performance? Do we really need an in-memory queue?

**Comment by ygoe** [comment]
Has anybody considered logging near the end of the process? Especially when it comes to unhandled exceptions and unclean terminations. I've seen regular `Console.WriteLine` output get lost if the process runs as Systemd service and terminates directly after the output. So I added a short synchronous delay after these outputs (500/1000 ms). A hosted service is certainly a bad option when logging the application shutdown as it will be shut down itself. I'm wondering how such an asynchronous log writer can be made reliable in those conditions. Would it help to make it flush its buffer in a `AppDomain.CurrentDomain.ProcessExit` event handler?
