### ISSUE TITLE
AddMemoryCache is no more required

### ISSUE THREAD

**Issue by CeciAc** [aspnet/AspNetCore.Docs#11835]
Hi team, 
I'm moving this from here: https://github.com/aspnet/Docs.pt-br/issues/109 
Since the user is making a suggestion on the original documentation

@joelrlneto commented:
In my recent tests, it was not necessary to call the method `services.AddMemoryCache() `inside `ConfigureServices`. For some reason, the IMemoryCache is being injected correctly and the memory cache is working well. But I did not find any updated documentation that says calling `AddMemoryCache` is no more required.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13f5f8f9-18dd-9c12-9ed1-fcc6b44ba7fd
* Version Independent ID: 640b4f36-5886-7b69-1c95-cfc8574a02fd
* Content: [Cache in-memory in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/performance/caching/memory?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/performance/caching/memory.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/performance/caching/memory.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-performance**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by serpent5** [comment]
@joelrlneto Do you have a call to `AddResponseCaching` in your `ConfigureServices` method?

**Comment by joelrlneto** [comment]
> @joelrlneto Do you have a call to `AddResponseCaching` in your `ConfigureServices` method?

No, I don't have any call to this method in my Startup.cs.

**Comment by serpent5** [comment]
@joelrlneto Would you mind providing a list of `AddXXX` methods you're using in `ConfigureServices`? I appreciate that might be a big ask so don't worry if it's too much effort.

**Comment by serpent5** [comment]
@joelrlneto Thanks for responding so quickly.

I've managed to track this down to the fact that the call to `AddMvc` actually registers `IMemoryCache` as part of registering the Razor view engine. if it's not already been registered ([source](https://github.com/aspnet/AspNetCore/blob/release/2.2/src/Mvc/Mvc.Razor/src/DependencyInjection/MvcRazorMvcCoreBuilderExtensions.cs#L233)). I also discovered that `AddResponseCaching` calls `AddMemoryCache` directly, too, so that all means you will have access to `IMemoryCache` without using `AddMemoryCache` when you've used either of the the following:

* `AddMvc()` (or `AddMvcCore().AddRazorViewEngine()`).
* `AddResponseCaching()`.

If you're *not* using `AddMvc`, please do let me know as I may have missed something.

**Comment by joelrlneto** [comment]
@serpent5 Thank you for the explanation.

Yes, I have called `AddMvc`. So this is why the cache  is working as you said.

Thank you again. I think this issue can be closed.
