### ISSUE TITLE
demonstrates using JavaScript/Angular to stream to a controller action incomplete

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/AspNetCore.Docs#11947]
Customer feedback:

I wasted a day working through this example which says that it "demonstrates using JavaScript/Angular to stream to a controller action”, but contains no javascript or angular code. Much of the documentation has links to full example code, but this one only had a few snippets and it was unclear how they combine to accomplish anything close to what the title and opening paragraph suggest. 

![image](https://user-images.githubusercontent.com/3605364/55987039-5e378200-5c3c-11e9-89d9-d5c29415794c.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a5cfa38-0e6c-4346-dafc-84ea5c513fcf
* Version Independent ID: c6787f0f-3e9a-6efb-0e6e-5ccb957d3f4a
* Content: [File uploads in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/models/file-uploads?view=aspnetcore-2.2#uploading-large-files-with-streaming)
* Content Source: [aspnetcore/mvc/models/file-uploads.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/mvc/models/file-uploads.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@Rick-Anderson There won't be JS/Angular in the updated approaches tracked by https://github.com/aspnet/AspNetCore.Docs/issues/10214. We could use this issue tho to track adding JS/Angular to the topic after #10214 is worked; however, it would have to be added by someone who works in Angular.

**Comment by Rick-Anderson** [comment]
Can we rip that out now?

**Comment by guardrex** [comment]
Sure. I'll do it by EOD.

**Comment by guardrex** [comment]
Buried in auth code at the moment! ⛏😅 ... I'll get it after I dig out of additional claims updates.

**Comment by guardrex** [comment]
@Rick-Anderson Just took a look at this. The reader isn't exactly correct. This section shows how to receive the stream from a client. True, it doesn't show the Angular side, but this is how it would (in theory) be set up on the ASP.NET Core side.

The problem is expectations: I guess some readers (or one reader) wants to see the Angular app, too, and we're not going to show that (guessing the reason is overhead).

What would you like to do?

* Leave it alone.
* Just cut the "Angular" language and comments and leave the section in a more generic form.

**Comment by Rick-Anderson** [comment]
Leave it alone.
