### ISSUE TITLE
short page

### ISSUE THREAD

**Issue by MohammadMQ** [aspnet/AspNetCore.Docs#11954]
You didn't put to much effort into this page, did you?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a5c47cc-5321-e928-79f7-af0f83fe06ff
* Version Independent ID: 7a89e12e-8e2c-4001-3d9a-ca732225d8ce
* Content: [Host and deploy Razor Components and Blazor](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/razor-components-blazor/index?view=aspnetcore-3.0)
* Content Source: [aspnetcore/host-and-deploy/razor-components-blazor/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/host-and-deploy/razor-components-blazor/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
This is a landing page, where you then move off to either Blazor or Razor Components. This is by-design because the only cross-cutting concern thus far (the most important) is publishing the app. If you have other cross-cutting content subjects that you would like to see, I'm all :ear: :ear: :ear: :ear:.

Also note that Blazor docs are still in preview, just like the bits in the framework itself. These topics are new and a work-in-progress. *Rome wasn't built in a day!* :smile:

@danroth27 Do you have any other cross-cutting *Host and Deploy* subjects that we need to cover at this time? If so, we can use this issue to track.

**Comment by danroth27** [comment]
We'll need to reconcile the client-side and server-side host and deploy content, but I don't think we need this issue to track that. Closing.

**Comment by guardrex** [comment]
@MohammadMQ Considerable improvements are coming for Preview 4 when the naming and layout of topics changes. Stand-by for those updates and then look again and let me know later what you think. No ETA yet, but the issues are on the Razor Components project. You can track the progress of the work there.

https://github.com/aspnet/AspNetCore.Docs/projects/35
