### ISSUE TITLE
Do call all data access APIs asynchronously.

### ISSUE THREAD

**Issue by yue-shi** [aspnet/AspNetCore.Docs#11964]
Even the call is really fast? Say 99.99 percentile is 20 ms.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9599d917-4e43-f1ae-452a-1f11aaa985ed
* Version Independent ID: 5cc05b6c-c671-3607-3217-7db73ebc1f28
* Content: [ASP.NET Core Performance Best Practices](https://docs.microsoft.com/en-us/aspnet/core/performance/performance-best-practices?view=aspnetcore-2.2#complete-long-running-tasks-outside-of-http-requests)
* Content Source: [aspnetcore/performance/performance-best-practices.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/performance/performance-best-practices.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-performance**
* GitHub Login: @mjrousos
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
yes

**Comment by mjrousos** [comment]
Hi @yue-shi. That's a good question since synchronous execution can be best if operations are very fast. In my experience, though, even fast data access operations are usually best done asynchronously - especially in a very multi-threaded scenario like an ASP.NET Core app.

I did a little experimenting and found that, as you guessed, very fast local SQL Server access (with the database on the same machine as the ASP.NET Core app) can be faster if performed synchronously. But for any sort of remote data access (even within the same Azure region), async access is better. The details will depend on the scenario (specifically, how fast data access is and how many requests will be querying data concurrently) but in my ad hoc experimenting, hot code paths performed better when they were async even with data access times as low as 1ms (in the hundreds of microseconds range, sync began to be better). The latency times at which synchronous access will beat async may increase if the data access is less frequent (I haven't tested this thoroughly), but those probably aren't the code paths that need to be super-optimized.

As with all performance questions, it's probably best to test your specific scenario both ways if you have very fast access times (<10ms) and think async overhead may be causing trouble. I think in the vast majority of cases, though, async will be the right approach.
