### ISSUE TITLE
Links to lots of Blazor docs are broken

### ISSUE THREAD

**Issue by LocalJoost** [aspnet/AspNetCore.Docs#11989]
# Issue description

Links to lots of Blazor docs are broken. See for instance

https://docs.microsoft.com/en-us/aspnet/core/razor-components/debug

**Comment by guardrex** [comment]
That's not very surprising ... we're in the midst of making sweeping changes to the locations of topics.

Did you get that link from the blazor.net site? I couldn't update those last night because the changes to the file locations on this repo hadn't gone live yet when I went to bed. I'm headed over to the blazor.net site now to make the updates, and I'll push those live immediately.

**Comment by LocalJoost** [comment]
No, I GoogleBinged it. To be clear I am not convicting anyone, I am a dev myself and I now this is all early days stuff and **** happens. I am just reporting :)

**Comment by guardrex** [comment]
🤔 Yeah ... we were going to avoid redirect file updates during preview (and got away with it for Pre3), but I think there has been so much traffic at this point at the old addresses that we don't have a choice now.

In addition to updating the blazor.net forwards, I'll put the redirect file entries in over here. That will help users and search engines find the content at the new locations.

Thanks for noting it.

**Comment by guardrex** [comment]
@LocalJoost You probably saw on the PR this morning: We discussed it, and we're going to forge ahead without the redirects.

We **_DO_** have them now coming over from the blazor.net site. Thanks for opening this as an early AM reminder for me to get those done asap. 🏃 Like I said earlier, I couldn't put them in yesterday because these doc location shifts occurred on the live site after I went to bed 🛌.

We believe that Google/Bing/etc. will catch up with us quickly.

We generally don't sweat preview doc redirects. There's just too much churn in URLs for docs during preview. Heck, we may move some docs around again for Preview 5 ... 6 ... release candidate. Just a lot of churn right now.

Let's see how it goes over the next couple of days/weeks. I'll check back with Google and Bing from time-to-time, and we'll monitor here for readers that run into broken search engine links. If it really becomes a nasty-bad problem, we'll reconsider putting the redirects in place.

**Comment by LocalJoost** [comment]
You are welcome. I just happened to come across it

Joost van Schaik

Windows Development MVP & Windows Insider MVP
Sent from my Surface Go

"The world as I envision it in my head is such a more interesting place"


________________________________

**Comment by guardrex** [comment]
Truly ... it's looking more and more likely that we'll need to put the redirects in. We just had another ping about broken links.

**Comment by guardrex** [comment]
Thanks again @LocalJoost ...... I had to enter the **_Federal Witness Protection Program_** on this one, and I have two armed guards tagging along with me now everywhere I go! :smile: lol

The redirects will go live shortly. 😅

**Comment by LocalJoost** [comment]
Uhm. What have I done? 😁

<http://www.9folders.com/>Joost van Schaik

Windows Development MVP

"The world as I envision it in my head is such a more interesting place"
________________________________
