### ISSUE TITLE
Response Caching: default approach cause user agents to cache errors

### ISSUE THREAD

**Issue by alefranz** [aspnet/AspNetCore.Docs#11990]
Edit by @guardrex: **This issue will be for John Luo to address at the next engineering doc sweep.**

This is to discuss potential improvements to the docs before raising a PR.

On the page, the recommended approach is to add a inline middleware that set `Cache-Control: public` for all requests, which cause user agents to potentially cache errors.
Not sure if the best approach here is to document a different approach (which would be more convoluted) or just add a warning,

I personally found misleading the following sentence:
> Response Caching Middleware only caches server responses that result in a 200 (OK) status code. Any other responses, including error pages, are ignored by the middleware.

Although this is correct, it should also warn of the side effects of setting the `Cache-Control` header.

What do you think?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 10cda0f9-e2c7-015d-4fbf-d361f6c67d9f
* Version Independent ID: 13154131-c2b6-2c72-fb0e-1d83bca4e21a
* Content: [Response Caching Middleware in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/performance/caching/middleware?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/performance/caching/middleware.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/performance/caching/middleware.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-performance**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @alefranz ... sounds good as long as the Exception Handling Middleware re-execution of the request is keeping that header. I like the idea of modifying the inline middleware. Let me play with it later this afternoon and get back to you ... I want to repro the behavior that you're seeing, and then we can compare notes and discuss it further.

**Comment by alefranz** [comment]
well in the middleware you either don't have the status code or, after the inner middleware execution, it would be too late to set response header.

I think the best approach would be to use a `IResultFilter`:
```
public class CachingFilterAttribute : Attribute, IResultFilter
    {
        public void OnResultExecuting(ResultExecutingContext context)
        {
            if (context.Result is StatusCodeResult statusCodeResult &&
                statusCodeResult.StatusCode == 200)
            {
                context.HttpContext.Response.GetTypedHeaders().CacheControl =
                    new CacheControlHeaderValue
                    {
                        Public = true,
                        MaxAge = TimeSpan.FromHours(1)
                    };
                context.HttpContext.Response.Headers[HeaderNames.Vary] = new[] {"Accept-Encoding,Accept"};
            }
        }

        public void OnResultExecuted(ResultExecutedContext context)
        {
        }
    }
```

**Comment by guardrex** [comment]
I'll get back to you later today. I'm 🏃🏃🏃😅  at the moment.

**Comment by guardrex** [comment]
**[TL;DR This issue will be for John Luo at the next engineering doc sweep.]**

ok 😅 ... just about caught up.

WRT this notion generally of adding the headers, the sample seems somewhat legacy given that the push is for a **cache profile** these days.

Note: The samp is 2.1 today, but a 2.2 sample update is *coming soon*. It's on my To Do list to get most of the samps updated for 2.2 before we reach 3.0 RTM. 🏃

Anywho ........

```csharp
services.AddMvc(options =>
{
    options.CacheProfiles.Add("Default",
        new CacheProfile()
        {
            Duration = 10,
            VaryByHeader = "Accept-Encoding"
        });
}).SetCompatibilityVersion(CompatibilityVersion.Version_2_1);
```

```csharp
[ResponseCache(CacheProfileName = "Default")]
public class IndexModel : PageModel
```

Cache profiles were available in *ancient times* (1.x :smile: lol). I think we/the original authors were just focusing on the basic caching scenario with the middleware. The inline middleware for adding headers was just meant to be quick-'n'-dirty demo code.

I agree with u that a note there would have been a good idea. We did add the note for authentication, and that might be expanded to include info on setting the header the way that is demonstrated.

It's also possible that cache profiles arrived at 1.1, but the topic actually goes all the way back to 1.0. That would also explain the presence of it.

> Response Caching Middleware only caches server responses that result in a 200 (OK) status code. Any other responses, including error pages, are ignored by the middleware.

I don't think it's misleading (to me) because that's speaking to the Response Caching Middleware's behavior and **_only_** that middleware. It isn't making any broader suggestions as far as I can tell. However if you found it misleading or unclear, then perhaps we can do something about that.

> well in the middleware you either don't have the status code or, after the inner middleware execution, it would be too late to set response header.

I'll defer to the engineer on that. I know that the Exception Handling Middleware runs very late. It changes the `Cache-Control` header if it has to. I don't know if where the error occurs in the pipeline can influence the Response Caching Middleware ... is there a point-of-no-return where an error can happen later than caching has actually occurred. Not sure. It's best for me to let the engineer, who is very familiar with that code base (he wrote it! lol) respond.

WRT your pitch for making it smarter, the Exception Handling Middleware should take care of the general page handler or controller exception scenario and update the header to **_not cache_** the response. *In the most general case*, it should work well.

WRT other scenarios (and the fact of how the `Cache-Control` header is currently added here via inline middleware), *Yes!* Let's ask the engineer (John Luo) how he would like to proceed. However, we can't ping him directly tho. I need to label this with the "PU" label, and then he'll look when they've set aside special time to look at docs issues. Sit tight for a bit for their next cycle to come around with us. I don't think it will take too long ... perhaps within just a few weeks.

**Comment by Rick-Anderson** [comment]
Thanks for contacting us.
We don’t have the resources to invest in this area, so we are closing the issue. Should your request generate enough  👍 responses, we’ll reconsider.
