### ISSUE TITLE
Actual gains?

### ISSUE THREAD

**Issue by Deathofdemigod** [aspnet/AspNetCore.Docs#12013]
For something saying that it's faster there should be a benchmark and comparison table.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 48e02614-5cdd-0c85-3193-75a2325326b4
* Version Independent ID: fca176e2-c56e-0f17-de1b-e60912091e4b
* Content: [High-performance logging with LoggerMessage in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/loggermessage?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/fundamentals/logging/loggermessage.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/logging/loggermessage.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @Deathofdemigod ... Seems like a good idea to me. IIRC, I wasn't presented with figures from engineering, and it would fall to them to produce such figures. If you would like to inquire further with the engineers on it, ask them on the [aspnet/Benchmarks repo](https://github.com/aspnet/Benchmarks). They *mostly* focus on overall framework perf, but there's no harm in asking them if they would be interested. If they do have figures (or are willing to provide them), then ping me back over here on this issue, and I'll re-open it so that we can improve the doc when we have figures in hand.
