### ISSUE TITLE
EF Core: Don't put this code in your project; it's here just to illustrate an alternative, why?

### ISSUE THREAD

**Issue by ahmedalejo** [aspnet/AspNetCore.Docs#12080]
Could more elaboration be done on the following instruction?
> [Don't put this code in your project; it's here just to illustrate an alternative](https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/crud?view=aspnetcore-3.0#the-create-and-attach-approach-to-httppost-delete)
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d420a47c-b0c7-b242-3116-3d6382467ffb
* Version Independent ID: 06d9d8e6-7069-fd79-561c-363cc4487821
* Content: [Tutorial: Implement CRUD Functionality - ASP.NET MVC with EF Core](https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/crud?view=aspnetcore-3.0)
* Content Source: [aspnetcore/data/ef-mvc/crud.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/data/ef-mvc/crud.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **tdykstra**

**Comment by Rick-Anderson** [comment]
It breaks the tutorial. Feel free to explore the alternative.

**Comment by tdykstra** [comment]
@ahmedalejo The beginning of that paragraph explains the reason why you might choose this alternative -

> If improving performance in a high-volume application is a priority, you could avoid an unnecessary SQL query 

If performance isn't a problem, the first code block shown is the recommended way, and that's why it's the one used for the tutorial.  Your're free to choose the alternative method in your own apps, but later tutorials in this series build on the recommended code, which is the reason for advising against using the alternative code in the tutorial. 

After the snippet is more text explaining something to be aware of if you choose the alternative method for your apps.

> If the entity has related data that should also be deleted, make sure that cascade delete is configured in the database. With this approach to entity deletion, EF might not realize there are related entities to be deleted.
