### ISSUE TITLE
IIS vs IIS Express deployment / debug

### ISSUE THREAD

**Issue by Nitro66215** [aspnet/AspNetCore.Docs#12197]
I've followed this section and done a lot of google searching. However, under Debug - IIS Express with IIS Express as the "Launch" setting, I am able to pass through my Windows Credentials to our SQL server. It authenticates fine. When published to my local IIS OR using IIS as the "Launch" (Assuming that's the same), the authentication passed to SQL is the local computer domain account. I've worked with making sure the applicationHost.config is correct as well as making sure the web.config file is set correctly. Is there something glaring I'm missing with the other configurations?

I've also tried AspNetCore 2.0,2.1 and attempted 2.2, but I cannot use that since I have a project with .Net Standard 2.0 attached. 2.2 will not work with .Net Standard 2.

I've also attempted to publish this to a Windows 10 computer and have the same results. 

Local Windows 7
VS2017 Debug....
Under Launch IIS Express...
Launch browser checked....
Environment variables ... ASPNETCORE_ENVIRONMENT = Development (I've done Production as well)
IIS Express Bitness - Default
Hosting Model - Default
Enable SSL Checked.
Enable Anonymous Auth - NOT checked
Enable Windows Auth - Checked.

Under Launch IIS
SSL / IIS Express Bitness Settings aren't available. Everything else remains the same.

applicationhost.config ...

&lt;-----&gt;
 &lt;sectionGroup name="authentication"&gt;
                    &lt;section name="anonymousAuthentication" overrideModeDefault="Allow" /&gt;
                    &lt;section name="basicAuthentication" overrideModeDefault="Deny" /&gt;
                    &lt;section name="clientCertificateMappingAuthentication" overrideModeDefault="Deny" /&gt;
                    &lt;section name="digestAuthentication" overrideModeDefault="Deny" /&gt;
                    &lt;section name="iisClientCertificateMappingAuthentication" overrideModeDefault="Deny" /&gt;
                    &lt;section name="windowsAuthentication" overrideModeDefault="Allow" /&gt;
                &lt;/sectionGroup&gt;
&lt;--- &gt;.....
  &lt;authentication&gt;
                &lt;anonymousAuthentication enabled="false" userName="" /&gt;
                &lt;basicAuthentication enabled="false" /&gt;
                &lt;clientCertificateMappingAuthentication enabled="false" /&gt;
                &lt;digestAuthentication enabled="false" /&gt;
                &lt;iisClientCertificateMappingAuthentication enabled="false"&gt;
                &lt;/iisClientCertificateMappingAuthentication&gt;
                &lt;windowsAuthentication enabled="true"&gt;
                    &lt;providers&gt;
                        &lt;add value="NTLM" /&gt;
                    &lt;/providers&gt;
                &lt;/windowsAuthentication&gt;
            &lt;/authentication&gt;

            &lt;authorization&gt;
                &lt;add accessType="Deny" users="*" /&gt;
            &lt;/authorization&gt;

web.config
&lt;?xml version="1.0" encoding="utf-8"?&gt;
&lt;configuration&gt;
  &lt;location path="." inheritInChildApplications="false"&gt;
    &lt;system.webServer&gt;
      &lt;aspNetCore processPath="%LAUNCHER_PATH%" stdoutLogEnabled="true" stdoutLogFile=".\logs\stdout" arguments="%LAUNCHER_ARGS%"&gt;
        &lt;environmentVariables&gt;
          &lt;environmentVariable name="ASPNETCORE_ENVIRONMENT" value="Development" /&gt;
          &lt;environmentVariable name="ASPNETCORE_HTTPS_PORT" value="44399" /&gt;
        &lt;/environmentVariables&gt;
      &lt;/aspNetCore&gt;
      &lt;handlers&gt;
        &lt;add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModuleV2" resourceType="Unspecified" /&gt;
      &lt;/handlers&gt;
      &lt;security&gt;
        &lt;authentication&gt;
          &lt;windowsAuthentication enabled="true" /&gt;
        &lt;/authentication&gt;
      &lt;/security&gt;
    &lt;/system.webServer&gt;
  &lt;/location&gt;
&lt;/configuration&gt;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 401ad9a0-9e51-80a2-5846-82e9790d7257
* Version Independent ID: fbc36c26-9992-1f4c-66d3-02f898ee7ec4
* Content: [Configure Windows Authentication in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/windowsauth?view=aspnetcore-2.1&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/security/authentication/windowsauth.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/windowsauth.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @scottaddie
* Microsoft Alias: **riande**

**Comment by Nitro66215** [comment]
Note: I ran the customer applicationhost.config via iisexpress /config:c:\myconfig\applicationhost.config /site:*MySite* ... and it loaded and used windows authentication fine.

**Comment by Nitro66215** [comment]
I fixed this issue.... but still have the windows authentication problem when under published IIS application.

 <authorization>
                <add accessType="Allow" users="*" />
            </authorization>

**Comment by Nitro66215** [comment]
This issue..... ***
   &lt;authorization&gt;
            &lt;add accessType="Allow" users="*" /&gt;
        &lt;/authorization&gt;

**Comment by guardrex** [comment]
Hello @Nitro66215 ... There's some overlap here between your issue and another one that we'll probably work: https://github.com/aspnet/AspNetCore.Docs/issues/12144. I'm glad that you were able to get that aspect (IIS Express) working.

WRT the IIS problem ... That authorization rule looks correct. If you have WinAuth enabled on that server, I'm not sure what the problem might be. For guidance, we link off to [Windows Authentication \<windowsAuthentication>](https://docs.microsoft.com/iis/configuration/system.webServer/security/authentication/windowsAuthentication/). You probably also saw their guidance for [\<add>](https://docs.microsoft.com/iis/configuration/system.webserver/security/authorization/add). We don't currently link out for troubleshooting guidance, but there is quite a bit out there. I'll see about that when I work on #12144.

If you're stuck and the IIS guidance and blogs don't help, I suggest posting to a support forum, such as Stack Overflow, or a support chat, such as Slack or Gitter.

Since there isn't a docs issue yet ... I mean the problem is currently unknown ... I'll close this as a duplicate of #12144. When I get to that issue, I'm going to walk the whole topic for IIS and confirm that the guidance is good. I'll also see if I can find a good troubleshooting topic offered by the IIS team (i.e., in the IIS docs) on WinAuth troubleshooting. If you find out what the problem is and fix it, please feel free to post it here. I'll see this again when I work #12144.

**Comment by Nitro66215** [comment]
Ok Thanks. I figure that IIS Express is built into VS and uses the logged in Users identity. That is why it works. Same as if I run the EXE / DLL from Dotnet command line. It's running as me, so it authorizes it. The issue is on the Deployed server. Whatever you find, please let me know. I'll keep digging.
