### ISSUE TITLE
How to use logging in a console application or a class library

### ISSUE THREAD

**Issue by Bartolomeus-649** [aspnet/AspNetCore.Docs#12250]
No info on how to use logging in non web applications, like a pure console application or a class library.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7184a308-a254-9350-a5cd-5bced1f369ae
* Version Independent ID: 726e3bf1-f367-d733-8933-bccc04da0e16
* Content: [Logging in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-2.2#logging-in-azure)
* Content Source: [aspnetcore/fundamentals/logging/index.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/logging/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
@Bartolomeus-649 Good point, thanks for bringing it up. We're aware of the documentation gap and have a discussion about it going in issue https://github.com/dotnet/docs/issues/4567 in the .NET docs repo.  Since we're tracking it there I'll close this one as a duplicate.  Feel free to add comments in 4567.
