### ISSUE TITLE
Parameter is counter-intuitive

### ISSUE THREAD

**Issue by EEaglehouse** [aspnet/AspNetCore.Docs#12262]
Why in the world is the parameter `IncrementAmount` declared private but allowed to be set from an external call? Anything that is declared private should not be available outside the component it belongs to. That's bad design.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c07e57dc-526f-9479-4695-de7d8f06eb9a
* Version Independent ID: 8226ed72-69b2-3c93-a931-218bd11cf9c8
* Content: [Get started with Blazor](https://docs.microsoft.com/en-us/aspnet/core/blazor/get-started?view=aspnetcore-3.0&tabs=visual-studio)
* Content Source: [aspnetcore/blazor/get-started.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/get-started.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello ... It's not set via an external call. It's a parameter for the Counter component.

I'm going to close here because we only handle doc issues on this repo. You can open an issue for Blazor product feedback on the aspnet/AspNetCore repo. The product engineers and managers receive feedback there for Blazor ...

https://github.com/aspnet/AspNetCore/issues
