### ISSUE TITLE
About Blazor Documentation

### ISSUE THREAD

**Issue by Honda99** [aspnet/AspNetCore.Docs#12299]
Does the documentation edited for Preview 4.

I have tried the javascript Introp in preview 4 but the procedure cannot work for me.

**Comment by guardrex** [comment]
Hello @Honda99 ... Yes, they were updated for Preview 4 (and Preview 5 updates have been merged and are live now).

What step (or steps) in the doc isn't working? If it's something quick that I can answer quickly here, I will. Otherwise, I'll recommend a support forum, such as Stack Overflow, or a support chat, such as Slack or Gitter. There are only a handful of doc authors here, so we don't have the staffing to offer general product support.
