### ISSUE TITLE
Potential Path traversal issue in the sample

### ISSUE THREAD

**Issue by omerlh** [aspnet/AspNetCore.Docs#12292]
The docs have the following line of code:
```
Path.Combine(_env.ContentRootPath, "wwwroot/images/upload", filename);
```
Which might be vulnerable to path traversal (e.g. when filename is `../../../` or something like that. Please correct me if I'm missing something, I'm not an expert.
As people (including myself) tend to copy-paste code from docs - maybe worth adding a note here? Look like fixing the issue requires some regex (see [this post](https://blog.mindedsecurity.com/2018/10/how-to-prevent-path-traversal-in-net.html)) and will make the example a lot harder to read.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cfb00531-4ac6-8bf6-9bd8-1eed6446397f
* Version Independent ID: ed418d09-6c33-699a-0d48-9aabc99457be
* Content: [Custom Model Binding in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/advanced/custom-model-binding?view=aspnetcore-2.2)
* Content Source: [aspnetcore/mvc/advanced/custom-model-binding.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/advanced/custom-model-binding.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Side note ... looks like `WebRootPath` would be better ...

```csharp
Path.Combine(_env.WebRootPath, "images", "upload", filename);
```

... but ... **_BUT_** ... that's not something (*wwwroot*) that I think we want to have as an example here. I think we should do like you, @ardalis, have over in file uploads topic:

* Don't save files into the app's directory tree. Put the file at some out-of-the-app path.
* Validate (or cleanse) the file name.

I'm glad you said something about this @omerlh. I'm working on file uploads topic updates. I'm currently using `Path.GetInvalidFileNameChars`, but I need to confirm that slashes (either forward or backward) are prevented by my current approach. If not, I'm going to do something a bit different.

**Comment by omerlh** [comment]
`Path.GetInvalidFileNameChars` sounds like an amazing addition to dotnet. I'm really happy you're adding it :) Looking forward to seeing the updated docs!

**Comment by guardrex** [comment]
The good news is that (at least on Windows) the invalid chars include forward slashes and backslashes ...

```
< > | ?        
   
                   : * ? \ /
```

I'll assume for the time being that what I have is good. When the engineers look :eyes: at the PR, we'll see what they have to say about it.

Example from the upcoming file uploads topic updates ...

```csharp
var invalidFileNameChars = Path.GetInvalidFileNameChars();
var trustedFileName = invalidFileNameChars.Aggregate(
    contentDisposition.FileName.Value, (current, c) => current.Replace(c, '_'));
```

**Comment by omerlh** [comment]
Why not having `Path.Sanitize` helper method?

**Comment by guardrex** [comment]
Because devs cut-and-paste from sample apps into their own apps and we really don't know if they intend to have more than one file upload in their app. If a file upload is only one spot and these lines only appear once in an app, it's perfectly fine to just have the lines.

**Comment by omerlh** [comment]
Thanks! 👏

**Comment by guardrex** [comment]
Correct @omerlh ... security guidance is to use a completely random (or app-generated) file name. Since the sample app associated with this topic doesn't display the human-readable file name, it has no need to HTML-encode the file name.

btw- These updates haven't gone live yet. They'll go live soon tho ... within a day or two probably.

**Comment by omerlh** [comment]
I understand, but maybe worth adding a comment? Something like "if you use this code in production, please ensure you're sanitizing the input by doing <>"? Copy-pasting is one of the biggest security risks :)

**Comment by guardrex** [comment]
That's all gone now (after the PR merges to `live`). A reader can cut-'n-paste the updated code without that risk because the file name isn't used to save the file. The way that the code composes now (after the PR goes in), the `ProfileViewModel`'s `FileName` would be supplied by the user via a web API call or form. The latest security guidance is to go ahead and store that value (e.g., in a dB) as it is (or in addition to a server-side model validation and `ModelState` check, which the sample doesn't do anyway) and then HTML-encode it for display (also something the sample doesn't do anyway). There's a note in the code comments not to trust the file name if they do decide to add code to use it. I think this will be ok for now.

**Comment by omerlh** [comment]
Sounds interesting, looking forward to seeing the updated docs!
