### ISSUE TITLE
The scoped service example is not really async enough to help anyone

### ISSUE THREAD

**Issue by AnthonyMastrean** [aspnet/AspNetCore.Docs#12342]
The "do work" method is actually synchronous and your async methods return completed tasks. You should show an actual example of running a method that properly returns an incomplete Task (because then you need to get async/await right or you won't dispose of your scoped services in the proper time).

https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/hosted-services?view=aspnetcore-2.1#consuming-a-scoped-service-in-a-background-task

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3460b0d-9c60-3a06-ac63-18cf990e53c3
* Version Independent ID: b2dece1f-15b8-03af-6d52-7cc070432b4b
* Content: [Background tasks with hosted services in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/hosted-services?view=aspnetcore-2.1#feedback)
* Content Source: [aspnetcore/fundamentals/host/hosted-services.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/host/hosted-services.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @AnthonyMastrean ... this was approved by engineering. I'll mark it with the "PU" label so that they'll be flagged to take a look. Thanks for commenting on it.

**Comment by guardrex** [comment]
@AnthonyMastrean Sorry for the *loooooong delay* 🕙 We were 🏃🏃😅 on 3.0 updates for a few months. We did get back to this topic's sample on another issue in a similar vein. I'm going to mark that PR (#14765) as fixing this issue, too. However, please look at the PR and remark over there if you feel that there are still problems to address ..... and I recommend that you look soon on that one because it's about to merge. If you don't get a chance to look soon tho:

* Let's go ahead and let this issue close.
* Open a new issue using the **This Page** feedback form at the bottom of the topic. We can do more work on the topic on a new issue if needed.

This issue will auto-close when that PR merges.
