### ISSUE TITLE
Add unit tests to practical example

### ISSUE THREAD

**Issue by suchoss** [aspnet/AspNetCore.Docs#12350]
Hello, I found your tutorial the best so far from what I've seen, but I am wondering, how should I add unit tests for BookService? 

If I understand it correctly then BookService should contain business logic and it should be testable, but since it is dependent on IConfiguration it is hard to test.

```
public BookService(IConfiguration config)
{
    var client = new MongoClient(config.GetConnectionString("BookstoreDb"));
    var database = client.GetDatabase("BookstoreDb");
    _books = database.GetCollection<Book>("Books");
}
```

Wouldn't following constructor be better for testing?
```
public BookService(IDbContext dbContext)
{
}
```

Btw. I saw somewhere that Db service should be transient (can't remember exactly where and why), but I see, that you are using scoped service. Can I ask why?

Many thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5240866d-d0a1-f0dd-7b2c-203e1d69bc4b
* Version Independent ID: 83a5cb3b-23bc-4f0c-cd1c-1d1ffeb1131a
* Content: [Build web APIs with ASP.NET Core and MongoDB](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mongo-app?view=aspnetcore-2.2&tabs=visual-studio-code#feedback)
* Content Source: [aspnetcore/tutorials/first-mongo-app.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-mongo-app.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @prkhandelwal
* Microsoft Alias: **scaddie**

**Comment by prkhandelwal** [comment]
Hi @suchoss 

Thanks for your really insightful questions. Deciding whether your DB Service should be transient or scoped really depends on the nature of your application. For example, if each of your api call is a `Unit of Work`, then it is better to go with Scoped service. It is good since you can maintain context during the request, while you are keeping it isolated from other requests (While also avoiding creating a new connecting for each operation). 

Transient services have their own uses. I usually prefer to go transient when I have classes which could be used multiple times and have internal states that must not be shared. 

Scoped is a better fit imo in this case, would love to hear your thought on it. 

For writing Unit Tests, you could refer to this [link](https://weblog.west-wind.com/posts/2018/Feb/18/Accessing-Configuration-in-NET-Core-Test-Projects). I hope it helps. 🖖

**Comment by Rick-Anderson** [comment]
Hello! Thanks for contacting us. This sounds like a general question about using ASP.NET Core. While we try to look at and respond to all issues, for questions like this we recommend posting to a community support group like [Stack Overflow](https://stackoverflow.com) with the `asp.net-core` tag.
