### ISSUE TITLE
Please document required call to AddApiExplorer() when using services.AddMvcCore()

### ISSUE THREAD

**Issue by JoePercy-Capp** [aspnet/AspNetCore.Docs#12400]
When ConfigureServices contains `services.AddMvcCore()` instead of `services.AddMvc()`, you need to chain a call to `AddApiExplorer()` (i.e. `services.AddMvcCore().AddApiExplorer()`) in order for the required services to be available for NSwag middleware to DI.

Couldn't find this anywhere on this page or in the NSwag docs and wasted time figuring this out when a couple of lines of explanation on this page would have avoided the issue :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2483813a-3c16-7ddd-3160-43e6843b55d4
* Version Independent ID: 25f7fb5b-92b0-a45b-57ab-fdceab571884
* Content: [Get started with NSwag and ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-nswag?view=aspnetcore-2.2&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/tutorials/getting-started-with-NSwag.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/getting-started-with-NSwag.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @zuckerthoben
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
Why are you calling `services.AddMvcCore()` instead of `services.AddMvc()` ? 

[`AddMvcCore`: ](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.dependencyinjection.mvccoreservicecollectionextensions.addmvccore?view=aspnetcore-2.2#Microsoft_Extensions_DependencyInjection_MvcCoreServiceCollectionExtensions_AddMvcCore_Microsoft_Extensions_DependencyInjection_IServiceCollection_) Adds the minimum essential MVC services to the specified . Additional services including MVC's support for authorization, formatters, and validation must be added separately using the returned from this method.
