### ISSUE TITLE
Running dotnet new -i in step to returns 401 (unauthorized)

### ISSUE THREAD

**Issue by itanex** [aspnet/AspNetCore.Docs#12413]
I just ran step #2 in my admin privileged console. I get the following output, followed by help on the new command, anad the template list below that. I am up to date on the SDK. Is there a step missing?

` Retrying 'FindPackagesByIdAsyncCore' for source 'https://microsoft.pkgs.visualstudio.com/DefaultCollection/_packaging/Universal.Store/nuget/v2/FindPackagesById()?id='Microsoft.AspNetCore.Blazor.Templates'&semVerLevel=2.0.0'.
  Response status code does not indicate success: 401 (Unauthorized).
  Retrying 'FindPackagesByIdAsyncCore' for source 'https://microsoft.pkgs.visualstudio.com/DefaultCollection/_packaging/Universal.Store/nuget/v2/FindPackagesById()?id='Microsoft.AspNetCore.Blazor.Templates'&semVerLevel=2.0.0'.
  Response status code does not indicate success: 401 (Unauthorized).
  Restore completed in 801.87 ms for C:\Users\v-brwoo\.templateengine\dotnetcli\v3.0.100-preview5-011568\scratch\restore.csproj.`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c07e57dc-526f-9479-4695-de7d8f06eb9a
* Version Independent ID: 8226ed72-69b2-3c93-a931-218bd11cf9c8
* Content: [Get started with Blazor](https://docs.microsoft.com/en-us/aspnet/core/blazor/get-started?view=aspnetcore-3.0&tabs=visual-studio)
* Content Source: [aspnetcore/blazor/get-started.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/get-started.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @itanex ... it's a product unit question. Open it over on the engineering repo for them to see: [aspnet/AspNetCore issues](https://github.com/aspnet/AspNetCore/issues).

Search first tho (open and closed issues) .... there might be an existing issue ... someone who hit the same thing.

**Comment by guardrex** [comment]
@itanex It isn't something that I've seen to-date; but if you get a response that seems like something the doc should address, plz add a note back here on this issue. We might need to note a common failure scenario for installing the templates in the Get Started topic.

**Comment by itanex** [comment]
I posted here because I was following the documents instructions and my experience did not align with the document. I will check out aspnet.core resource.

**Comment by guardrex** [comment]
Yes ... let me explain a bit more. We get doc issues from the **This Page** doc feedback button from time-to-time that are really bugs or strange behaviors that we need engineering help to resolve.

I haven't seen the error that you reported. I think the engineers who build the framework should see your error. They work on the aspnet/AspNetCore repo and don't monitor these doc issues very closely.

The best way to get them to look at a potential product problem is to open an issue over there. If they figure out that a common scenario that leads to an error should be covered by the docs, we re-open the issue over here and work it on the docs team.

Open an issue over there ...... but for sure ... plz do post back here what the cause of the problem was. I'll re-open this issue if it's something that devs are going to hit regularly.
