### ISSUE TITLE
The module at ClientApp/dist/server/main.js does not export a default function, and you have not specified which export to invoke

### ISSUE THREAD

**Issue by maurisa11** [aspnet/AspNetCore.Docs#12434]
I have the next problem when I run my asp .net core app:

**NodeInvocationException: Prerendering failed because of error: Error: The module at ClientApp/dist/server/main.js does not export a default function, and you have not specified which export to invoke.**

This is my startup.cs file:

`       app.UseSpa(spa =>
        {
            // To learn more about options for serving an Angular SPA from ASP.NET Core,
            // see https://go.microsoft.com/fwlink/?linkid=864501

            spa.Options.SourcePath = "ClientApp";

            spa.UseSpaPrerendering(options =>
            {
                options.BootModulePath = $"{spa.Options.SourcePath}/dist/server/main.js";
                options.BootModuleBuilder = env.IsDevelopment()
                    ? new AngularCliBuilder(npmScript: "build:ssr")
                    : null;
                options.ExcludeUrls = new[] { "/sockjs-node" };
            });

            if (env.IsDevelopment())
            {
                spa.Options.StartupTimeout = new System.TimeSpan(0,5,0);
                //spa.UseAngularCliServer(npmScript: "start");
                spa.UseProxyToSpaDevelopmentServer("http://localhost:4200");
            }
        });`

and if I did:  node -e "console.log(require('./ClientApp/dist/server/main.js'))"
this is the result:

> `{ LAZY_MODULE_MAP:
   { './admin/admin.module#AdminModule':
      NgModuleFactory_ {
        moduleType: [Function: AdminModule],
        _bootstrapComponents: [],
        _ngModuleDefFactory: [Function] },
     './investor/investor.module#InvestorModule':
      NgModuleFactory_ {
        moduleType: [Function: InvestorModule],
        _bootstrapComponents: [],
        _ngModuleDefFactory: [Function] },
     './restaurant/restaurant.module#RestaurantModule':
      NgModuleFactory_ {
        moduleType: [Function: RestaurantModule],
        _bootstrapComponents: [],
        _ngModuleDefFactory: [Function] } },
  AppServerModuleNgFactory:
   NgModuleFactory_ {
     moduleType: [Function: AppServerModule],
     _bootstrapComponents: [ [Function: AppComponent] ],
     _ngModuleDefFactory: [Function] },
  AppServerModule: [Function: AppServerModule] }`

Someone can help me?

I need to finish the implementation of angular universal on my app.

**Comment by Rick-Anderson** [comment]
Hello! Thanks for contacting us. This sounds like a general question about using ASP.NET Core. While we try to look at and respond to all issues, for questions like this we recommend posting to a community support group like [Stack Overflow](https://stackoverflow.com) with the `asp.net-core` tag.

**Comment by PieterjanDeClippel** [comment]
Did you find a solution for this. I'm facing the same problem. ASP.NET Core docs aren't very clear about SSR.

**Comment by MahnazSheikhi** [comment]
Hi @maurisa11 .
Did you find a solution for this? I'm facing the same problem. 
I did an example in the following article and I came across the same problem.

https://medium.com/@pieterjandeclippel/server-side-rendering-in-asp-net-core-angular-6df7adacbdaa

https://github.com/PieterjanDeClippel/AspNetCoreSpaPrerendering?source=post_page---------------------------

Did you find the answer to this problem?

**Comment by PieterjanDeClippel** [comment]
Hi @MahnazSheikhi,

I pushed a new version to a new repository:
https://github.com/PieterjanDeClippel/AspNetCoreSpaPrerendering
I tried to clone this one and now it **does** seem to be working fine.

If you still encounter an issue, can you please post me the output of following commands in cmd (windows+R --> cmd).
node -v
npm -v
ng version

From a directory not within an angular project.
My output:

```
PS C:\Users\pidc> node -v
v10.15.3
PS C:\Users\pidc> npm -v
6.4.1
PS C:\Users\pidc> ng version
Angular CLI: 8.1.2
Node: 10.15.3
OS: win32 x64
Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.801.2
@angular-devkit/core         8.1.2
@angular-devkit/schematics   8.1.2
@schematics/angular          8.1.2
@schematics/update           0.801.2
rxjs                         6.4.0
```

**Comment by MahnazSheikhi** [comment]
Thanks @PieterjanDeClippel 
Your example works:

https://github.com/PieterjanDeClippel/AspNetCoreSpaPrerendering

**Comment by GitMonkey007** [comment]
Also confirm that it works. For anyone following, I did

cd ClientApp
npm install
npm run build:ssr

followed by running the application from VS2017. Appears to work under both IIS and Kestrel. Thanks @PieterjanDeClippel !

**Comment by PieterjanDeClippel** [comment]
You're getting the same exception when in your `angular.json` the property `projects:ClientApp:architect:server:options:main` is set to `server.ts` instead of `src/main.server.ts`. It should be set to `src/main.server.ts`

**Comment by jitterbox** [comment]
@PieterjanDeClippel 
I've been trying to get SSR working w/ .NET 6/Angular 14 for *literally* weeks now, mostly following your examples.
When I have angular.json's architect:server:options:main set to "**server.ts**", I get the **main.js** error above.
But when I change it to "**src/main.server.ts**", running `ng run ClientApp:serve-ssr` compiles, but Node.js exits with:
`connect ECONNREFUSED 127.0.0.1:49182`. 

In the official [Angular Universal sample project](https://angular.io/generated/zips/universal/universal.zip) it has main set to **server.ts**...

**Comment by PieterjanDeClippel** [comment]
@jitterbox 
For a starter, as you state the server main entrypoint is by default set to `server.ts`. For .NET (or at least the current state of the code) this is a problem because the NodeServices for .NET only supports commonJS bundles. So we need a custom implementation of the server BootModule. We ARE able to specify which export from BootModule we want to invoke, but atm we cannot use EcmaScript, but have to use CommonJS instead.

Therefor we leave the `server.ts` for what it is, we're not using it. We'll just modify the `src/main.server.ts`.

From the `main.server.ts` you should have the default export from the `aspnet-prerendering` node package. I haven't been able to do a deep-dive there, but this should still work fine.

1) main.server.ts
```
import 'zone.js/dist/zone-node';
import '@angular/platform-server/init';

import { renderModule, renderModuleFactory } from '@angular/platform-server';
import { APP_BASE_HREF } from '@angular/common';
import { enableProdMode, StaticProvider, Inject } from '@angular/core';
import { createServerRenderer, BootFuncParams } from 'aspnet-prerendering';
import { environment } from './environments/environment';

export default createServerRenderer(params => {
	const { AppServerModule, AppServerModuleNgFactory, LAZY_MODULE_MAP } = (module as any).exports;

	const options = {
		document: params.data.originalHtml,
		url: params.url,
		extraProviders: []
	};

	// Bypass ssr api call cert warnings in development
	process.env['NODE_TLS_REJECT_UNAUTHORIZED'] = "0";

	const renderPromise = AppServerModuleNgFactory
		? /* AoT */ renderModuleFactory(AppServerModuleNgFactory, options)
		: /* dev */ renderModule(AppServerModule, options);

	return renderPromise.then(html => ({ html }));
});

export { renderModule } from '@angular/platform-server';
export { AppServerModule } from './app/app.server.module';
```

2) This is why you should update your angular.json and set the server-main to `src/main.server.ts`. I think however you can also just paste the `createServerRenderer` in the `server.ts` as well, without changing the angular.json.

3) Try and run `npm run build:ssr`. This generates your bootmodule
4) There's no reason to call `npm run serve:ssr` as you're doing. This only works for node. .NET will just invoke the bootmodule from the path you've specified (the file that only starts to exist after running `npm run build:ssr`) and take the output from this, and serve it through the `UseSpaPrerendering` middleware.

-----------
Some more catches:
- When running Visual Studio as administrator or from a laptop inside a corporate network, don't let the application run `npm install`. Open a non-elevated cmd, navigate to the **ClientApp** folder, and run `npm install` yourself after you've cloned a repo
- The `architect:build:options:outputPath` **MUST BE** set to `dist`. I've never got it fixed to work with another value specified here...
