### ISSUE TITLE
Do we have to stop current websites before updating runtime?

### ISSUE THREAD

**Issue by DanJ210** [aspnet/AspNetCore.Docs#12430]
I didn't see anything about this so I'm asking. If I'm installing a new runtime first, then removing/uninstalling the old one which leaves only the new one installed, do I have to stop the websites that are being hosted on IIS? Would be good to cover in the documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec484002-18c1-6a0d-00de-820d56f038d3
* Version Independent ID: 7903ce53-2cbb-f083-7479-c8abc30211a0
* Content: [Host ASP.NET Core on Windows with IIS](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/host-and-deploy/iis/index.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/host-and-deploy/iis/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
*Ah!* Good question @DanJ210! 🏎

Indeed, the doc doesn't address what happens to live sites if the ANCM and runtime (patch version, for example) is replaced on-the-fly while requests are hitting live apps. Rubber 🦆 says that until the app recompiles a patch runtime update won't take effect and the app won't get the patch goodness until it does (e.g., worker process recycles). On ANCM replacement, rubber 🦆 says that WAS will stop-start ✨  *auto-magically* ✨ for you. If so, it will result in a brief delay in request processing.

We don't trust silly rubber 🦆 around here tho ... @joeloff @jkotalik ... I'll react to your guidance for an update to cover this.

**Comment by DanJ210** [comment]
Well thank you! The main thing I'm worried about is if anything would get corrupted. But sounds like no problems should arise that would corrupt anything.

**Comment by guardrex** [comment]
Yes, I doubt corruption ... guessing two things should be addressed in the topic:

* Patch updates to the runtime with roll-forward framework behavior. Does the app get a runtime patch when it eventually recompiles? ... **and not before then**.
* ANCM replacement ... does IIS restart automatically? ... so that there's just a short delay in request processing as IIS comes back online and apps fire back up with the new module?

**Comment by guardrex** [comment]
@DanJ210 Engineers are busy ... I'm marking this with the "PU" label ("Product Unit"). When they get some time, they'll look and let us know.

**Comment by cremor** [comment]
I'd also like to see the documentation of the "runtime update process" improved.

Today I updated to 2.2.6 (just by installing the new hosting bundle, I didn't uninstall the old one) and my site was automatically restarted **4** times in a time span of just 10 seconds. No manual requests reached the site during this time, but I have the [Application Initialization Module](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/?view=aspnetcore-2.2#application-initialization-module) enabled so IIS triggert one request for each restart. This seems a bit excessive and would be nice if it was documented.

I'm especially confused that I saw the 4 restarts because it was once documented in #8436 that the installer calls an IIS reset, but that note was later removed again in #11629 because appearantly it doesn't (https://github.com/aspnet/AspNetCore/issues/7615#issuecomment-467992410)?
aspnet/AspNetCore#3847 also says that an IIS restart is not planned.

As you can see, I'm a bit lost. There is no "official" documentation about the restart behavior and the Github issues don't match what I've seen during the update.

In the case there are differences between a first install and an update of the ASP.NET Core Module, please also make this clear when you update the documentation.
