### ISSUE TITLE
What's the default forwarded headers middleware settings for Razor Pages apps 

### ISSUE THREAD

**Issue by spacecat** [aspnet/AspNetCore.Docs#12506]
I'm confused by the following sentence:

"Forwarded Headers Middleware is enabled by default by IIS Integration Middleware when the app is run behind IIS and the ASP.NET Core Module."

Is "Forwarded Headers Middleware" enabled by default in Razor Pages apps? Because I'm not really sure what you mean by "IIS Integration Middleware" and "IIS and the ASP.NET Core Module". 

When testing though the request headers are proxied from the nginx ingress to my Razor Page app so it seems the forwarded headers middleware is enabled by default. Plus UseForwardedHeaders() is not needed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e548cd16-b06c-5802-a1a7-c627167857ae
* Version Independent ID: c48abb08-bea3-dcff-c067-2edf5dc9b3a6
* Content: [Configure ASP.NET Core to work with proxy servers and load balancers](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-2.2#forwarded-headers)
* Content Source: [aspnetcore/host-and-deploy/proxy-load-balancer.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/host-and-deploy/proxy-load-balancer.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@spacecat Yes ... AFAIK, that's correct. Since "app" refers to any kind of ASP.NET Core app, I think the guidance is ok ........ except for one thing ...

> not really sure what you mean by "IIS Integration Middleware"

... cross-linking to what that middleware is.

I'll cross-link it over to the IIS topic where that middleware is described. Actually ... I see about 4-6 places across the docs where that middleware name appears and it isn't cross-linked. I'll get them all in one shot.

It should be linked to this :point_right: https://docs.microsoft.com/aspnet/core/host-and-deploy/iis/#enable-the-iisintegration-components.

... and I see that I need to include the middleware name where it describes `UseIISIntegration`.

Thanks for calling this out.

**Comment by spacecat** [comment]
Great, thanks for confirming this! :)
