### ISSUE TITLE
Sequence numbers in cycles

### ISSUE THREAD

**Issue by arivoir** [aspnet/AspNetCore.Docs#12504]
Could you explain how sequence numbers work inside a cycle? 
Looking at the .razor generated code, I see that the elements and attributes added inside a cycle have a hard-coded number, like in any other place. How can all the elements added inside a cycle have the same sequence number? How the diff algorithm works in this case?

**Comment by guardrex** [comment]
Hello @arivoir ... We just added that guidance a little over a week ago :point_right: https://docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.0#sequence-numbers-relate-to-code-line-numbers-and-not-execution-order.

That came from a gist in Steve's repo ... and you can probably discuss it with the devs there at the bottom. See: https://gist.github.com/SteveSandersonMS/ec232992c2446ab9a0059dd0fbc5d0c3

I'll close here, but we can re-open if you think something is missing. Let me know.

**Comment by arivoir** [comment]
@guardrex I took a second look at the docs and I think I understood more, but I still have a doubt. The elements added in a cycle will have all the same sequence number, because it is tied to the code line concept. But I'd like to implement virtualization and I'd need more granularity to be able specify which element inside the cycle are related to the previous tree. I understand that Blazor doesn't give this level of granularity and that the diff will have to figure out how to update the dom, considering all the elements equally. Am I right?

**Comment by guardrex** [comment]
I think that's correct based on the discussion, but I can't provide a firm answer ... ask the engineers that on the Gist. Steve and those community members are :ear: for discussion comments there.

If you/they work out that the doc should have additional comments, then ping me back over here with the text that you work out with them (or just let me know to re-open the issue so that you can put a PR in over here on the docs), and we'll get the content updated here.
