### ISSUE TITLE
File Upload is banned 

### ISSUE THREAD

**Issue by gnohgnol** [aspnet/AspNetCore.Docs#12553]
[EDIT by @guardrex to drop the boilerplate text from the issue template. [File Uploads Topic](https://docs.microsoft.com/aspnet/core/mvc/models/file-uploads)]

I use IFormFile in a regular Form to upload a file. My form is written using ASP.NET Core MVC using a simple html form together with IFormFile.  After I select a file and upload it, the runtime tells me that I cannot upload a file in a development configuration. And I cannot change the configuration. What can I do to upload a file ?

**Comment by guardrex** [comment]
@gnohgnol Note that we have a *large* update to the file uploads topic. You could compare what you have to what's on the PR. https://github.com/aspnet/AspNetCore.Docs/pull/12344

> I cannot upload a file in a development configuration

Can you put up a small repro app on GH so that I can see how you have everything set up?

Also, what's the exact error message? Provide the whole stack trace.
