### ISSUE TITLE
LoggerMessage does not log container_name and pod_id into stackdriver

### ISSUE THREAD

**Issue by shengxue** [aspnet/AspNetCore.Docs#12566]
LoggerMessage does not log container_name and pod_id into Google Cloud Platform stackdriver, while LoggerExtensions does.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 48e02614-5cdd-0c85-3193-75a2325326b4
* Version Independent ID: fca176e2-c56e-0f17-de1b-e60912091e4b
* Content: [High-performance logging with LoggerMessage in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/loggermessage?view=aspnetcore-2.1)
* Content Source: [aspnetcore/fundamentals/logging/loggermessage.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/logging/loggermessage.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @shengxue ... We won't be able to address this here on the docs repo. Personally, I'm only aware of Google's client library. I've never used it.

Ask on a support forum, such as Stack Overflow, or a support chat, such as Slack or Gitter, or inquire on the Google side ... on their GH repo. Without knowing more, it sounds to me that you're using the Google client library, thus the issue is more on their side than Microsoft's side. However, I'm just *wildly guessing* without more context.

If there is a problem (a bug) in the ASP.NET Core framework that you think you've discovered, of course, the engineers would like to hear about it over in the engineering repo. https://github.com/aspnet/AspNetCore/issues
