### ISSUE TITLE
How to write test to confirm CORS config?

### ISSUE THREAD

**Issue by zsmorris** [aspnet/AspNetCore.Docs#12597]
Step 5, "Test with the client app."  is helpful, but for production application, one should not rely on manual testing.  If would be great if this doc could include steps to write an automated integration test to verify the configured CORS behavior.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59bca5db-1196-2a8b-a0d8-4e89b2382288
* Version Independent ID: d3f332c4-4c60-039e-0e1e-bc6b11831f87
* Content: [Enable Cross-Origin Requests (CORS) in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/cors?view=aspnetcore-2.2)
* Content Source: [aspnetcore/security/cors.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/cors.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Probably would be best for the [integration testing topic](https://docs.microsoft.com/aspnet/core/test/integration-tests). However, I doubt that the topic can show tests for every framework scenario ... there are just too many aspects to cover imo 🏃😅. It would be nice tho if that topic at least showed an example of assigning headers to a request because that's all it would need in a general way to resolve this issue.

**Comment by Rick-Anderson** [comment]
Hello! Thanks for contacting us. This sounds like a general question about using ASP.NET Core. While we try to look at and respond to all issues, for questions like this we recommend posting to a community support group like [Stack Overflow](https://stackoverflow.com) with the `asp.net-core` tag.
