### ISSUE TITLE
Is [Parameter] still necessary?

### ISSUE THREAD

**Issue by jasonshave** [aspnet/AspNetCore.Docs#12610]
Looks like the latest Blazor templates don't use `[Parameter]`. Is this still necessary, and if so, can we elaborate on when and why?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c07e57dc-526f-9479-4695-de7d8f06eb9a
* Version Independent ID: 8226ed72-69b2-3c93-a931-218bd11cf9c8
* Content: [Get started with Blazor](https://docs.microsoft.com/en-us/aspnet/core/blazor/get-started?view=aspnetcore-3.0&tabs=visual-studio)
* Content Source: [aspnetcore/blazor/get-started.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/get-started.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
They don't use them because they don't need them.

The Components topic calls out the purpose:

https://docs.microsoft.com/aspnet/core/blazor/components?view=aspnetcore-3.0#component-parameters

I'll place a similar remark in the *Get Started* topic. I **_do_** want the reader to receive a quick word on it here because the *Build your first* experience based on adding a single component (i.e., no nesting of components) won't have info on this aspect.

Thanks for mentioning this.
