### ISSUE TITLE
Blazor client-side state management

### ISSUE THREAD

**Issue by SogoGolf** [aspnet/AspNetCore.Docs#12628]
i know app state management isn't strictly a (eg. Blazor) product feature, but would be nice to see something here regarding a very basic blazor client side web app with state management, setup/added. React for example has Redux, Mobx etc.. 

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce9457c7-13d4-1520-790c-a18187532ff4
* Version Independent ID: 43f87dbb-2f36-c91e-084c-c28d93da923f
* Content: [Blazor dependency injection](https://docs.microsoft.com/en-au/aspnet/core/blazor/dependency-injection?view=aspnetcore-3.0)
* Content Source: [aspnetcore/blazor/dependency-injection.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/dependency-injection.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @SogoGolf ... It's in-design in engineering (but on the backlog right now). You can track and participate in the engineering discussion here :point_right: https://github.com/aspnet/AspNetCore/issues/5467.

I suspect that we'll have a topic on it after they settle on and provide an implementation. We'll open a new issue for that when there's something good to document.

I'll mark this for triage: DR, do you want to document *anything* at this time? If not, let's close this and create a new issue later.

**Comment by SogoGolf** [comment]
sounds good thanks

**Comment by thangchung** [comment]
Please make it works

**Comment by guardrex** [comment]
Server-side will be covered by work on https://github.com/aspnet/AspNetCore.Docs/issues/13259.

I'll leave this open so that DR can remark on the client-side scenario and triage this issue.

**Comment by guardrex** [comment]
This was resolved as far as engineering wants to resolve it for Blazor WebAssembly apps on https://github.com/aspnet/AspNetCore.Docs/pull/13364 yielding the live topic [ASP.NET Core Blazor state management](https://docs.microsoft.com/aspnet/core/blazor/state-management).

There will likely be future enhancements on the engineering side. We'll open a new issue for anything new that engineering produces when they do the work. For now, what's described there is all that engineering wishes to address at this time for **both** hosting models.

If you want to provide feedback to engineering on this subject, do so on their repo :point_right: https://github.com/aspnet/AspNetCore/issues ... **BUT be sure to search open and closed issues first** because others have probably already posted feedback and it's better to add remarks to existing issues.
