### ISSUE TITLE
Document custom authentication scheme

### ISSUE THREAD

**Issue by elgunhuseynli** [aspnet/AspNetCore.Docs#12656]
It took me 2 days to find how we can implement our custom bearer authentication handler in asp.net core. I finally found this blog post teaches how to register custom auth handler for Basic, Digest and Bearer authentication.

https://joonasw.net/view/creating-auth-scheme-in-aspnet-core-2

And it is as simple as this:
```csharp
services.AddAuthentication("Basic")
    .AddScheme<MyAuthenticationOptions, MyAuthenticationHandler>("Basic", null);
```

**Comment by blowdart** [comment]
It is not as simple as the linked URL suggests, and we've ruled out ever shipping basic authentication because of its insecurity and scalability problems, so documentation showing how to implement it is equally a bad idea from a security point of view. 

Making a secure custom authentication scheme is, to be honest, not an every day occurrence. We'd hope that developers who feel this is what they want to do are comfortable reading the source code for the built in authentication pieces and work from there, rather than require a beginners documentation.
