### ISSUE TITLE
[Preview 6] Add Blazor auth documentation

### ISSUE THREAD

**Issue by SteveSandersonMS** [aspnet/AspNetCore.Docs#12704]
Original spec here: https://gist.github.com/SteveSandersonMS/60ca3a5f70a7f42fba14981add7e7f79

A few of the names changed along the way, but the preview 6 implementation is pretty close to this.

**Comment by SteveSandersonMS** [comment]
![image](https://user-images.githubusercontent.com/1101362/59255396-f0064000-8c29-11e9-8ab9-55074c08ec91.png)

![image](https://user-images.githubusercontent.com/1101362/59256591-2e046380-8c2c-11e9-8cfb-8dc50a0d253f.png)

**Comment by SteveSandersonMS** [comment]
OK, I've put a draft of this doc item here: https://gist.github.com/SteveSandersonMS/175a08dcdccb384a52ba760122cd2eda

@guardrex, is this enough for you to work with? Thanks for your help with this!

**Comment by guardrex** [comment]
@SteveSandersonMS Excellent.

@danroth27 @tdykstra Where do you want the content? This spans authn and authz, so how do you want it handled if it's headed into the *Security and Identity* node where authn/authz are normally split? Alternatively, do you prefer a new topic in the *Blazor* TOC?

**Comment by tdykstra** [comment]
>  a new topic in the Blazor TOC?

That would be my choice.

**Comment by guardrex** [comment]
Let's work out the details. I'll try to get this done by EOD on release day (but no promises on that ... let's say "within 48 hours" ... depends on how smoothly things go that day).

* **Title:** *Blazor security*
* **Physical path**: aspnetcore/blazor/security/index.md
* **URL**: `https://docs.microsoft.com/aspnet/core/security/`
* **TOC**: **Web apps** > **Blazor** > **Security**
* **UID**: blazor/security/index

This includes a "security" node and makes the topic the index because we'll almost certainly have additional Blazor security topics in the future.

Title/TOC could also mirror existing security topics with a title of *Blazor security and identity* and TOC of **Security and Identity**, but I recommend merely "security" for the node name either way.

Not sure if you prefer "overview" tho on the physical path/URL. Let me know on that.

Under this scheme, the content would be easy to shift in the future. For example, authn and authz could be split into new standalone topics if they ever get too heavy for one topic. The index (overview) content can then focus on generic/cross-cutting security (and identity) coverage.

**Comment by danroth27** [comment]
Can we cross link the Blazor security docs from the top level "Security and Identity" node? We don't want Blazor to be a separate island. It's part of ASP.NET Core.

**Comment by tdykstra** [comment]
Yes, we can duplicate the TOC nodes.

**Comment by guardrex** [comment]
I modified my **TOC** remark to track taking care of it. :point_up:
