### ISSUE TITLE
withAutomaticReconnect not at all clear

### ISSUE THREAD

**Issue by jiggyswift** [aspnet/AspNetCore.Docs#12726]
This document in the "Hosting models" section needs to be cleaned up and is not at all clear with regards to setting default for automatic reconnection.  The documentation includes this code:
 Blazor.start({
    configureSignalR: function (builder) {
      builder.configureLogging(2); // LogLevel.Information
    }
And this code to enable with automatic reconnection:
const connection = new signalR.HubConnectionBuilder()
    .withUrl("/chatHub")
    .withAutomaticReconnect()
    .build();

But it is not at all clear what we should be doing?  Without understanding more of the plumbing, I don't know how to link those two things together?  I have thought about this for 20 minutes but cannot figure out exactly what do to.  Is it possible to show a single script tag that simply shows how to enable automatic reconnections.  My confusion is:
a) Why does the example include .withUrl("/chatHub") when the server I understand defaults to listening on /blazor.
b) How do you link that second chunk of code back to blazor starting up?  Am I to assume that when "function (builder)" is called that the object passed in is that you can then call builder.withAutomaticReconnect ? 

I assume that is incorrect, but I simply don't understand what do to.  I think 100% of people with deep experience with SignalR will immediately understand this; and 0% of people coming to Blazor without previously using SignalR will understand what to do here.  Is it possible to provide a complete script block in this document?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 542f38c4-1502-f739-372a-80c86c377491
* Version Independent ID: 72c2a844-ffb2-4799-2c7a-a7a73d3b6833
* Content: [Blazor hosting models](https://docs.microsoft.com/en-au/aspnet/core/blazor/hosting-models?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/blazor/hosting-models.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/hosting-models.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @jiggyswift ... Two of the sections were accidentally placed in this topic. The coverage was really for SignalR, and SignalR docs received the coverage on the last preview release. Therefore, we just removed those two sections in this topic on https://github.com/aspnet/AspNetCore.Docs/pull/12717/files yesterday.

Yes, on (a) ... you are correct. "chatHub" applies to the SignalR examples in the SignalR docs ... not here ... it shows that because this section was in the wrong spot in the docs. On (b), it's handled by the framework. It's configured by default to automatically reconnect.

For more information, the SignalR docs apply. That doc set is over here (for 3.0 preview) :point_right: https://docs.microsoft.com/aspnet/core/signalr/introduction?view=aspnetcore-3.0 ... which hopefully will answer questions.

I'll mark your issue here for engineering to take a look to see if we should provide more information. One thing that we will be doing shortly is working on the SignalR cross-linking in the hosting area on https://github.com/aspnet/AspNetCore.Docs/issues/12445, so check that issue out to see the content links that I'll be working on there.

**Comment by guardrex** [comment]
The offending sections were removed on #12717. The current content was checked by engineering for the 3.0 release. I believe we're in good shape now. If you need to open a new issue, use the **This page** feedback button/form at the bottom of the topic.
