### ISSUE TITLE
Document why HSTS middleware is not suitable for APIs

### ISSUE THREAD

**Issue by mkArtakMSFT** [aspnet/AspNetCore.Docs#12749]
This issue came up from the conversation related to this issue: https://github.com/aspnet/AspNetCore/issues/8533

**Comment by blowdart** [comment]
@guardrex @Rick-Anderson could I get a paragraph added to https://docs.microsoft.com/en-us/aspnet/core/security/enforcing-ssl for 3.0? Something like the following, although worded as you know best.

**HSTS and API projects**

The default API projects do not include HSTS because HSTS is generally a browser only instruction, other callers, such as phone applications or desktop applications will not obey the instruction. Even within browsers a single authenticated call to an API over HTTP has risks on insecure networks. The secure approach is to configure API projects to only listen to and respond over HTTPS.

**Comment by guardrex** [comment]
@Rick-Anderson I'll be free this weekend (Sat) if you want me to do it.

**Comment by blowdart** [comment]
In fact it could be merged with the warning on that page somehow right at the top? We will probably create a short link to put into templates in a comment which points to this

**Comment by guardrex** [comment]
We can't include versioned content *inside of* a warning ... we'd need to duplicate the warning (one for >=3.0 and one for <3.0) ... but for sure ... we can do that.

**Comment by blowdart** [comment]
Its whatever you think gets the message across best really.

**Comment by guardrex** [comment]
I'll take it for now, and Rick can swap with me if he prefers to work it.
