### ISSUE TITLE
Add Azure SignalR Service to the SignalR publish-to-Azure page

### ISSUE THREAD

**Issue by bradygaster** [aspnet/AspNetCore.Docs#12744]
Adding @guardrex and @danroth27 to this request. Dan and I were discussing the ways we could round out the docs on the upcoming Blazor and VS updates around SignalR and the Azure SignalR Service (ASRS). The [Publish to Azure](https://docs.microsoft.com/en-us/aspnet/core/signalr/publish-to-azure-web-app?view=aspnetcore-2.2) article should be updated to include screen shots of the SignalR provisioning suggestion in Visual Studio. Potentially show the resultant screen-shot in the Azure portal, too, inclusive of the App Service and ASRS instance.

**Comment by bradygaster** [comment]
adding @vijayrkn to the discussion. @vijayrkn it'd be helpful to have some of the latest UI for this doc when they're available. I grabbed a few screen shots from existing testing manuals in case @guardrex can't replicate this (or improve upon these). 

Updated publish start: 
![image](https://user-images.githubusercontent.com/41929050/59083562-b7bed480-88ac-11e9-942b-e8157cdaaf63.png)

Updated provisioning:
![image](https://user-images.githubusercontent.com/41929050/59083580-ca390e00-88ac-11e9-83a4-1c1515e92084.png)

SignalR Service drop-down presence:
![image](https://user-images.githubusercontent.com/41929050/59083591-d4f3a300-88ac-11e9-953e-7dab90cfe1e1.png)

Select/create ASRS instance:
![image](https://user-images.githubusercontent.com/41929050/59083601-df15a180-88ac-11e9-9361-927e8986b99b.png)

**Comment by guardrex** [comment]
Let me verify the plan and ask a few ? ...

[Publish an ASP.NET Core SignalR app to an Azure Web App](https://docs.microsoft.com/aspnet/core/signalr/publish-to-azure-web-app?view=aspnetcore-2.2)

1. The plan is to update the single example shown in the topic for a Blazor app with screenshots provided above that will apply to an upcoming round of Azure Portal and VS updates. We're not **_adding_** a separate Blazor example (for two examples), correct?
1. There are some versioning issues to consider:
   * This is only SCD at this time because this is using 3.0, correct? Should this show FDD for 3.0? If so, should that be a follow-up issue for post-3.0 RTM given that there might be a slight delay on the Azure rollout of 3.0 at RTM and the fact that the guidance won't be useful between now and then unless this stays SCD during preview?
   * Since this is going to be a Blazor example, the whole topic must be versioned >=3.0. Is that correct? We won't have anything for 2.2 with a non-Blazor example?

**Comment by bradygaster** [comment]
Close - IMO, 

1: No, this would be just an update to this doc. That said, I **don't mind your idea of a new doc at all**. Whatever you do, do, I'd love to have copies of the publishing part in **this** doc. 
2: After reading this one, I agree with your #1, that a Blazor-specific doc would be in order, as there'd be too many differences. Once the Blazor fire is no longer... uh... _ablaze?_ - maybe we switch back and augment this doc, too. 

But yes, a Blazor-specific doc would be better since there are *enough* variances.

**Comment by guardrex** [comment]
I left out a phrase that would've helped. When I typed "adding a separate Blazor example (for two examples)" ... I should've added "**_in this topic_**."

We can have one topic (this one) if you want ... we just version the content. The older content (current bits with new VS and Azure UI screenshots) for <3.0 and then add the new content versioned for >=3.0.

For the two-topic concept: This topic remains 2.2 (with updated screenshots). For a new Blazor-only 3.0 topic ...

* Where do you want the physical file to reside (e.g., *aspnetcore/host-and-deploy/blazor*)? Where do you want this in the TOC (e.g., Blazor > Host and deploy > Azure SignalR Service)? @tdykstra
* Looks like we'll need a 3.0-RTM-rollout-to-Azure issue to convert the Blazor example from SCD over to an FDD, correct?

**Comment by tdykstra** [comment]
>Where do you want the physical file to reside (e.g., aspnetcore/host-and-deploy/blazor)?  Where do you want this in the TOC (e.g., Blazor > Host and deploy > Azure SignalR Service)? @tdykstra

LGTM

While you're at it, you could move the SignalR Publish to App Service node to the Hosting and scaling node.

**Comment by guardrex** [comment]
> While you're at it, you could move the SignalR Publish to App Service node to the Hosting and scaling node.

Sure thing.

@bradygaster Just need you (perhaps with @tdykstra) to make the final call ... this can go either way ...

* Put the Blazor example, text, and screenshots in as updates to the **existing** *Publish an ASP.NET Core SignalR app to an Azure Web App* topic versioned for >=3.0, while the current 2.2 content in the topic remains there versioned for <3.0 with updated screenshots and text for VS and portal.
* Go with the standalone Blazor version over in Blazor's Host and Deploy area (physical + TOC as planned above). In that case, the *Publish an ASP.NET Core SignalR app to an Azure Web App* topic gets updated screenshots/text and hangs there at 2.2 for now.

... and either way ... do I understand correctly that we'll need to sit on the PR for a bit until VS and Azure Portal updates land per the remarks on the issue?

Finally, I'll open up a follow-up issue to make the Blazor example an FDD after 3.0 rollout in Azure.

**Comment by danroth27** [comment]
@guardrex @bradygaster This doc is about publishing apps that SignalR to Azure generally, so I don't think we should cover Blazor here. We have separate Blazor host & deploy topics for that (which could reference this doc). I think we should keep this doc generic for SignalR.

**Comment by guardrex** [comment]
> Go with the standalone Blazor version over in Blazor's Host and Deploy area (physical + TOC as planned above). In that case, the Publish an ASP.NET Core SignalR app to an Azure Web App topic gets updated screenshots/text and hangs there at 2.2 for now.

Excellent ...

* I'll use the screenshots from the issue to get the ball rolling.
* Locations are:
  * Physical: `aspnetcore/host-and-deploy/blazor`
  * TOC: **Blazor** > **Host and deploy** > **Azure SignalR Service**
  * UID: `host-and-deploy/blazor/publish-to-azure-web-app`
* It will go in as a draft PR given that I presume we'll need to confirm screens are correct when VS and Azure Portal UIs are released.
* I'll also attempt to place the new screenshots (minus Blazor) into the SignalR TOC doc on the same PR. 
* I'll move the SignalR doc to the Hosting and scaling node.

btw @tdykstra I used "*Host and deploy*" while u were in Azure Land Docs because the guidance that we received from the localization cats was *not to use gerunds in titles and headings unless they're part of a technology name*. Do you want the same change that you made in the root TOC taken in the Blazor TOC on these updates? 

*Host and deploy* :point_right: *Hosting and deployment*

**Comment by tdykstra** [comment]
>Host and deploy 👉 Hosting and deployment

Yes, best to be consistent.

**Comment by guardrex** [comment]
I just discovered working thru these updates ...

> I think we should keep this doc generic for SignalR.

We don't even need a Blazor version if this avoids screenshots showing naming (i.e., "Blazor").

Let's try it on the upcoming PR and see how it goes.
