### ISSUE TITLE
Build error with HeadingComponent.razor code under Components folder

### ISSUE THREAD

**Issue by katiep23** [aspnet/AspNetCore.Docs#12812]
HeadingComponent.razor generates "CS0428	Cannot convert method group 'UpdateHeading' to non-delegate type 'object'. Did you intend to invoke the method?" error when created under Components folder, but not when moved to Pages folder.

Have added @using BlazorTest.Components to _Imports.razor file.

Any other steps missing not in the documentation?

Check the .NET target framework(s) being used, and include the version number(s).

- [ x] .NET Core
- [ ] .NET Framework
- [ ] .NET Standard

**Comment by guardrex** [comment]
Hello @katiep23 ... *Roasted Rat Burgers!* 🐀🍔 lol ... We just (*tried*) to address that with https://github.com/aspnet/AspNetCore.Docs/pull/12730.

Can you shoot a repro project up to GH so that I can take a look at it? What you did *should have worked.* If I repro it here, we can open with the engineers for a look.

btw -- just for future reference -- It helps us work doc issues if you use the **This Page** feedback button to open issues. It's no biggie ... but it tags the issue with metadata for us. Just mentioning it for future reference.

**Comment by katiep23** [comment]
Thanks for the feedback!  I'm pretty new to all this, but definitely will in future. I've attached the repo.

[BlazorTest.zip](https://github.com/aspnet/AspNetCore.Docs/files/3278893/BlazorTest.zip)

**Comment by guardrex** [comment]
You'd need to put the project up in a GitHub repo for me.

**Comment by katiep23** [comment]
https://github.com/katiep23/BlazorTest

**Comment by guardrex** [comment]
Thanks @katiep23 ... we're in the midst of a lot of work today. I'm 🏃🏃😅 for today ... possibly tomorrow, too. I'll get back to you ASAP.

**Comment by guardrex** [comment]
@katiep23 That looks correct. Try one more time with a new Preview 6 template and SDK, which was just released two days ago. If that persists, search for an open issue in engineering. If you don't see anyone else reporting the same issue, open a new issue with them ...

https://github.com/aspnet/AspNetCore/issues

... if you open a new issue, do the same thing ... put up a Pre6 repro project in GH for them to see.

**Comment by katiep23** [comment]
I actually found the difference.  The templates on the original site had "<button class="btn btn-primary" onclick="@IncrementCount">."

The updates use @onclick, which eliminates the error.

**Comment by guardrex** [comment]
Yes, indeed. We're still getting those little bits ironed out. I even have a PR in review now to continue that process ... https://github.com/aspnet/AspNetCore.Docs/pull/12893.
