### ISSUE TITLE
identity impersonation

### ISSUE THREAD

**Issue by poonamshingrut** [aspnet/AspNetCore.Docs#12870]
I've implemented Timed background tasks which is working fine. Can I use identity impersonation here?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3460b0d-9c60-3a06-ac63-18cf990e53c3
* Version Independent ID: b2dece1f-15b8-03af-6d52-7cc070432b4b
* Content: [Background tasks with hosted services in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/hosted-services?view=aspnetcore-2.1&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/fundamentals/host/hosted-services.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/host/hosted-services.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @poonamshingrut ... *Interesting concept!* Normally, we'd suggest that you consult with devs on a support forum or chat, but that's a really interesting scenario. I think the engineers would like to remark on this. Open an issue on the engineering repo ...

https://github.com/aspnet/AspNetCore/issues

Make sure that you provide more detail tho ... describe your full scenario to them.

Please add a "cc: @guardrex" to that so that I can see what they say.
