### ISSUE TITLE
Incorrect generated code

### ISSUE THREAD

**Issue by mrpmorris** [aspnet/AspNetCore.Docs#12963]
The `Data binding` shows the following code

&lt;input value="@CurrentValue" 
    @onchange="@((UIChangeEventArgs __e) =&gt; CurrentValue = __e.Value)" /&gt;

1: Rather than saying this is the "equivalent" code, say it is the auto-generated code. That way the reader will understand why a double underscore prefix is being used, against coding guidelines.
2: The identifier has been changed from __e to __value in the latest preview.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be4c4d0c-149c-bde1-c7fa-f082916390ca
* Version Independent ID: 9d945996-ad02-bd4b-58ea-c465cc5cc74c
* Content: [Create and use Razor components](https://docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/blazor/components.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/components.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
> Using @bind with a CurrentValue property (\<input @bind="CurrentValue" />) is essentially equivalent to the following:

Hello @mrpmorris ...

* That's not the generated (Razor) code.
* I think the author's intent was to draw the code out into something *sort of* equivalent that one could write and run that shows what `@bind` is doing ... sort of. :smile:

  * `@bind` produces:

    ```
    builder.AddAttribute(6, "onchange", 
        Microsoft.AspNetCore.Components.EventCallback.Factory.CreateBinder(this, 
        __value => CurrentValue = __value, CurrentValue));
    ```

  * The *almost* equivalent example code produces:

    ```
    builder.AddAttribute(10, "onchange",
        Microsoft.AspNetCore.Components.EventCallback.Factory.Create<Microsoft.AspNetCore.Components.UIChangeEventArgs>(this, 
        (UIChangeEventArgs __e) => CurrentValue = __e.Value));
    ```

* Since the Razor code will use whatever is provided there for the var, `__e` could be anything. AFAIK, the double-underscore is a pattern to avoid name collision. Given that the point is the structure/syntax and we don't want it to be confusing as you say, we could show it with just `e` ...

  ```
  <input value="@CurrentValue" 
      @onchange="@((UIChangeEventArgs e) => CurrentValue = e.Value)" />
  ```

I'll mark this for engineering to take a look at and see what changes they would like to make.

**Comment by mrpmorris** [comment]
Names that are unlikely to clash are only required in generated code that is mixed with user code. If this is supposed to be user-written code then the example should conform to .NET coding practices for user-written code, and use `e` :)

**Comment by VR-Architect** [comment]
I found this part very confusing for non JS coder. What do I care what the equivalent is? Put that in a side box with note saying "For JS developers this is like doing this ...."

**Comment by guardrex** [comment]
Should be resolved by https://github.com/aspnet/AspNetCore.Docs/pull/14868. Open a new issue using the **This Page** feedback button/form at the bottom of the topic to send additional feedback.
