### ISSUE TITLE
 OnModelCreating symbolic

### ISSUE THREAD

**Issue by Goldenstarc** [aspnet/AspNetCore.Docs#13059]
fix OnModelCreating link on this page :

https://docs.microsoft.com/en-us/aspnet/core/security/authentication/customize-identity-model?view=aspnetcore-2.2#default-model-configuration

**Comment by guardrex** [comment]
Thanks @Goldenstarc ... I'll get quick patch in on that.

**Comment by Goldenstarc** [comment]
> Thanks @Goldenstarc ... I'll get quick patch in on that.

thanks.
also check other links. like DbContext one

**Comment by guardrex** [comment]
There's a problem with link resolution generally, so I'm going to ask one of the :cat2: to take a look on the PR. I think we'll need to open an internal issue for investigation because our API cross-references are correct. For now, I'll fix these broken links by using relative links. I'm working on the PR now.

**Comment by guardrex** [comment]
btw @Goldenstarc If you use the **This Page** feedback button at the bottom of the topic, it will tag the metadata that we need to work the issue (i.e., no need to provide the link to the topic and the author of the topic will get a direct ping when the issue opens). No big deal ... I'm just mentioning it for future reference. Thanks again for opening this issue.
