### ISSUE TITLE
Implement Health check

### ISSUE THREAD

**Issue by nandhu** [aspnet/AspNetCore.Docs#13081]
Hi,
How can I implement Health check for generic host applications?
Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5f1eeee-d500-82bf-0d0a-b4e0d5d5c175
* Version Independent ID: 2373a3df-6ea3-50c7-d63d-61c51d572511
* Content: [.NET Generic Host](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/generic-host?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/fundamentals/host/generic-host.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/host/generic-host.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hi ... We won't have additional info here until I get to the topic for 3.0 updates. 

Engineering recommends sticking with the Web Host until 3.0 RTM. Due to engineering churn during preview we're virtually forced to wait until the Release Candidate before we make the doc updates. Some docs have been updated for the Generic Host, and a PR is under construction now. 

If you can't squeeze enough info out of the prerelease coverage that we have today, talk to devs on Stack Overflow or a support chat, such as Slack or Gitter.
