### ISSUE TITLE
Order doesn't seem to apply to ExceptionFilter

### ISSUE THREAD

**Issue by jstafford5380** [aspnet/AspNetCore.Docs#13239]
Not sure if this is a particularity or a bug, but when I specify the order of the exception filters, they do not run in that order. They don't seem to be affected if I change their physical order (the order in which they were added to the filter collection) either.

``` csharp
services.AddMvc(options =>
{
	options.Filters.AddService(typeof(PetmApplicationExceptionFilter), 2);
	options.Filters.AddService(typeof(ConfigurationExceptionFilter), 1);
})
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a70a955f-dd5a-c46b-dfe8-21521e619320
* Version Independent ID: ebb299e0-6c1c-7077-689d-ac711352e418
* Content: [Filters in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/filters?view=aspnetcore-2.2)
* Content Source: [aspnetcore/mvc/controllers/filters.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/controllers/filters.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
The order they are registered has no impact. Lower numbers run first.

**Comment by jstafford5380** [comment]
Thanks, did you read the rest of it? Neither are affecting the order in which they are ran. I'm asking on here in case this is somehow misdocumented and doesn't work for exception filters. Examples seem to focus on other filters.

**Comment by dougbu** [comment]
The `Order` value _does_ apply to `ExceptionFilter`s that implement `IOrderedFilter`. Unless we have a repro of a case where that isn't the case, this issue and #13279 should be closed.

In the original description, the `1` and `2` values passed to `AddService(...)` provide the `Order` values. The position in the unsorted collection doesn't matter unless the metadata's `Order` and `Scope` match. In all cases `FilterCollection.Add(...)` or `FilterCollection.AddService(...)`, `Order` values elsewhere e.g. a default when the filter type is instantiated are not relevant because the filter isn't created until after `IFilterMetadata` instances (the `TypeFilterAttribute` or `ServiceFilterAttribute` here) are sorted.

**Comment by aldrashan** [comment]
Same issue here. Two ExceptionFilters. Highest order always runs first.

```
services.AddControllers(o =>
{
    o.Filters.Add<OperationCancelledExceptionFilter>(1); 
    o.Filters.Add<LogUnhandledExceptionFilter>(2);
})
```

**Comment by dementeddevil** [comment]
With exception filters, since the filter will execute after the action has executed it should execute from high to low. That might be contrary to the docs but makes sense if you think of them as any other filter.

That being said, I have two pieces of code that update the list of action filters (one in a library and the other in the startup code) and the filter added in my startup code implements IOrderedFilter but the order is ignored. I only get the desired behaviour if I move the registration code so it occurs before the code run in my library.

For example (this works)
````
builder.Services
    .AddControllers()
    .AddMvcOptions(options => options.Filters.Add<MyOrderedFilter>());

builder.AddMyLibraryServices();  // inside this extension method it also adds filters
````

For example (this does not work)
````
builder.AddMyLibraryServices();  // inside this extension method it also adds filters

builder.Services
    .AddControllers()
    .AddMvcOptions(options => options.Filters.Add<MyOrderedFilter>());
````
