### ISSUE TITLE
Handling Large File Uploads and Timeouts

### ISSUE THREAD

**Issue by kieronlanning** [aspnet/AspNetCore.Docs#13243]
How do we handle a large upload from client(s), where the ASP.NET Core request is timing out.

Everything I've seen says it's not possible to change the maximum request timeout?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a5cfa38-0e6c-4346-dafc-84ea5c513fcf
* Version Independent ID: c6787f0f-3e9a-6efb-0e6e-5ccb957d3f4a
* Content: [File uploads in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/models/file-uploads?view=aspnetcore-2.2#uploading-large-files-with-streaming)
* Content Source: [aspnetcore/mvc/models/file-uploads.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/models/file-uploads.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by ardalis** [comment]
You can see some sample code here: https://github.com/ardalis/DevBetterWeb/commit/25f9169a061d9ebc19553f6ee21587c602b6cc4f

Specifically, you want these bits:
```
.UseKestrel(options =>
                {
                    options.Limits.MaxRequestBodySize = Constants.MAX_UPLOAD_FILE_SIZE; //500MB
                });
```
and on your controller action:
```
[RequestSizeLimit(Constants.MAX_UPLOAD_FILE_SIZE)]
        public async Task<IActionResult> OnPost(List<IFormFile> files)
```

Does that help? It worked for me.

**Comment by kieronlanning** [comment]
@ardalis We've got those, the problem is we have a 250Mb file which is fine when the user's are on a quick connection...when they're not, we get timeouts all over the show so the client can't continue.

**Comment by ardalis** [comment]
Are you hosting on IIS? Have you set the timeout there? See https://medium.com/aspnetcore/increase-the-timeout-of-asp-net-core-application-9a7b4f6deebf for example.

**Comment by kieronlanning** [comment]
Alas no, it's self-hosted - locally - and running as a docker container when it's live.

It's a real problem I've not found a solution too yet.

**Comment by ardalis** [comment]
I'd file an issue in the aspnet repo, then, where the product team will see it, in addition to here (you can reference this one).

**Comment by kieronlanning** [comment]
Good shout, thanks @ardalis.

**Comment by guardrex** [comment]
We have the limits covered AFAIK on the PR for the File Uploads topic ...

https://github.com/aspnet/AspNetCore.Docs/pull/12344

Engineering is supposed to look at that PR in a bit and will let me/us know where it goes off the rails.

There was one limit that I don't think has been fully resolved, but I don't think it applies to your scenario. I'll just link it here for you to :eyes: and confirm that it doesn't apply. I don't recall the details or workarounds for it ...

https://github.com/aspnet/AspNetCore/issues/2711

Since we have an open PR with **_massive updates_** for this topic, I'm going to close this issue. If you look at the content on the PR and have feedback, provide it on the PR. I'll take a look over there. At the very least, placing the feedback on the PR will surface it to engineering when they review the PR. I don't have an ETA on that review tho ... it could be weeks, months, or ..... well ..... given that 3.0 is breathing down our necks .... it could be when the 🐄 come :house: ... i.e., *lateer this year*. :smile:

**Comment by kieronlanning** [comment]
Thanks for the update @guardrex. It looks like we may need to go with another option in the mean time.
