### ISSUE TITLE
Need documentation on `AdditionalAttributes` property and operation

### ISSUE THREAD

**Issue by conficient** [aspnet/AspNetCore.Docs#13258]
The `AdditionalAttributes` property has appeared in several controls along with the `AddMultipleAttributes` method on `RenderTreeBuilder`, and is a useful feature for passing attributes to a Component that are not directly handled but are required in the render process. I looked for documentation on this (e.g. how can we write these attributes in our own control using Razor syntax, rather than calling `AddMultipleAttributes` ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be4c4d0c-149c-bde1-c7fa-f082916390ca
* Version Independent ID: 9d945996-ad02-bd4b-58ea-c465cc5cc74c
* Content: [Create and use ASP.NET Core Razor components](https://docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/blazor/components.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/components.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
This has been covered since the issue was opened ...

https://docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.0#attribute-splatting-and-arbitrary-parameters

**Comment by joshball** [comment]
Hi @guardrex,

The [documentation here](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/?view=aspnetcore-3.1#attribute-splatting-and-arbitrary-parameters) is sufficient. However, when I [searched for `AdditionalAttributes`](https://docs.microsoft.com/en-us/search/?scope=ASP.NET%20Core&view=aspnetcore-3.1&terms=AdditionalAttributes) I cannot find the documentation. 

![image](https://user-images.githubusercontent.com/127526/86816866-58546a80-c052-11ea-9211-9acc097b2f06.png)
[Searching for "attributes"](https://docs.microsoft.com/en-us/search/?scope=ASP.NET%20Core&view=aspnetcore-3.1&terms=attributes) does find it, about 20 down, but that is a pretty generic term, and I would **not** expect it to bubble up.

I realize that `AdditionalAttributes` is an arbitrary variable name, and would not expect it to be searchable in general, but since it is used internally in the source and examples and other documentation, it would be helpful. 

So, any chance we could index  `AdditionalAttributes` (and maybe the singular, `AdditionalAttribute`, just in case) to point to the above link?

Also, is there a correct way for me to _request_ an index term and link? I didn't see anything searching issues, but I am sure I am just missing the correct term to search for ;-)

Thanks

**Comment by guardrex** [comment]
I believe the filters are **_title based_**. We don't have search term indexing as far as I know.

Your best bet for these types of searches isn't to use that search system but to go with a good 'ole Google search. Search for it this way in Google ...

```
site:docs.microsoft.com/en-us/aspnet/core "AdditionalAttributes"
```

**Comment by guardrex** [comment]
Also ... btw ... it's best not to comment on closed issues and PRs. Feel free to open a new issue using the **This Page** feedback button+form at the bottom of a topic.

<img width="404" alt="Capture" src="https://user-images.githubusercontent.com/1622880/81926733-0b02d200-95a8-11ea-8683-8dadc5483fb1.PNG">

**Comment by joshball** [comment]
I will send feedback. Thanks

**Comment by guardrex** [comment]
I mean that just opens the issue for us, so it's the same answer. If you want to open feedback about the search feature itself, open an issue here ...

https://github.com/MicrosoftDocs/feedback/issues
