### ISSUE TITLE
Problem with hosting in a remote Ubuntu server

### ISSUE THREAD

**Issue by shunjid** [aspnet/AspNetCore.Docs#13275]
I have a Ubuntu Server, which I am connecting remotely with this command (Let's say, the IP address is XX.YY.ZZ

$ ssh root@XX.YY.ZZ -p 22

I have installed dotnet core runtime and dotnet core sdk on that machine remotely from my local computer.

Then, I pulled my project (MVC) in a folder from GitHub. And run this command:

$ dotnet publish --configuration Release

Then, I have changed directory to, bin/Release/projectName/publish folder and run the projectName.dll with:

$ dotnet projectName.dll

What it shows is, port is listening to http://localhost:5000. Now, I am trying to enter into the server and my project, typing:

http://XX.YY.ZZ:5000

But it says, This site can’t be reached. Am I missing something important during the deployment process? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dcdd2c35-bf2b-2673-d150-303a8aaa54d2
* Version Independent ID: 815fe034-c9fc-aee3-a8b5-f2e860b30302
* Content: [Host ASP.NET Core on Linux with Nginx](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/linux-nginx?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/host-and-deploy/linux-nginx.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/host-and-deploy/linux-nginx.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @shunjid ... Unfortunately, our experts in this area are actually on the engineering team and not the docs team, per se. We do work with the tech on doc updates, but we rely heavily on their input, since they work with non-MS server technology more regularly than we do. Your best bet on this is to ask on a support forum, such as Stack Overflow, or a support chat, such as Slack or Gitter. Chat can provide answers *very fast* on a question like this, and here are the links for those two ...

* [ASP.NET Core Slack Team](http://tattoocoder.com/aspnet-slack-sign-up/)
* [ASP.NET Gitter](https://gitter.im/aspnet/Home)
