### ISSUE TITLE
misleading info on logging in ConfigureServices()

### ISSUE THREAD

**Issue by WellspringCS** [aspnet/AspNetCore.Docs#13277]
There's a whole section on how to add `ILogger` to Startup.cs `ConfigureServices`, but that's not possible with the recommended go-forward approach in Program.cs of using `IHostBuilder`. Maybe address that here in the docs? I lost some time going down that dead-end.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7184a308-a254-9350-a5cd-5bced1f369ae
* Version Independent ID: 726e3bf1-f367-d733-8933-bccc04da0e16
* Content: [Logging in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-3.0&tabs=aspnetcore2x#feedback)
* Content Source: [aspnetcore/fundamentals/logging/index.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/logging/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by guardrex** [comment]
Hello @WellspringCS ... We're just a little bit early for it. The Generic Host doesn't make its full debut until 3.0 and thus isn't recommended at this time by engineering for production apps. WRT docs for preview scenarios: Due to engineering churn right up to the RC, we can usually only document the current release. The updates will be covered by an issue that will be opened later by the topic author.
