### ISSUE TITLE
Surface additional instruction for downloading samples

### ISSUE THREAD

**Issue by edikaufmann** [aspnet/AspNetCore.Docs#13414]
As a retired (mid seventies !) 'hobby' developer I'm struggling to follow/use the instructions given in
the document: "Introduction to ASP.NET Core" it says:
....
How to download a sample

Many of the articles and tutorials include links to sample code.
1. Download the ASP.NET repository zip file.
2. Unzip the Docs-master.zip file.
3. Use the URL in the sample link to help you navigate to the sample directory.
Preprocessor directives in sample code
....

HOW do I now use "AspNetCore.Docs-master" to simply download e.g. the "ef-mvc" sample ?
OR "view" the final "ef-mvc" e.g. in VS2019 ?
(as the sample suggests in every chapter ["Download or view the completed application."])

Of course I downloaded "AspNetCore.Docs-master" BUT I'm obviously to old/dumb to understand.
I must be the only one struggling with this approach .... 

Therefore thanks for your time to help me out or, at least, give me the right kick to start ..!

PS: yes I have gone through the course "ef-mvc" to build it step by step, successfully!
thanks, ek

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ad06677-5842-c1aa-153f-7993a9660dfa
* Version Independent ID: 8daf79df-eac4-358b-e6f0-6def45bd54da
* Content: [Tutorial: Get started with EF Core in an ASP.NET MVC web app](https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/intro?view=aspnetcore-2.2)
* Content Source: [aspnetcore/data/ef-mvc/intro.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/data/ef-mvc/intro.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **tdykstra**

**Comment by guardrex** [comment]
Hello @edikaufmann ...

Looking at the landing page of the GitHub repository, download the ZIP archive of the whole repo ...

<img width="399" alt="Capture" src="https://user-images.githubusercontent.com/1622880/61591310-0c7f8b80-ab8b-11e9-90f6-6e6d5eead5b5.PNG">

Decompress it and navigate through the folders to the same location that is indicated by the URL of the sample. For this sample, dig down through the folders to ...

```
AspNetCore.Docs/aspnetcore/data/ef-mvc/intro/samples/cu-final/
```

<img width="585" alt="Capture2" src="https://user-images.githubusercontent.com/1622880/61591327-536d8100-ab8b-11e9-9967-32fd8147fd05.PNG">

The docs engineers were planning a way to download just a single sample a while back for all of the Microsoft repositories, not just ours. Not sure if that plan was dropped or if they still plan to do it.

For now, downloading the entire repo is required. After doing so, you have all of the samples. Just make sure that you pull down a new repo every so often because we're regularly updating sample apps, especially around the time of a framework release.

If you wonder about a given sample's current version and to track the work on sample updates, we have a tracking issue at https://github.com/aspnet/AspNetCore.Docs/issues/5495.

**Comment by edikaufmann** [comment]
Hi Luke,
thanks a lot for taking the time. 
I have attached a screenshot like yours (gitshot.png). As you see I DO NOT have the 'Clone or Download' button - as I mentioned in my first msg (#13403).

 I think if I would see the ZIP button - problem solved! (I have a history button instead - see attachement)

So again, what I'm doing wrong NOT to have that button!?


![Gitshot](https://user-images.githubusercontent.com/51043011/61591953-f1ce0680-abcc-11e9-8c3f-69cc8aa07fe9.PNG)

**Comment by guardrex** [comment]
Back out ... you don't get the button within the repo, only at the top level of the repo. Click on "AspNetCore.Docs" link at the top-left of your screenshot.

**Comment by guardrex** [comment]
I'm going to make an instruction change there to surface that.

**Comment by guardrex** [comment]
Nevermind ... it's already done. The download instruction links to the download archive directly. That's best.

**Comment by guardrex** [comment]
Good news @edikaufmann ... *Yes! They're working on it.*

See :point_right: https://github.com/MicrosoftDocs/feedback/issues/982

**Comment by edikaufmann** [comment]
I'm obviously getting older than I thought - i.e. I'm now totally confused!

I downloaded AspNetCore.Docs-Master before; did it again; I find aspnetcore/date/ef-mvc - no problem!

How do I now VIEW (run) this ef-mvc ? in VS2019 ?

I do not see any .sln file nor any C# code...….

I apologize for my ignorance but definitely need a kick start on this - perhaps I don't see the forest for trees!?
Thanks again for your time, ed

**Comment by guardrex** [comment]
No worries. We hear these questions regularly. We can't document too much on these aspects because we just focus on the programming bits.

Use **Open a project or solution** when VS first opens. Select the project file (\*.csproj file) in the root directory of the project.

VS will create the solution file for you and ask you where to save it when you close the project.

**Comment by edikaufmann** [comment]
well, well … thanks a million! In the end it's always clear and obvious!

for me a hint like - would had helped!?
3. Use the URL in the sample link to help you navigate to the sample directory; **find the .csproj; open it in VS.**

Need now to figure out how to handle the DB
Anyway I appreciate your help, THANKS!
ed
