### ISSUE TITLE
Rename RenderFragment to Template

### ISSUE THREAD

**Issue by SNathani** [aspnet/AspNetCore.Docs#13432]
Why not we use Template word to RenderFragment to make it self explanatory and less characters?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be4c4d0c-149c-bde1-c7fa-f082916390ca
* Version Independent ID: 9d945996-ad02-bd4b-58ea-c465cc5cc74c
* Content: [Create and use ASP.NET Core Razor components](https://docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.0#templated-components)
* Content Source: [aspnetcore/blazor/components.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/components.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @SNathani ... I think it's because "template" implies some degree of pre-formatting. These "render fragments" don't need to be pre-formated in any particular way. Their content can be completely dynamically generated. They truly are what the naming implies: a fragment of rendered content. The engineers are super crazy busy 🏃😅, so I can't ping them to ask about this. We'll have to assume that they named the delegate well.
