### ISSUE TITLE
Needs more real world information and examples

### ISSUE THREAD

**Issue by boaterdan** [aspnet/AspNetCore.Docs#13451]
While this article was a treasure for getting me going, it turns out it is so superficial that it doesn't have a lot of value.  

I'm creating a Razor Pages app for learning it.  I've got tons of unit tests of the PageModel derivatives including mocking the database and testing all the actions.  This gives me pretty high confidence the page will behave as expected.

But integration tests by definition go beyond one system and test the interaction between them.  One of the things that seems an glaringly obvious next step after the test described here that confirms a secured page redirects to the login would be to actually do the login and confirm access is then granted.  I mean really, how can we NOT test that?  I also want to test that pages I've restricted to a certain role can be accessed after logging in with that role but not anonymously and not after logging in with user that doesn't have the role.

But it turns out that after several days of making it work I had to give up because for some reason authentication fails using the InMemory database.  As soon as I switched to the real database the tests started working as expected.  There is also the problem of multiple test classes trying to spin up data, or tests colliding with each other as they make changes to the data.  Addressing these problems using information from blogs and other docs has led me pretty far away from the starting point of this article.

It's left me wondering whether this article has intentionally addressed only the most basic superficial aspects of integration testing because anything else is nearly impossible.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77889d43-fedb-f8b4-8fea-379ec946555c
* Version Independent ID: f499b131-8b14-7e10-1728-543fdd5a5656
* Content: [Integration tests in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/test/integration-tests.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/test/integration-tests.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-test**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @boaterdan ... Thank you for this valuable feedback.

> whether this article has intentionally addressed only the most basic superficial aspects of integration testing

*YES!* That's exactly right. This is only meant to be a basic, introductory topic. It contains enough basic info to get started. It doesn't get into advanced scenarios for integration testing (e.g., auth). There are already a couple of open issues for these aspects on the [Integration Testing project](https://github.com/aspnet/AspNetCore.Docs/projects/31) ...

* How to create authenticated request? #6882
* Create sample for Integration testing with user claims. #3833

I'll mark this for the product unit. The "PU" has taken over all work and issue triage for the integration testing topic. We (the docs team) will work anything that they assign tho. They'll take care of these issues at some point when they get some time.

**Comment by boaterdan** [comment]
Thanks for the reply.  For what it's worth, I would consider at least basic authentication as the very first thing that screams for integration testing.  I'll also throw in my opinion that I want to test without mocking away key components of the process.  While researching I've seen solutions to fake the authentication with things like adding a Middleware handler, for example, but it's the authentication process itself that I want to test, so I want to leave things as intact as possible.

I've been able to get something working, but there is still one hurdle after the other, even after I figured out using the physical database and not in-memory made everything start working.

I'm beginning to think that in the end I'll probably end up with a combination, with the basic authentication process being tested the way I am against a physical database and the authorization testing being done with some custom claims provider or Middleware to get around the problems of using the same physical database for everything.

**Comment by InDieTasten** [comment]
> anything else is nearly impossible

I've done a little bit of integration testing in the past, including full authentication, but not using the default asp.net core identity as a backing store. It's been working for me, so either I've managed to do something nearly impossible, or things have changed. I can fully imagine how the in-memory vs SQL server database might have broken in recent updates as well.

This definitely needs to be addressed, and I will try out integration testing in my spare time with 3.0 again and let you know of my results. If I can succeed, I can link a repo with examples for whoever wants to flesh out the documentation part of it.

Other than authentication, what other obvious next portions of an application are most common to be integration-tested? Apart from auth, I think there really isn't that much missing. The next thing for me would be testing actual page logic, which is of course very centered around business requirements. It will be difficult to create documentation other than basic Html-Response querying for certain tags and content. Anything beyond, and I would consider it E2E testing.

On another note regarding auth, nowadays many applications allow or are exclusive to third-party signup. Live ID, Twitter and so on. At that point, you must really mock, because you can't reasonably simulate real user flow, and doing so would probably break a ton of ToS, so the other solutions are oftentimes the best you can do.

**Comment by InDieTasten** [comment]
@boaterdan Hey there! I did just manage to properly create an integration test, which will make a GET request on the login page, performs a POST with credentials to the login page, and then a GET on a secured endpoint. I've pushed a minimal implementation in this repository: https://github.com/InDieTasten/Authenticated-Integration-Testing

The documentation was really helpful, including the AngleSharp samples for posting the login form. What was mostly costing me time was figuring out, that you cannot really override the registered db provider from ConfigureServices of the SUT. My web application factory was unable to overwrite the registered DbContext to use InMemory. The current samples provided by the docs only work, because they are using In-Memory DB for the SUT itself as well. That's what I changed in my code as well. That is a different issue though, so for integration testing with actual authentication using ASP.NET Core Identity you can see a perfectly working sample in my linked repository.

If there are any questions, feel free to post here or create an issue on the repository. Maybe someone else can write some high-quality documentation from my sample code. I think many people would appreciate that.

**Comment by guardrex** [comment]
@InDieTasten That was just updated, and I tested overriding a SQL Server dB used in the SUT with the in-memory dB in the test project. See the topic (version 3.0) for the latest updates that make that scenario work.

WRT ...

> you cannot really override the registered db provider from ConfigureServices of the SUT

... should work if you configure the SUT by environment (e.g., `Testing` environment ... or `Staging` ... or whatever), and you configure the app in that environment to use a different dB. Then, set the environment for the tests to `Testing` ... the SUT will use that environmental configuration. Although it involves having some test config in the SUT, which many devs will object to having at all, it should work ... and might make sense in some scenarios.

**Comment by InDieTasten** [comment]
@guardrex 
> the latest updates that make that scenario work.

Cool, I will take a look and maybe update the sample repo.

> Although it involves having some test config in the SUT, which many devs will object to having at all

Yeah, I remember using ConfigureTestServices in the past and being able to do that without the SUT having that kind of branching in the Startup. I'm not entirely sure about the changes to the DI going into 3.0. I'm confident, that there must still be a way to augment the service collection/provider of the SUT from the test assembly.

**Comment by guardrex** [comment]
We're going to start with https://github.com/aspnet/AspNetCore.Docs/pull/15340 **_initially_** for mocking auth. We'll keep an :eye: out and an :ear: open for more feedback as we go, especially for authorization beyond authentication.

**Comment by guardrex** [comment]
Oh ... and @InDieTasten good news on the SUT environment. That PR also has the new content that engineering suggests for setting the SUT environment. You can comment further on the PR if you want. Comment *quickly* tho ... we plan to have that approved within a few hours ... merged ... and live by the end of the day or tomorrow.
