### ISSUE TITLE
Add new Razor directives to Razor syntax doc

### ISSUE THREAD

**Issue by asklar** [aspnet/AspNetCore.Docs#13465]
The samples here reference @code for inserting C# code, however the Razor docs only call out @functions
https://docs.microsoft.com/en-us/aspnet/core/mvc/views/razor?view=aspnetcore-3.0
Which one is correct?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36e7dc3c-54c4-35de-203e-d230869e8417
* Version Independent ID: dc5b52d5-c8c6-1440-6b3a-fda898167d0c
* Content: [Build your first Blazor app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/build-your-first-blazor-app?view=aspnetcore-3.0)
* Content Source: [aspnetcore/tutorials/build-your-first-blazor-app.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/build-your-first-blazor-app.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
`@code` an alias of `@functions`, so both will work. However, `@code` is recommended now.

**Comment by guardrex** [comment]
I thought we listed that with the rest in the Razor syntax doc on an earlier PR. I can see now that we didn't. I'll take care of it. Thanks @asklar!

**Comment by guardrex** [comment]
I'll use this to add `@attributes`, too.

**Comment by guardrex** [comment]
@danroth27 We should confer on how to cover common and uncommon Razor syntax between the *Razor syntax* topic and Blazor topics.

I tried something that would have gone over better on 🎃 **_Halloween!_** 👻 with https://github.com/aspnet/AspNetCore.Docs/pull/13478 ... *Yikes!* It was a *living daymare* over there! 🙈

1. Do you want **_ALL_** of the Razor syntax in the [Razor syntax topic](https://docs.microsoft.com/aspnet/core/mvc/views/razor)?

   If so, then ...

   * I'll call out where a scenario applies (e.g., `@code` is for Razor components only, `@model` is for MVC only, etc.).
   * The Blazor topics don't need to describe the syntax in any more detail than is required for the examples that they show.

   If not, then I need to confirm our layout of the ordinary Razor syntax versus the Blazor-only Razor syntax across topics and react to any cross-coverage ... confirm we've separated the coverage cleanly.
1. Do you want *Razor directives* to be distinguished from *Razor directive attributes*? If so, should we have a *Directives* section and a section for *Directive attributes*? What section naming do you want?

These ❓ have wide-ranging implications for coverage of `@bind`/`@bind-*`/`@bind:format`, `@key`, `@{event}`, and duplication in the [Components: Razor support section](https://docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.0#razor-support).

This is a bit of an unresolved problem since merging the content from the `Blazor.Docs` repo where we had to cover the scenarios independently. I'll try to straighten it all out after I have your guidance.

**Comment by danroth27** [comment]
> Do you want ALL of the Razor syntax in the Razor syntax topic?

Yes. But, I generally consider the Razor Syntax topic a *reference* topic. It's OK to cover relevant Razor syntax features when discussing specific scenarios.

> Do you want Razor directives to be distinguished from Razor directive attributes? f so, should we have a Directives section and a section for Directive attributes? What section naming do you want?

Yes. The syntax for Razor directive attributes is more involved. Naming the sections "Directives" and "Directive attributes" sounds fine to me.
