### ISSUE TITLE
Document precedence of registered configuration sources

### ISSUE THREAD

**Issue by scottaddie** [aspnet/AspNetCore.Docs#13481]
For example, what happens when the same property exists in both *appsettings.json* and *secrets.json*? How are environment variables prioritized?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c99993c-c983-6fda-6c3a-ce4ec8c1d5db
* Version Independent ID: ba688ac2-e90e-fce5-f60d-40c2553c3efd
* Content: [Safe storage of app secrets in development in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/app-secrets?view=aspnetcore-3.0&tabs=windows#feedback)
* Content Source: [aspnetcore/security/app-secrets.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/app-secrets.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
The Environment Variables Configuration Provider is called after configuration is established from user secrets and appsettings files. Calling the provider in this position allows the environment variables read at runtime to override configuration set by user secrets and appsettings files.

**Comment by Rick-Anderson** [comment]
Secrets should not be stored in appsetting.json

**Comment by guardrex** [comment]
It's covered in the Web Host topic at ...

https://docs.microsoft.com/aspnet/core/fundamentals/host/web-host?view=aspnetcore-2.2#set-up-a-host

... and in the Generic Host topic at ...

https://docs.microsoft.com/aspnet/core/fundamentals/host/generic-host?view=aspnetcore-3.0#default-builder-settings

... but not in the app secrets topic. A quick line+cross-link should do the trick. Since this is lower priority and I'm 🏃 right now, I'll get to this later.

**Comment by Rick-Anderson** [comment]
And the list of default providers in order is here:  https://review.docs.microsoft.com/en-us/aspnet/core/fundamentals/host/generic-host?view=aspnetcore-3.0&branch=pr-en-us-13545#default-builder-settings
