### ISSUE TITLE
Advantage of using such highly specific interfaces vs generic controller end points for health?

### ISSUE THREAD

**Issue by SidShetye** [aspnet/AspNetCore.Docs#13510]
We use health check endpoints so understand the value of having them in general. However the healthcheck middleware prescribed here is highly specific and unnecessarily complicated for something trivial as a `true/false` or `healthy/degraded/unhealth` response to a simple `GET /health` endpoint. To balance those disadvantages, what advantage does this middleware offer over a simpler and more generalized controller endpoint based approach?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0cbb094-29e9-740a-9fd6-db372641d753
* Version Independent ID: 52d8efc9-a336-71d9-6d90-98173cbf6bf4
* Content: [Health checks in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/health-checks?view=aspnetcore-3.0#basic-health-probe)
* Content Source: [aspnetcore/host-and-deploy/health-checks.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/host-and-deploy/health-checks.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @SidShetye ... We only handle documentation feedback here. Please open product feedback for the engineers and managers at https://github.com/aspnet/AspNetCore/issues.

**Comment by SidShetye** [comment]
I’m asking you to document the advantages; not asking for a change to the products.

**Comment by guardrex** [comment]
I might not understand your request then. You'd have to provide more detail than what you stated because it sounds like you're asking about the design choices that engineering made.

We generally don't document engineering design choices. Our doc set is mostly made up of reference docs and tutorials. We don't get into 'advantages' and 'disadvantages' unless the framework offers options for a given scenario.

AFAIK today, the topic describes everything that engineering wants to cover. If there's a scenario that you don't think is covered (or not covered well), then *yes*, we'd like to hear about that. If your request is for the topic to explain framework design for Health Checks, then generally *no*, we probably don't want to include content like that.

**Comment by GoFightNguyen** [comment]
@SidShetye @guardrex Was an issue ever opened for this?

**Comment by guardrex** [comment]
@GoFightNguyen If you mean on the engineering repo, I don't think so. As far as the doc is concerned, it's reference content. Usually, we only cover the 'how to use?' aspects. We don't get into the 'why is it like this?' question. Design content can be very interesting, but we don't generally cover it in the reference topics. I imagine that if you research the genesis of health checks in the engineering repo and find the first few issues that you might find discussion on the design. You can open a new issue asking design questions or to provide product feedback.
