### ISSUE TITLE
XDT schema URL is correct but no longer seems to be a valid URL

### ISSUE THREAD

**Issue by daedam** [aspnet/AspNetCore.Docs#13553]
The URL for the XML-Document-Transform schema results in a HTTP 404. (http://schemas.microsoft.com/XML-Document-Transform) Is there a new URL for this schema, or was it removed from schemas.microsoft.com by mistake?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c703c55-7ece-6e0d-2518-50786599530a
* Version Independent ID: 7e68f62c-8c84-e7a5-2a74-201fc60b3036
* Content: [Transform web.config](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/transform-webconfig?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/host-and-deploy/iis/transform-webconfig.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/host-and-deploy/iis/transform-webconfig.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @daedam AFAIK, those were never real URLs ... unless you saw them work at some point. Truly, I don't recall ever looking. Sometimes companies do put spec info at the link that they use for the namespace URL, but I didn't think MS ever did ... well ... for many of them anyway.  AFAIK, they were just used by the tooling ... only to set the namespace and prefix ... and only in that format (a URL with "schemas.microsoft.com") so that they would be consistent across MS products/services and unique to MS.

We can't ping engineering on a question like this because they're so busy 🏃😅. I'm sure if you post a question to Stack Overflow or a support chat, such as Gitter or Slack, that a super-guru XML tranform :cat2: will come on and shed additional light.

**Comment by Soundman32** [comment]
XML Schema namespaces are not necessarily web URLs, they are just meant to be 'globally unique'.  One of the easiest ways to do this is to look like a web url, but that doesn't mean there has to be a document at that location. https://www.liquid-technologies.com/xml-schema-tutorial/xsd-namespaces
