### ISSUE TITLE
Required  ASP.NET Core Web API Test controller logic using xUnit document or sample application

### ISSUE THREAD

**Issue by ParthiKarnan** [aspnet/AspNetCore.Docs#13575]
I have built an  **ASP.NET Core 2.2 Web API** project that is deploying in production environment in azure. During the development I have not completed Unit Test in my project due to rapid delivery. Now, I'm searching **Unit Test** implementation document with example for an **ASP.NET Core 2.2 Web API controller** logic using **xUnit** with **EF Core in-memory database**s. If I will get any documentation or sample projects. It'll really help me to implement xUnit with my project.

Note:-
You may suggest which unit test (i.e, xUnit, nUnit or MsUnit , etc.,) suitable for **ASP.NET Core Web API** project v 2.2 or later  

Thanks,
Parthi

**Comment by guardrex** [comment]
Although this issue pertains to unit testing controller logic for web API, I'm going to add this to the Integration Testing project so that when testing issues are triaged this issue will get some visibility by engineering.

**Comment by ParthiKarnan** [comment]
Thanks for your response @guardrex . I'm not telling you this is an issue. I'm just requesting you to provide some document or sample xUnit Test implementation for ASP.NET Core 2.2 Web API with EF Core In-Memory database. So that, It'll help for every engineers who are looking for this kind of example.

**Comment by ParthiKarnan** [comment]
@guardrex @shanselman any update?

**Comment by guardrex** [comment]
Decisions on what (and when) to cover testing scenarios is handled by engineering. This issue is on the Integration Testing project for triage.

@Rick-Anderson Did you get a sense from talking with them when they might have a look at the 14 issues there? My orders are not to work any of them until they have a chance to go thru and see what they want to cover and which ones they want to work themselves. Even if they assign any to me, it's not clear that I'll even be here long enough to work them. 🏖

**Comment by Rick-Anderson** [comment]
Hopefully they will look at them when 3.0 GA's

**Comment by guardrex** [comment]
Moved to the tracking issue for this topic: **Integration tests MASTER issue** #16341
