### ISSUE TITLE
Add startup code block on Build your first app page

### ISSUE THREAD

**Issue by mpetrinidev** [aspnet/AspNetCore.Docs#13607]
[EDIT by @guardrex to mention that this should be worked with **Replace 'Build your first' tutorial** #10773, where the current tutorial will be completely replaced.]

I was reading the tutorial that shows how to build your first app on Blazor.
On the [Dependency Section](https://docs.microsoft.com/en-us/aspnet/core/tutorials/build-your-first-blazor-app?view=aspnetcore-3.0#dependency-injection) mentions and refers that you have to register the service as a singleton on server side.

Is it possible to insert the code block of the startup? I think that is better for reading if you're doing the tutorial.

```csharp
public void ConfigureServices(IServiceCollection services)
{
    services.AddRazorPages();
    services.AddServerSideBlazor();
    services.AddSingleton<WeatherForecastService>();
}
```

**Comment by guardrex** [comment]
I avoided that on purpose because there was considerable churn in `Startup` during the early previews. I knew that more changes were coming, and there was the Generic Host updates to consider.

*Yes!* on this, but I'd like to wait on it until we get closer to 3.0. I'll mark this for the release candidate period and take care of it at that time.

Thanks @mpetrinidev! :rocket:

**Comment by guardrex** [comment]
btw --- There's a **This Page** feedback button at the bottoms of the topics. Please use that form. It adds metadata to the issues to help us track the work.
