### ISSUE TITLE
Cannot create a .razor page that has a name that ends with "Component"

### ISSUE THREAD

**Issue by endstreet** [aspnet/AspNetCore.Docs#13742]
if I try to create a .razor page as in your sample that ends with "Component" as in your sample, the razor markup fails immediately. What could be the problem?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be4c4d0c-149c-bde1-c7fa-f082916390ca
* Version Independent ID: 9d945996-ad02-bd4b-58ea-c465cc5cc74c
* Content: [Create and use ASP.NET Core Razor components](https://docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.0)
* Content Source: [aspnetcore/blazor/components.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/components.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Fails in what way? Is there an error message?

**Comment by guardrex** [comment]
You're using the latest VS 2019 Preview, correct? Version should be 16.3 Preview 1.

**Comment by guardrex** [comment]
Note that while we're in preview that tooling behavior might be a little bit shaky. Search the [engineering repo (open and closed issues)](https://github.com/aspnet/AspNetCore/issues?utf8=%E2%9C%93&q=is%3Aissue+) for issues that you run into because issues are reported there on a rolling basis. It's best to search open **_and closed_** issues. Recently closed issues often reflect things that the engineering team fixed for the next release, which will be *Preview 8*.

Problems with VS can be reported to the VS team using the **Report a Problem** process built into VS. That opens an internal issue for that team.

If you need general tips and advice, ask on Gitter ... https://gitter.im/aspnet/Blazor

We only work documentation issues here and don't have the staffing to provide product support. Of course if you think something is wrong with a topic, please do open an issue using the **This Page** feedback button at the bottom of any topic.
