### ISSUE TITLE
Workaround for the Blazor (client-side) template not visible

### ISSUE THREAD

**Issue by joslat** [aspnet/AspNetCore.Docs#13761]
As there seems to be a known issue, https://github.com/aspnet/AspNetCore.Docs/issues/13531 which has a known root cause https://github.com/aspnet/AspNetCore/pull/11707
I'd propose either to create the blazor client project from command line with "dotnet new blazor" or either select the "ASP.NET Core Web Application" template and on the third step we will be asked the ASP.NET Core project template to use. One of them is "Blazor (client-side)", so go and use it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c07e57dc-526f-9479-4695-de7d8f06eb9a
* Version Independent ID: 8226ed72-69b2-3c93-a931-218bd11cf9c8
* Content: [Get started with ASP.NET Core Blazor](https://docs.microsoft.com/en-us/aspnet/core/blazor/get-started?view=aspnetcore-3.0&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/blazor/get-started.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/get-started.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Those seem closed/merged ... we'll see when this issue is triaged if the fix is in for Pre8 (or VS's new preview release); and if so, if we'll need to cover anything in the meantime. Exact date for Pre8 release isn't **_publicly_** announced (I know what it is but I'm sworn to 🙊 secrecy), but the Pre8 engineering issues on the roadmap are all worked/closed/merged and the milestone for Pre8 shows 197 issues closed and **_0 issues open_**. *I'll let you guess what that means.* :smile:

**Comment by joslat** [comment]
Sounds like great work! :)

**Comment by serkan-cakmak** [comment]
I like this

**Comment by jerryzjw** [comment]
I just installed VS 2019 Community Version (Version 16.3.0 Preview 2.0) with .NET Core 3.0 Preview 8. I also ran the command "dotnet new -i Microsoft.AspNetCore.Blazor.Templates::3.0.0-preview8.19405.7", which I copied from Get started with ASP.NET Core Blazor page. I'm able to see the Blazor App project type when creating a new project but don't see the Blazor (Client-Side) template even after selecting Asp.NET Core Web App.

**Comment by guardrex** [comment]
@jerryzjw It should be called **Blazor WebAssembly App** now. If you don't see it (and try restarting VS if you haven't done that already), open an engineering issue https://github.com/aspnet/AspNetCore/issues ... but search the closed issues there with the `area-Blazor` label first to see if others reported this and the team already responded.

I'm going to close this issue now because their work for Pre8 and the latest VS preview should have resolved *most* of the issues.
