### ISSUE TITLE
Review Blazor Sample code for API review changes

### ISSUE THREAD

**Issue by rynowak** [aspnet/AspNetCore.Docs#13787]
We've made a bunch of API changes in Blazor during preview 8 and preview 9. We need to review all of the existing docs and sample and find places where they are out of date.

**Comment by guardrex** [comment]
Note that Pre9 updates thus far are on the `release/3.0-preview9` branch. Definitely look there and not at `master` to assess the state of the content if this issue is worked prior to the staging branch merging.

**Comment by guardrex** [comment]
@rynowak Update ......

* The Pre9 staging branch PRs are all merged, and Scott will merge staging to master and master to live sometime this evening (Wednesday, 9/4).
* First thing Thursday morning, I'll work ...
  * [OnAfterRenderAsync(bool firstRender) (aspnet/AspNetCore.Docs \#14146)](https://github.com/aspnet/AspNetCore.Docs/issues/14146)
  * A mop-up PR based on the blog post to catch any remaining updates.

After that and unless anything else comes in, you're good to go here on `master`. I'll note back here when the deeds are done.

**Comment by guardrex** [comment]
@rynowak Update ......

New issues have been assigned to me that I should knock out before you perform the review. See the *P0/P1 - High Priority* column on the project ...

https://github.com/aspnet/AspNetCore.Docs/projects/35

I'll ping back here when all of the work is done and merged.

**Comment by guardrex** [comment]
@rynowak Update ...

[Blazor.Docs GH Project](https://github.com/aspnet/AspNetCore.Docs/projects/35)

* Two issues/PRs are in review now:
  * [Blazor circuits, security, and hosting guidance (aspnet/AspNetCore.Docs \#14189)](https://github.com/aspnet/AspNetCore.Docs/pull/14189) &ndash; Feedback addressed ... awaiting final approval.
  * [Blazor chained bind (aspnet/AspNetCore.Docs \#14215)](https://github.com/aspnet/AspNetCore.Docs/pull/14215) &ndash; Went in today (Sunday) ... should be quick to approve and merge.
* Two more issues for me to work:
  * [Add documentation for parsing during binding (aspnet/AspNetCore.Docs \#13014)](https://github.com/aspnet/AspNetCore.Docs/issues/13014) &ndash; Planning to work this on Monday.
  * [Update Blazor hosting model terms (aspnet/AspNetCore.Docs \#14177)](https://github.com/aspnet/AspNetCore.Docs/issues/14177) &ndash; Also planning to work on Monday, but I'd like to work it after we merge the *Parsing during binding* work.

I think that will clear the way for this issue ... will keep u posted here.

I just opened an issue for the common sample related to this issue: We have in-text code examples that would make great demos in the sample app. However, it's best if this issue is worked first to iron out any problems with all of the coverage. I opened #14216 to address it and put it in the HOLD column of the project for now.

cc: @danroth27 ... I keep'in :ear::ear::ear::ear: open for guidance changes.

**Comment by guardrex** [comment]
@rynowak Update ...

All of the prior issues mentioned :point_up: are resolved and merged.

There are two new issues for me ...

* [Provide guidance about how to do async work in Blazor](https://github.com/aspnet/AspNetCore.Docs/issues/14260)
* [Blazor common sample error](https://github.com/aspnet/AspNetCore.Docs/issues/14338)

... but I doubt that I can get to those this week (or within two weeks!) given all of the non-Blazor 3.0 work on my head. 🏃

AFAICT, you can perform your total Blazor docs review+update at any time.

WRT to [splitting the Components topic (aspnet/AspNetCore.Docs #14353)](https://github.com/aspnet/AspNetCore.Docs/issues/14353), we can go with either of ...

1. Do that first. You work this issue afterward.
1. Work this issue first.

... let me what u plan to do.

For your PR on this issue, I'll review it and make a direct commit to it *after* additional engineering review on the technical aspects.

I propose that we let you create that PR and merge it with a :smile: and not :boom::cry:. Therefore, when you start to work this, plz shoot a comment on here to let me/us know you've started. Go ahead and use the `master` branch for the updates.

**Comment by rynowak** [comment]
@guardrex  - PR here: https://github.com/aspnet/AspNetCore.Docs/pull/14451#pullrequestreview-291435819
