### ISSUE TITLE
dotnet-aspnet-codegenerator NuGet tool installation

### ISSUE THREAD

**Issue by wcqrnj** [aspnet/AspNetCore.Docs#13980]
At the NuGet package installation section, I miss "dotnet tool install --global dotnet-aspnet-codegenerator". I could not scaffold movie pages without this tool (on Linux, VS Code).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d975a83-1550-b284-d0d8-7fe2ea206ff5
* Version Independent ID: 48e81b42-7c2b-afbf-71e6-d4f442a4bd1f
* Content: [Add a model to an ASP.NET Core MVC app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/adding-model?view=aspnetcore-3.0&tabs=visual-studio-code#feedback)
* Content Source: [aspnetcore/tutorials/first-mvc-app/adding-model.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-mvc-app/adding-model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by flagrama** [comment]
This seems to still be an issue. Just today I was following through this tutorial on Linux and the scaffolding step would not work because this was not installed in addition to the other requirements. Nowhere on the page is this stated that you need to install it as well. I had to look through _closed_ issues to figure out what the issue was.

`dotnet tool install --global dotnet-aspnet-codegenerator` should probably be added along with 
```
dotnet tool install --global dotnet-ef
dotnet add package Microsoft.EntityFrameworkCore.SQLite
dotnet add package Microsoft.VisualStudio.Web.CodeGeneration.Design
dotnet add package Microsoft.EntityFrameworkCore.Design
dotnet add package Microsoft.EntityFrameworkCore.SqlServer
```
in the [Add NuGet packages](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/adding-model?view=aspnetcore-3.0&tabs=visual-studio-code#add-nuget-packages) step as it does seem to be required _in addition_ to the ones already there, at least on Linux.

**Comment by Rick-Anderson** [comment]
@flagrama  how does that differ from the instructions?

```
dotnet tool install --global dotnet-ef
dotnet add package Microsoft.EntityFrameworkCore.SQLite
dotnet add package Microsoft.VisualStudio.Web.CodeGeneration.Design
dotnet add package Microsoft.EntityFrameworkCore.Design
dotnet add package Microsoft.EntityFrameworkCore.SqlServer
```
