### ISSUE TITLE
Platform Setting must be clearly mentioned

### ISSUE THREAD

**Issue by sujayvsarma** [aspnet/AspNetCore.Docs#14000]
There are two places one would set up the App Service platform for an application:

1) The App Service's Configuration - General Settings page.

2) In Visual Studio when you publish the app.

BUT, the two HAVE TO MATCH. Otherwise, you will get an ACNM exception during app start and the message will say it could not find the framework for the app. This happens even if you publish in Self Contained mode.

The Fix is to go into App Service - General Settings, set the platform and match that platform value (x86 or x64) in the dropdown when you publish from Visual Studio. 

This is a hard requirement at the moment. At least until the folks at Visual Studio set it for you -- and they have refused to do so. So this has to be mentioned in the document above.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2eab542-a420-d6c5-d314-a420837cf602
* Version Independent ID: 48c12168-54f3-0b83-f136-565f483a03e9
* Content: [Deploy ASP.NET Core apps to Azure App Service](https://docs.microsoft.com/en-in/aspnet/core/host-and-deploy/azure-apps/index?view=aspnetcore-2.2&tabs=visual-studio)
* Content Source: [aspnetcore/host-and-deploy/azure-apps/index.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/host-and-deploy/azure-apps/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @sujayvsarma ... Bitness has been a bit of a pain point because how it should be managed hasn't been stable over releases and SDK bitness has played a role.

We have some coverage ...

https://docs.microsoft.com/aspnet/core/host-and-deploy/azure-apps/#deploy-the-app-framework-dependent

... but I agree that the topic requires more work. A few things to address:

* I think having the paid tier be the recommended approach is a bit problematic, since it throws up a barrier to adoption. We don't normally take that approach when there's a free option, the free App Service tier in this scenario.
* Bitness concepts do span FDD and SCD, but the topic isn't written that way right now. The instructions should probably explain the default case across deployment types. A new section on bitness can explain out the scenarios for non-default deployments and the platform setting in App Service (i.e., paid tier access).

I'll see about improving these aspects. Thanks for commenting.

**Comment by sujayvsarma** [comment]
Thank you @guardrex

**Comment by sujayvsarma** [comment]
Thank you @guardrex. 

The reason I filed this bug was because I created a new App Service from Visual Studio's Publish workflow. That had the following settings:

Runtime stack: BLANK
Bitness: 32-bit

It was an ASP.NET Core 3.0 MVC app. Try whatever I might, I kept getting the weird ACNM exception saying it could not load the runtime. Then when I compared this app service to ones I had created in the past -- I have about 15 running fine in the same account, with the same tech stack! - I found this difference. As soon as I updated the values, the App Service began to run fine.

Then it dawned on me. I always created the App Service from the portal, and then publish to that from VS. So I usually set up these properties ahead of time. That's probably why I never noticed this before! 

That got me to search specifically for this doc and file this item hoping that it would help future travellers.
