### ISSUE TITLE
Add additional pointers to continue learning

### ISSUE THREAD

**Issue by surfmuggle** [aspnet/AspNetCore.Docs#14071]
After step 16 of [build-a-todo-list](https://docs.microsoft.com/en-us/aspnet/core/tutorials/build-your-first-blazor-app?view=aspnetcore-3.0#build-a-todo-list) i suggest to add a headline "Learn more" with a bullet list similar to the [tic-tac-toe tutorial from reactjs](https://reactjs.org/tutorial/tutorial.html#wrapping-up) where you list ways to extend the todo app

 - add todo item if user presses enter inside the input (learn more about [event handling](https://docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.0#event-handling))

 - add a responsible person to each todo item by using a select field 

 - and so on

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36e7dc3c-54c4-35de-203e-d230869e8417
* Version Independent ID: dc5b52d5-c8c6-1440-6b3a-fda898167d0c
* Content: [Build your first Blazor app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/build-your-first-blazor-app?view=aspnetcore-3.0)
* Content Source: [aspnetcore/tutorials/build-your-first-blazor-app.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/build-your-first-blazor-app.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @surfmuggle ... but a couple of issues with that suggestion:

* We aren't allowed by our guidelines to link off very much in these. We are allowed to have a *Next step* at the end but not a list of links to other resources. Currently, we link off to the *Components* topic. I think they decided on this approach in order to keep the experience focused on one straightforward set of learning objectives.
* We're going to replace the entire tutorial soon (https://github.com/aspnet/AspNetCore.Docs/issues/10773). Given that this one will go away (perhaps right after 3.0 is released in a few months), there's not much interest in extending it given our current (heavy) workload for 3.0. 🏃😅 We're just keeping it updated for each preview release and addressing bug reports on it until then.
* The next version of this tutorial will have a lot more 🍖 *meat on the bone* 🍖 ... it will cover many more concepts than this one.
* There has also been talk of an *advanced* tutorial to go right after this one. If that happens, what you're suggesting would be covered in the followup tutorial.

Thanks anyway tho for the suggestion.
