### ISSUE TITLE
Where's the Run button in Visual Studio?

### ISSUE THREAD

**Issue by abukres** [aspnet/AspNetCore.Docs#14087]
"Set the Run button to the IIS profile and select the button to start the app.".

Where's the Run button? There are Start Debugging and Start Without Debugging buttons. Please update the docs to make this clearer.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5477f20-bdbf-ae0b-63b4-8bf6789f7a48
* Version Independent ID: fa9dc362-76a4-5d11-f457-b3d8550f9997
* Content: [Development-time IIS support in Visual Studio for ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/development-time-iis-support?view=aspnetcore-3.0#)
* Content Source: [aspnetcore/host-and-deploy/iis/development-time-iis-support.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/host-and-deploy/iis/development-time-iis-support.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @abukres ... The Run button is here ...

<img width="258" alt="Capture" src="https://user-images.githubusercontent.com/1622880/64011288-031a0500-cae1-11e9-9238-b1a97569cf80.PNG">

After creating a profile named "IIS," pop open the run button with the small downward-pointing triangle (right side of the button) and set the button profile to "IIS." Select the button to run the app with the IIS profile.

We try not to put images into the docs because they're so hard to maintain. In this case, it makes sense to have an image. The VS toolbar and Run button are stable IDE features. I'll place a pic into the topic. Thanks for commenting.

**Comment by abukres** [comment]
I have no Run button and no button that says IIS Express. The only green filled triangle button I have is start Debugging (F5). Let's assume I need to add it, which category and command should I add? When you hover over IIS Express, does your tooltip say Run? What does your tooltip read?

**Comment by abukres** [comment]
I have IIS working now with a Blazor app.
