### ISSUE TITLE
Integration testing with managed identities in Azure DevOps Pipelines

### ISSUE THREAD

**Issue by ps-tb** [aspnet/AspNetCore.Docs#14179]
We have integration tests that run as part of a pipeline in Azure DevOps. The issue that we're experiencing is that the build agent doesn't have a managed identity and therefore the tests won't run. Is there any recommendation for how to handle this case? We have the app setup such that we always use the Key Vault provider regardless of environment. If we're working locally, we use the Azure CLI to login and gain access this way. Thank you for any information or direction that can be provided.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2cc0b77a-df21-7007-5cec-4399d98c6dc6
* Version Independent ID: efe5ae5e-ff64-f1c7-6920-4512fc8f36d1
* Content: [Azure Key Vault Configuration Provider in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/key-vault-configuration?view=aspnetcore-2.2#disabled-and-expired-secrets)
* Content Source: [aspnetcore/security/key-vault-configuration.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/key-vault-configuration.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Good ? @ps-tb ... Is the certificate approach not a good workaround for you in that scenario?

**Comment by ps-tb** [comment]
It might be but I have questions about this setup, if you don't mind. If this isn't the right forum for these questions please let me know or direct me elsewhere. 

Do you think that it would that mean a testing environment to differentiate between development/production? Something like the very pseudo code below?

```
if  env.IsEnvironment("testing")):
  use the certificate based approach
else:
  use the managed identity approach
```

Would a self hosted build agent alleviate this need? It appears that Azure VMs can be assigned a managed identity (https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/services-support-managed-identities).

**Comment by guardrex** [comment]
It looks like they have a section on it ... did you see this? :point_right: https://docs.microsoft.com/azure/devops/pipelines/library/connect-to-azure?view=azure-devops#create-an-azure-resource-manager-service-connection-to-a-vm-with-a-managed-service-identity

It seems like that would work ... that managed identity would be given access to the vault and it would *Just Work*:tm:. 🤞 Of course, I haven't tried it, so I don't know if it will work.

They have a *Help and Support* section. You could try that, but I see one of them is just Stack Overflow, which we suggest all the time because there are so many devs there. You can also try:

* [ASP.NET Core Slack Team Room](http://tattoocoder.com/aspnet-slack-sign-up/) (not official but maintained by a MS employee)
* [ASP.NET Gitter](https://gitter.im/aspnet/Home) (this is official)

... and similar chats where Azure devs hang out are bound to be out there.

**Comment by ps-tb** [comment]
@guardrex Thanks for all the info. It's probably (likely...def. is) well beyond the scope of the article so I appreciate it. I think that I have enough to go on now so you're welcome to close the issue. Thanks again.

**Comment by guardrex** [comment]
Sure ... I think there's a cross-link opportunity here. Let me take another look at that. The DevOps Pipeline reference might be a good idea. I'll take a look this evening.
