### ISSUE TITLE
ConnectionStrings - appsettings.json

### ISSUE THREAD

**Issue by Legends** [aspnet/AspNetCore.Docs#14327]
Jump to here:
https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/adding-model?view=aspnetcore-3.0&tabs=visual-studio#add-a-database-connection-string

If `ConnectionStrings` is a convention, then it should be mentioned in the section above.
I know the ConnectionString key `MvcMovieContext` is passed in `startup.cs`, but how does it know where to get the value from --&gt; `ConnectionStrings`?
Does the app parse the appsetttings.json and search for `MvcMovieContext` or does it know it's under `ConnectionStrings` and searches there for the key?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d975a83-1550-b284-d0d8-7fe2ea206ff5
* Version Independent ID: 48e81b42-7c2b-afbf-71e6-d4f442a4bd1f
* Content: [Add a model to an ASP.NET Core MVC app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/adding-model?view=aspnetcore-3.0&tabs=visual-studio#add-a-database-connection-string)
* Content Source: [aspnetcore/tutorials/first-mvc-app/adding-model.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-mvc-app/adding-model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Legends** [comment]
In VS2019 I don't have any intellisense for appsettings.json available, when I write `ConnectionStrings`, so if it's a convention intellisense should be there to support.

Or can we name the section `SomeDbConnStrings` and put the `connectionstring` there?

**Comment by Rick-Anderson** [comment]
Thanks for contacting us.
We don’t have the resources to invest in this area, so we are closing the issue. Should your request generate enough  👍 responses, we’ll reconsider.

**Comment by xenophilios** [comment]
It would be really nice if "DbContext class" were an option of a new item that could be added to a folder and if all we had to do to register it in Startup.cs and add a connection string in appsettings.json were to give it a name.

**Comment by xenophilios** [comment]
It would also be very nice if we could see the database schema in graphic form, as we used to be able to do.

**Comment by xenophilios** [comment]
Concerning my last comment but one:
It is already possible to have VS 2019 do these things, if not in exactly the way described.
Here is one way:
(1) In /Models, define a class to be mapped to a database table.
(2) Right-click on /Controllers.
(3) Add | New Scaffolded Item...
(4) Choose: MVC Controller with views, using Entity Framework.
(5) As the model class, choose the class defined in Step (1).
(6) For the data context class, click on the plus sign ("+").
(7) If you so desire, edit the proposed name for this class. There is no need to change the folder name (from "Models"), because it will be changed automatically to "Data". A "Data" folder will be created automatically, if you haven't created one already.
(8) Click "Add" to finish and wait for VS to install the required NuGet packages, create the data context class, register it in Startup.cs, and define the connection string in appsettings.json.
