### ISSUE TITLE
Hosting Model

### ISSUE THREAD

**Issue by jagwaran** [aspnet/AspNetCore.Docs#14436]
I installed ASP.NET Core Module (for IIS) and I have a simple ASP.NET Core 2.1 app with netcoreapp2.1 in the vsproj project file TargetFramework element.

I published to IIS and I set the hostingModel="inprocess" in the web.config for aspNetCore.

But still, when I see the "Server:" in response header in the browser developer tool, it says "Server: Kestrel". This means, the app is running with OutOfProcess right?

Also, is there any way problematically log/see what hostingModel app started with?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec484002-18c1-6a0d-00de-820d56f038d3
* Version Independent ID: 7903ce53-2cbb-f083-7479-c8abc30211a0
* Content: [Host ASP.NET Core on Windows with IIS](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/?view=aspnetcore-2.2)
* Content Source: [aspnetcore/host-and-deploy/iis/index.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/host-and-deploy/iis/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
In-process is for 2.2 or later. The hosting model content appears in the docs depending on the version selector in the upper left-hand corner of the docs page. Since you're trying to use 2.1, set it down to 2.1. You'll see all of the hosting model content disappear given that 2.1 doesn't support in-process.

Yes on the `Server` header. It will change for in-proc. For example, my test app running on my local IIS (running on Win10) reports ...

```
Server: Microsoft-IIS/10.0
```

Here are the links to two chats, where devs will help with general support questions ...

* [ASP.NET Core Slack Team Room (self-signup)](http://tattoocoder.com/aspnet-slack-sign-up/) - not official, but run by a MS employee.
* [ASP.NET Gitter](https://gitter.im/aspnet/Home) - this is official.

**Comment by jagwaran** [comment]
Thanks again @guardrex 
I missed to see the content changing when I change the version links at the top in the docs.
It was my bad that I was looking for the entire page reload, but it is "AJAXified" or show/hide implemented :).
