### ISSUE TITLE
ConfigureKestrel() conflict with appsettings

### ISSUE THREAD

**Issue by khteh** [aspnet/AspNetCore.Docs#14566]
I have Kestrel section in appsettings.json and I also call ConfigureKestrel() in Program.cs. When I run the app, there is an error:
```
11:10:36 [Warning] () Overriding address(es) '"https://localhost:5003"'. Binding to endpoints defined in "UseKestrel()" instead.

11:10:36 [Fatal] () Unable to start Kestrel.
System.IO.IOException: Failed to bind to address https://[::]:5003: address already in use. ---&gt; Microsoft.AspNetCore.Connections.AddressInUseException: Address already in use ---&gt; System.Net.Sockets.SocketException: Address already in use
```
Here is my appsettings.json:
```
    "Kestrel": {
        "Endpoints": {
          "HttpsInlineCertFile": {
            "Url": "https://localhost:5003",
            "Certificate": {
              "Path": "/tmp/localhost.pfx",
              "Password": "password"
            }
          },
          "HttpsDefaultCert": {
            "Url": "https://localhost:5003"
          },
          "Https": {
            "Url": "https://*:5003",
            "Certificate": {
                "Path": "/tmp/localhost.pfx",
                "Password": "password"
            }
          }
        },
        "Certificates": {
          "Default": {
            "Path": "/tmp/localhost.pfx",
            "Password": "password"
          }
        }
    },
```
Here is my ConfigureKestrel():
```
            .ConfigureKestrel((context, options) =>
            {
                options.Listen(IPAddress.Any, 5003, listenOptions =>
                {
                    listenOptions.UseHttps(o => o.SslProtocols = SslProtocols.Tls12);
                    listenOptions.UseConnectionLogging();
                    listenOptions.Protocols = HttpProtocols.Http1AndHttp2;
                });
            });
```
OR:
```
            .ConfigureKestrel((context, options) =>
            {
                options.Configure(context.Configuration.GetSection("Kestrel"))
                    .Endpoint("Https", listenOptions =>
                    {
                        listenOptions.HttpsOptions.SslProtocols = SslProtocols.Tls12;
                        listenOptions.ListenOptions.UseConnectionLogging();
                        listenOptions.ListenOptions.Protocols = HttpProtocols.Http1AndHttp2;
                    });
            });
```
So, which is which? I am confused. Can I do everything in appsettings.json?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f22dcddb-0c25-be1a-9a02-9e71dce86bdb
* Version Independent ID: 3e0e12c2-e544-5655-e001-d2ec180b11a8
* Content: [Kestrel web server implementation in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel?view=aspnetcore-2.2)
* Content Source: [aspnetcore/fundamentals/servers/kestrel.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/servers/kestrel.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Yes, you can. If you call `CreateDefaultBuilder`, the settings (from the file) will apply to the configuration without you having to do anything in code.

I see a few things here to address:

* Bad link (to web host) and a minor grammatical issue ("endpoint is a available").
* `CreateDefaultBuilder`:
  * Isn't cross-linked. It wasn't linked on purpose because we have both Web Host and Generic Host coverage concurrently in the doc. I think I see a better way to handle it. We can link in parentheses to both host topics ... "([Generic Host](https://docs.microsoft.com/aspnet/core/fundamentals/host/generic-host#default-builder-settings) / [Web Host](https://docs.microsoft.com/aspnet/core/fundamentals/host/web-host#set-up-a-host))" with each linked to its respective host destination.
  * Probably isn't mentioned/cross-linked enough. Since all of the Kestrel config can come from the settings file, it either should be:
    * At the very top of all Kestrel config in its own section (probably best).
    * Or, briefly mentioned at the top of each of the existing sections. It's in the HTTPS config section. That's fine, but it should also be cross-linked from perhaps two other spots.

WRT to the two `ConfigureKestrel` approaches that you showed ...

The 2nd one allows you to load a different section of configuration (from any configuration source that has been provided, including the app settings file config) and then perform additional config in code on just that loaded section via the `Endpoint` ... **_BUT_** ... the `UseKestrel` warning pertains to how you composed it. Scroll down in https://docs.microsoft.com/aspnet/core/fundamentals/servers/kestrel#listenoptions-usehttps to see an example of the correct composition.

The first one is the best choice configuring entirely in code (no configuration involved).

**Comment by khteh** [comment]
How about the `SslProtocols` and `UseConnectionLogging`? How to configure them in the config file? Is there any document on the available configuration properties for Kestrel using config file?

I might be wrong but I read that kestrel configuration using external config file was removed sometime in the journey of .Net Core but added back in. What's the best approach/practice? External config file or code? Thanks.

**Comment by guardrex** [comment]
> How to configure them in the config file?

On the first point, I really do think that it's possible. However, I haven't done it ... or even looked that far into it. I agree that it's a problem that we need to address in the content. I would even go so far perhaps to including a "snapshot" JSON file linked to the topic that has all of the settings shown (or over at http://schemastore.org/json/ ... similar to http://json.schemastore.org/appsettings).

When I get to this issue, I'll confer with engineering, do some testing here, and get our content fleshed out.

If you can't wait that long (ur working on this today 🏃) and can't figure out the composition or find online resources, I recommend Stack Overflow, Slack, Gitter first. If that doesn't pan out, open an engineering issue to ask (**_last resort_** given how busy the engineers are).

> kestrel configuration using external config file was removed sometime in the journey of .Net Core but added back in

I don't recall such a period, and I've been here since ..... er ..... **_Beta 5_** 👴 :smile: lol

> External config file or code?

Rubber :duck: always says, **_"Config file plz!"_**

Main benefit: Just update the file on the hosting system (environment) (by name *appsettings.development.json*, *appsettings.staging.json*, *appsettings.production.json*, etc.), and it's all good. It's very easy to manage config that way.

**Comment by guardrex** [comment]
@halter73 Working this now.

Cross-linking a bit for `CreateDefaultBuilder` is done. *Easy!*

The other aspect of this issue is a bit harder to address. Rubber :duck: says not to ask this stupid question, but do you have a schema for *all* of the Kestrel options that would be loaded from a configuration provider showing all of the keys? ........ (Rubber :duck: is laughing at me now.)

You see, we focus on this only for the most complicated scenario (that would be *very* hard to guess), the listen options for endpoints. However, I think we should have a brief example early in the discussion of options that speaks to loading basic options from configuration providers with at least a quick/short example.

Any thoughts on this?

**Comment by guardrex** [comment]
For example, something along the lines of (if this is even correct; haven't tested it yet) ...

> The following options, which are configured in C# code in the examples, can also be set using a \[configuration provider](fundamentals/configuration/index). For example, the File Configuration Provider that loads app settings from a file (\*appsettings.json\* or \*appsettings.{Environment}.json\*) when \`CreateDefaultBuilder\` is called can also load Kestrel configuration:
> 
> ```json
> {
>   "Kestrel": {
>     "Limits": {
>       "MaxConcurrentConnections": 100,
>       "MaxConcurrentUpgradedConnections": 100
>     },
>     "AllowSynchronousIO": true,
>     "AddServerHeader": false
>   }
> }
> ```

**Comment by guardrex** [comment]
@halter73 Let's discuss this further on the PR. I think I'm close to something that will work there.
