### ISSUE TITLE
Allowed location value is wrong

### ISSUE THREAD

**Issue by ihorbond** [aspnet/AspNetCore.Docs#14643]
Location and Duration
To enable caching, Duration must be set to a positive value and Location must be either Any (the default) or Client. In this case, the Cache-Control header is set to the location value followed by the max-age of the response.

But caching doesn't work with Location set to Client. This page https://docs.microsoft.com/en-us/aspnet/core/performance/caching/middleware?view=aspnetcore-2.2 under *Conditions for caching* also says the following: "Cache-Control header parameters must be valid, and the response must be marked public and not marked private"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b6728e59-93ec-891e-0416-94819296ad72
* Version Independent ID: 5d581acc-c651-2112-844a-6b85dc5a99a6
* Content: [Response caching in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/performance/caching/response?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/performance/caching/response.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/performance/caching/response.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-performance**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
There's a distinction between client-side caching (the `ResponseCache` attribute sets the response caching headers) and what the middleware does. The client is free to cache based on the header notwithstanding whatever the middleware does. I guess the underlying question is does this doc confound these two *different* aspects of caching?

**Comment by anurse** [comment]
Yeah, I also don't think there's an inconsistency here, though perhaps the docs need to be updated.

* `Location.Any` allows the client **or any intermediate proxy** to cache the value (including the server-side caching middleware). It does this by setting the `Cache-Control` header to `public`.
* `Location.Client` indicates that **only the client** may cache the value, and **no intermediate cache can do so** (including the server-side caching middleware). It sets the `Cache-Control` header to `private` in order to do so.

@guardrex I think you're on the same page here as well. The client is always free to cache, the `Location` value is controlling whether intermediaries (the caching middleware, as well as any proxies down-stream).
