### ISSUE TITLE
files described

### ISSUE THREAD

**Issue by carltonsmith** [aspnet/AspNetCore.Docs#14713]
This page has some great information, but it doesn't say anything about where these files should be created or what their filenames should be. Isn't that important?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed756b9c-1d37-cd29-dbca-2838ddf152fb
* Version Independent ID: 06064983-8ada-c25d-2adc-ffb4059978f2
* Content: [Dependency injection into views in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/dependency-injection?view=aspnetcore-3.0)
* Content Source: [aspnetcore/mvc/views/dependency-injection.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/views/dependency-injection.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @carltonsmith ... Largely up to you. Of course, *Views* for views, *Controllers* for controllers, *Pages* for pages, *Services* for services are all quite typical for folders. Filenames are your call. You'll see a lot of services with "Service" at the end of the file name ... that's common ... but not required, of course. You can take a look at our sample apps, which are engineering-team approved, or check out engineering samples around [the engineering repo](https://github.com/aspnet/AspNetCore/) to see what we/they do. Chat with devs on Slack or Gitter if you want to just see what community devs do.

I'll close because I don't think that we'll make any explicit recommendations on it.

**Comment by guardrex** [comment]
btw @carltonsmith ... here are the links to those chats if you need them ...

* [Slack](http://tattoocoder.com/aspnet-slack-sign-up/)
* [Gitter](https://gitter.im/aspnet/Home)

**Comment by carltonsmith** [comment]
Thanks, @guardrex , much appreciated!
