### ISSUE TITLE
3.0 - Add 3.0 version of app.Use(async (context, next) =>

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/AspNetCore.Docs#14773]
PR #14734 will add the following 2.2 code

```
public void Configure(IApplicationBuilder app)
{
    app.Use(async (context, next) =>
    {
        await context.Response.WriteAsync("Hello ");

        await next();

        if (!context.Response.HasStarted)
        {
            context.Response.Headers["test"] = "test value";
        }
    });
}
```

Need the 3.0 version  of the preceding code using the new templates and `app.UseEndpoints(endpoints =>`

```
public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
{
    app.UseRouting();

    app.UseEndpoints(endpoints =>
    {
        endpoints.MapGet("/", async context =>
        {
            await context.Response.WriteAsync("Hello World!");
        });
    });
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9599d917-4e43-f1ae-452a-1f11aaa985ed
* Version Independent ID: 5cc05b6c-c671-3607-3217-7db73ebc1f28
* Content: [ASP.NET Core Performance Best Practices](https://docs.microsoft.com/en-us/aspnet/core/performance/performance-best-practices?view=aspnetcore-3.1&branch=pr-en-us-14734#avoid-using-synchronous-readwrite-overloads-on-httprequestbody-and-httpresponsebody)
* Content Source: [aspnetcore/performance/performance-best-practices.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/performance/performance-best-practices.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-performance**
* GitHub Login: @mjrousos
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@halter73 can you write the 3.0 version of the preceding code?

**Comment by halter73** [comment]
I'm a little confused here. In the first sample, `context.Response.HasStarted` will always be true unless someone replaced the response body stream beforehand, and there's no indication this has happened. The sample would make more sense if the `await context.Response.WriteAsync("Hello ")` was removed. That would at least make it ambiguous whether the response started or not since there's no telling what `next()` might have done.

Since this sample uses `next()` which doesn't really make sense with UseEndpoints since each endpoint is terminal. This means there's no IRouteBuilder methods that give the request handler a `next()` action which is necessary for the sample to make sense.

Instead, I would keep the example as-is for 3.0. I would just put the following between UseRouting() and UseEndpoints():

```c#
    app.Use(async (context, next) =>
    {
        await next();

        if (!context.Response.HasStarted)
        {
            context.Response.Headers["test"] = "test value";
        }
    });
```

**Comment by Rick-Anderson** [comment]
@halter73 thanks, that answers my question.

 Can you take a peek at [same code](https://review.docs.microsoft.com/en-us/aspnet/core/performance/performance-best-practices?view=aspnetcore-3.1&branch=pr-en-us-14734#avoid-adding-headers-after-the-httpresponse-has-started)
in  #14605 
`@davidfowl`  wrote that code.  I think it makes sense in the content.
