### ISSUE TITLE
 Razor file compilation topic updates for 3.0

### ISSUE THREAD

**Issue by lourencocotta** [aspnet/AspNetCore.Docs#14800]
that was work for me:

  services.AddMvc().AddRazorRuntimeCompilation();

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a83deb2-e035-bb66-be4f-68709bcad341
* Version Independent ID: 16438f35-f35d-c097-0903-ec17e83e051e
* Content: [Razor file compilation in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/view-compilation?view=aspnetcore-3.0)
* Content Source: [aspnetcore/mvc/views/view-compilation.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/views/view-compilation.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
*Ah! Perfect.* I was just about to move an issue over to this topic, and your issue here, @lourencocotta, is perfect for it. It pertains to the updates for 3.0.

Looks like some of the [annoucement](https://github.com/aspnet/Announcements/issues/343) made it in for 3.0 (e.g., the package), but not all of that made its way here (e.g., the extension method). It probably happened because the 3.0 updates to the doc occurred during preview before all of the bits were stabilized in engineering for release.

The file provider scenario discussed on https://github.com/aspnet/AspNetCore.Docs/issues/14593 may apply to these doc updates. I haven't really looked in detail, so idk what applies from that discussion.

I'll ping the readers who were on that discussion so that they can track on the updates and discuss it on this issue: @zhou881117, @nexon33, @alexkyse1.

@nexon33 Feel free to state your solution here. You said something about "the above code" solving it with `.AddRazorRuntimeCompilation`. I recommend that you add a comment here with whatever worked.

**Comment by guardrex** [comment]
From @zhou881117 ...

> how to run app-parts  correct  .net core 3.0?
>
> the demo dosen't not work well for .net core 3.0
>
> https://github.com/aspnet/AspNetCore.Docs/tree/5bbb2f5c459cf9bcc1159278a52555cc0f4bb3f6/aspnetcore/mvc/advanced/app-parts

@zhou881117 Good question. I don't know if these are related issues or if that sample breaking is a new issue.

They both pertain to `RazorViewEngineOptions` changes for 3.0. Even if they are not directly related, they might be worked together because they both pertain to the options changes for Razor for 3.0.

I'll let Rick look because this isn't an area that I specialize in or have very good knowledge of. If Rick wants to work them separately, we'll open a new issue for the App Parts problem from the [App Parts](https://docs.microsoft.com/en-us/aspnet/core/mvc/advanced/app-parts) topic. Stand-by.

**Comment by Rick-Anderson** [comment]
See #14960

**Comment by Legends** [comment]
When I start my app using `Strg+F5` and edit a view during runtime, it gets compiled when I hit refresh in the browser.

Don't have to add `.AddRazorRuntimeCompilation();` at all.
Can you elaborate on this?

**Comment by Rick-Anderson** [comment]
> When I start my app using `Strg+F5` (VS2019) 

What's  `Strg`

**Comment by guardrex** [comment]
I think that's German for `Ctrl`.

**Comment by Legends** [comment]
Yeah 'Ctrl' ... sorry.

**Comment by jaredthirsk** [comment]
This worked for me for Razor pages:
services.AddRazorPages().AddRazorRuntimeCompilation();

I wanted to avoid turning on Mvc for now, so I was concerned about adding this Nuget package (Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation) since it had Mvc in the name, but it looks like AddRazorPages is built on Mvc APIs and so this is indeed the package I need.

**Comment by Rick-Anderson** [comment]
This appears to be fixed,
