### ISSUE TITLE
Please write more detail about Authentication, Authorization on Blazor Server web-app (Individual User Accounts)

### ISSUE THREAD

**Issue by donhuvy** [aspnet/AspNetCore.Docs#14843]
Due to the Balazor Server approach/architect is different to 

- ASP.NET Core Razor Page
- ASP.NET Core MVC
- ASP.NET Web Form
- ASP.NET Core WebAPI

therefore development team should write more about Authentication, especially Authorization. How to put authentication tag in Razor component, Razor page?

I spent many days for research about this, and looking for authentication/authorization on Google, GitHub, YouTube, etc. but I still did not implement authorization, authentication (Individual User Accounts)  for my Blazor Server webapp success. If development team has a reference sample web-app, it is very helpful and easy-to-understand.

Thank you very much!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1a9f84a-feaa-d2b0-409a-01f75f9101a0
* Version Independent ID: aeec639f-a9d6-2f00-b61f-2c316ef6afb6
* Content: [Secure ASP.NET Core Blazor Server apps](https://docs.microsoft.com/en-us/aspnet/core/security/blazor/server?view=aspnetcore-3.0)
* Content Source: [aspnetcore/security/blazor/server.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/blazor/server.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by donhuvy** [comment]
After anchor link https://docs.microsoft.com/en-us/aspnet/core/security/blazor/?view=aspnetcore-3.0&tabs=visual-studio#blazor-webassembly-authentication

> Implementation of a custom AuthenticationStateProvider service for **Blazor WebAssembly apps is covered in the following sections.**

// Authentication for Blazor Server content.

These words make me mis-understanding about the content below is for Blazor WebAssembly, not for Blazor Server.

**Comment by guardrex** [comment]
This is going to be covered by one or more other issues. I'm going to probably end up with a tracking issue later. For now, the other issues are ...

* [Social login provider tokens+claims for Blazor auth](https://github.com/aspnet/AspNetCore.Docs/issues/15160)
* [Google Social login provider for Blazor](https://github.com/aspnet/AspNetCore.Docs/issues/15325)
* [Token Based Authorization using IdentityServer with Blazor](https://github.com/aspnet/AspNetCore.Docs/issues/14191)
* [Signalr Context.User missing on hub](https://github.com/aspnet/AspNetCore.Docs/issues/14097)
* [Logout Flow](https://github.com/aspnet/AspNetCore.Docs/issues/13316)
* [Blazor auth topic enhancements](https://github.com/aspnet/AspNetCore.Docs/issues/13022)

Let's close this one since you're asking for general guidance.

> These words maybe make me mis-understanding about the content below is for Blazor WebAssembly, not for Blazor Server.

It just means that a dev should implement a custom `AuthenticationStateProvider` and the rest of the scenarios in the topic should work.
