### ISSUE TITLE
https_port appears to be required in order for redirection and HSTS to work correctly (Core 2.2)

### ISSUE THREAD

**Issue by IanKemp** [aspnet/AspNetCore.Docs#14880]
Our webapp has the standard HTTPS/HSTS configuration:

```csharp
public void Configure(IApplicationBuilder app, IHostingEnvironment env)
{
    if (!env.IsDevelopment())
    {
        app.UseHsts();
    }

    app.UseHttpsRedirection();

    ...
}
```

However, what we've found is that with this configuration, the first time the user hits our site using plain HTTP (insecure), they are not redirected to HTTPS as expected.

After playing around a bit, we found that doing the above **plus the following setting** in `appsettings.json` makes the initial redirect to HTTPS occur as expected:

```json
{
    "https_port": 443
}
```

Is this intentional?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7ddfb2f-5dea-5e31-2a27-02a4dc16104c
* Version Independent ID: 12ca0b9a-2638-a4ce-c45f-d4579c83dafb
* Content: [Enforce HTTPS in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?view=aspnetcore-2.1&tabs=visual-studio#trust-the-aspnet-core-https-development-certificate-on-windows-and-macos)
* Content Source: [aspnetcore/security/enforcing-ssl.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/enforcing-ssl.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Follow the guidance in this section ...

https://docs.microsoft.com/aspnet/core/security/enforcing-ssl#edge-deployments

The app must be able to receive requests on both 80 and 443 for redirection to work.

We can't say more here (in an issue) about **_exactly_** what the setup looks like in a specific case ... that depends on your environment and how the app is deployed (IIS, Kestrel edge, etc.). We don't have the staffing to provide product support. Access the *Host and deploy* docs and reach out to the devs on a support forum, such as Stack Overflow, or a support chat, such as Slack or Gitter ...

* [ASP.NET Core Slack Team Room](http://tattoocoder.com/aspnet-slack-sign-up/)
* [ASP.NET Gitter](https://gitter.im/aspnet/Home)

... in the end tho ... the basic idea is that however you host the app, it must be able to receive and process requests on both ports in order to perform the redirection and then respond on the secure port.

**Comment by guardrex** [comment]
btw --- what you called out is covered ... see :point_right: https://docs.microsoft.com/aspnet/core/security/enforcing-ssl#port-configuration

**Comment by IanKemp** [comment]
I guess my question was pretty unclear, here's what I actually wanted to ask:

* Why is it necessary to explicitly set the `https_port` configuration value to 443, when the default HTTPS port number is 443 anyway?

**Comment by guardrex** [comment]
That's not a default ... 5001 is the default for HTTPS and only for the Development environment. HTTPS for the Production environment must always be configured.

**Comment by shoe788** [comment]
The docs say 443 is the default

https://docs.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?view=aspnetcore-2.2&tabs=visual-studio#options

>The default value is 443.

**Comment by guardrex** [comment]
Thanks @shoe788 ... that line isn't accurate. The *Port configuration* section is ok, but that line didn't get addressed the last time the *Port configuration* section was updated. I'll open a new issue to have that line addressed. Thanks for calling it out.
