### ISSUE TITLE
Unclear: volume data store and value data store

### ISSUE THREAD

**Issue by Legends** [aspnet/AspNetCore.Docs#14896]
_In production, send Trace through Information level to a volume data store. 
Send Warning through Critical to a value data store._

What is a volume data store and what is a value data store?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7184a308-a254-9350-a5cd-5bced1f369ae
* Version Independent ID: 726e3bf1-f367-d733-8933-bccc04da0e16
* Content: [Logging in .NET Core and ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-3.0#add-providers)
* Content Source: [aspnetcore/fundamentals/logging/index.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/logging/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @tdykstra
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
An ancient text update to this content didn't go well, and we've all probably looked right at that and missed it on successive updates ... thanks for calling it out.

"Volume data store" is supposed to mean "high-volume data store" (see https://github.com/aspnet/AspNetCore.Docs/commit/5362a8dca5b600b50ddb71a9382bc4f41ea9f3e5#diff-0a2f90a81fb4f1f2c8931b1681f84cebR139)&dagger; ... i.e., an expensive data store that can store *a lot of information fast* and as opposed to the "value data store," which really should say "high-value (i.e., **lost cost but slower**) data store."&Dagger; The updates were blown. *Yikes!* :smile:

&dagger;The original text wasn't correct in a different aspect, too, since "higher" (directional terms) seem to be used to represent logging levels running in opposite directions.
&Dagger;Even so, I'll need to make some adjustments to the language to make that clearer.

**Comment by Legends** [comment]
Perhaps supply some examples for each to make it crystal clear :-)
You see, I am making my way through the docs, we'll stay in contact :D ;-)

**Comment by guardrex** [comment]
No worries ... I'll fix it up. I agree, and it shouldn't go back to just "high-volume" and "high-value" ... that's also (all by itself) confusing. The author tried to fix it, and it just didn't work out. What's annoying is that we've all probably read past that a few times over the last few years (that change was *2016!!!*) and didn't spot it.
