### ISSUE TITLE
Without change numTimes to ID,  the request still match the id route parameters 

### ISSUE THREAD

**Issue by TangMonk** [aspnet/AspNetCore.Docs#15211]
```
public string Welcome(string name, int numTimes = 1)
        {
            return HtmlEncoder.Default.Encode($"hello {name}, Numtime is {numTimes}");
        }
```

request url is :
```
https://localhost:5001/Home/Welcome/1?name=asd
```

response is:

```
hello asd, Numtime is 1
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 20264150-9ac7-2b21-3314-64ffa114410f
* Version Independent ID: 3477519b-1bc2-73be-33e3-63067383d426
* Content: [Add a controller to an ASP.NET Core MVC app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/adding-controller?view=aspnetcore-3.0&tabs=visual-studio-code)
* Content Source: [aspnetcore/tutorials/first-mvc-app/adding-controller.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-mvc-app/adding-controller.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by serpent5** [comment]
This is the correct behaviour. The default MVC route is `{controller=Home}/{action=Index}/{id?}`, which means `Home/Welcome/1` is a valid match for the action shown. If you try it with `Home/Welcome/2`, you'll see that `numTimes` is still `1` because a value for `numTimes` wasn't specified in the URL. A value was specified for `id` (`2`), but it's unused in the action.
