### ISSUE TITLE
Add information about when net core 3.0 might be supported

### ISSUE THREAD

**Issue by sander1095** [aspnet/AspNetCore.Docs#15228]
Right now it says "We hope to make this available soon" which is not enough for me. Giving us an indication will be helpful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76f39eec-9dd1-6167-56ec-47b26e0b5063
* Version Independent ID: f9f2b0f3-01eb-cf58-8767-194fe0fc0e44
* Content: [Migrate from ASP.NET Core 2.2 to 3.0](https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.0&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/migration/22-to-30.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/migration/22-to-30.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-migration**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
At the time of writing, it wasn't known.

Currently, the runtime and shared framework should be there. The SDK rollout is in progress.

https://aspnetcoreon.azurewebsites.net/

I'll add that site to that section.

**Comment by sander1095** [comment]
This might be offtopic but I hope you can still answer my question.

I want to create a new ASP.NET Core 3.0 project. I want to build and release it in Azure Pipelines using a self-hosted agent that has .NET Core 3.0 agent installed. 

I will release it to an app service hosted in Azure.

Do I understand it correctly when I say that Azure has no support yet for hosting an ASP.NET 3.0 app yet and that your link shows me the progress of this step? I have read about creating a standalone app or using a docker image but I'd rather wait for it to be actually supported fully instead of using workarounds.


Also, if im right, is there an indication _somewhere_ that will tell me more  about the possible release date of normal .NET COre 3.0 support in app service?


Thanks!

**Comment by guardrex** [comment]
@sander1095 My understanding is that if you go the self-hosted agent route, you can configure to use the 3.0 SDK. If you need to use their hosted agents, then you have to wait on the full rollout ... until they get the SDK rolled out.

You're correct in checking their docs and asking them for more coverage if they don't make it clear. I see a bullet that pertains to this ...

> After a new version of the .NET Core SDK is released, it can take a few weeks for us to roll it out to all the datacenters that Azure Pipelines runs on. You don't have to wait for us to finish this rollout. You can use the .NET Core Tool Installer, as explained in this guidance, to install the desired version of the .NET Core SDK on Microsoft-hosted agents.

https://docs.microsoft.com/azure/devops/pipelines/ecosystems/dotnet-core#troubleshooting

> no support yet for hosting an ASP.NET 3.0 app

The runime and the shared framework for 3.0 are there, so you **_can host_** a 3.0 app on App Service. Without the SDK, you **_can't build_** right now (e.g., Kudu). Since the SDK isn't there, that's probably related to why their build agents also aren't available yet for Azure Pipelines (the agents that they offer).

Regarding the website, *yes* ... that's official. Keep an :eye: on that.
