### ISSUE TITLE
Lost

### ISSUE THREAD

**Issue by PaulCr125** [aspnet/AspNetCore.Docs#15251]
I'm just trying to begin learning MVC and the 1st how to I try doesn't work. You can't imagine how frustrating this is. Shouldn't this  be tested? This is beginners page, where else could I start?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 20264150-9ac7-2b21-3314-64ffa114410f
* Version Independent ID: 3477519b-1bc2-73be-33e3-63067383d426
* Content: [Add a controller to an ASP.NET Core MVC app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/adding-controller?view=aspnetcore-3.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-mvc-app/adding-controller.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-mvc-app/adding-controller.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
The tutorial works. I'm not sure what step you missed. You might try asking on StackOverflow,.

**Comment by baktay** [comment]
Is this tutorial for VS2019 Ver.16.3.9 ? I feel like its for an earlier version because you will get stuck when trying to add controller.

When you start the project there is already a HomeController.cs with views. The scaffolding gives error if you try to add controller as shown in tutorial. 

If you try to add it manually (add / controller class / rename to HelloWorldController.cs) then it seems to clash with the existing HomeController.cs. At least this is what I think.

This put me off as well. This is no beginning tutorial. You get puzzled off the bat!

If different versions of Visual Studio behave differently they should mention what version to use, or create a tutorial for each version (different versions may prepare different files for selected project template).
