### ISSUE TITLE
Running command line to install Blazor Templates does not get them to show in Visual Studio

### ISSUE THREAD

**Issue by DanJ210** [aspnet/AspNetCore.Docs#15280]
Under step three for Visual Studio there's a note that states you can remove the extension which I never did install, but you can remove it because the command will cause the templates to show up when creating a new project. This is not true for me. I can create the Blazor templates in the command line but nothing has changed in Visual Studio. Even after computer restart.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c07e57dc-526f-9479-4695-de7d8f06eb9a
* Version Independent ID: 8226ed72-69b2-3c93-a931-218bd11cf9c8
* Content: [Get started with ASP.NET Core Blazor](https://docs.microsoft.com/en-us/aspnet/core/blazor/get-started?view=aspnetcore-3.0&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/blazor/get-started.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/get-started.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
I don't have any new info on this from engineering. Note that you do need 16.4 Preview 2 for Blazor WebAssembly development at this time and that you may need to run the template install command again after updating (or installing) VS Preview. 

The process you see in the topic today was approved by engineering. If you're having trouble with getting the WebAssembly templates to show up in VS, open an issue over on the engineering repo. If they determine that we need to make changes here, we can re-open this issue to do so.

https://github.com/aspnet/AspNetCore/issues

Feel free to add a "cc: @guardrex" to the bottom of your issue so that I can track the discussion.

**Comment by DanJ210** [comment]
@guardrex Just so I know I'm doing the right thing. Visual Studio 2019 16.3.8 won't work, I'd have to download a non RC preview version 16.4 Preview 2?

Would that warrant clarifying in docs or is the user supposed to deduce that?

**Comment by guardrex** [comment]
@DanJ210 Quick note on adding comments to closed issues and PRs: It's best to open a new issue using the **This Page** feedback button/form at the bottom of any topic. It adds the topic metadata, pings the author automatically (me! lol), and helps to track work volume a little better.

> won't work

... isn't specific/actionable. Always state *exactly* what the behavior is.

The guidance from engineering is ...

> 1. Install the latest Visual Studio with the ASP.NET and web development workload.
>
> 2. Optionally install Visual Studio 16.4 Preview 2 or later with the ASP.NET and web development workload for Blazor WebAssembly app development.

Your 16.3.8 *should work* for Blazor Server apps. Go with 16.4 Preview 3 (just released) for Blazor WebAssembly development.

If you're having trouble with VS following the guidance, use the **Report a problem** process from within VS or open an issue on the engineering repo because we can't troubleshoot product issues or provide much support here on the docs repo 🏃🏃😅.

**Comment by guardrex** [comment]
I'll hold this open for a bit so that you can add the "won't work" behavior. If it sounds like a purely doc issue, then we can leave this for triage here. I have a feeling tho that it's going to be a product issue. What exactly isn't working with 16.3.8 for Blazor Server?

**Comment by adudsic** [comment]
I had the same issue. Instructions here resolved it: http://blazor-university.com/overview/installing-blazor/

**Comment by guardrex** [comment]
We don't have any further guidance from engineering at this point for our installation instructions. It will surely be nice when Blazor WebAssembly gets out of preview ... I think some of these types of issues will melt away when that happens (e.g., I've had to re-install the templates after a VS upgrade).

**Comment by riverar** [comment]
Having the same issue, despite having met all the prerequisites. Will punt this into the MVP alias. cc: @guardrex
