### ISSUE TITLE
Add an example for providing a pre-built configuration to Host

### ISSUE THREAD

**Issue by UncleDave** [aspnet/AspNetCore.Docs#15370]
As far as I can tell there is currently no example which shows how to:

1. Clear out the default configuration sources added by `CreateDefaultBuilder`.
2. Add a pre-built `IConfiguration` via `AddConfiguration`.

As raised in [this StackOverflow question](https://stackoverflow.com/questions/58530942/how-to-read-configuration-settings-before-initializing-a-host-in-asp-net-core/58594026).

If this is something that would be beneficial to the docs I'd be happy to open a PR.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0eb4d762-3910-2c57-8741-3306c15537b6
* Version Independent ID: ba2254a0-ea8e-9b28-e94b-edd0fc58c043
* Content: [Configuration in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/fundamentals/configuration/index.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/configuration/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @UncleDave ... Thanks for the comment, but we're not leaning in that direction (i.e., showing *every* way to handle configuration. We are being a little bit *opinionated* about what's shown, especially for the goal of not overloading new devs and devs new to ASP.NET Core. Let's take those separately ...

### Clear providers

Devs can just clear them. Otherwise, devs build their own host and just don't call `CreateDefaultBuilder`. Of course, the dev can just ignore them (i.e., if they aren't using settings files ... it just no-ops on settings files; not using command-line args ... again ... no-ops; not using Secret Manager ... no-ops; etc.). These are fairly straightforward approaches.

```csharp
.ConfigureAppConfiguration((hostingContext, config) =>
{
    config.Sources.Clear();
    // New config providers here
})
```

The main pattern recommended by engineering is shown in the host and config topics. We'll probably let more advanced devs work on more advanced/different patterns on their own. Given the no-op behavior of the config providers with `CreateDefaultBuilder`, I don't see much value but do see some significant downside in an already *looooong* topic with a lot of content. Explain in more detail *why* you think it would important to add the coverage.

### Pre-built config

We had something like that ... sort of like that ... for the Web Host.

https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/web-host?view=aspnetcore-3.0#override-configuration

... so only the *concept* is similar going forward with the Generic Host. I really think `ConfigureAppConfiguration` is a much better pattern to adopt.

In ...

```csharp
.ConfigureAppConfiguration((hostingContext, config) => { ... })
```

`config` is an `IConfigurationBuilder`, and that can be created anywhere and just assigned. I don't think that it's difficult to work out. I think that only a tiny fraction of devs would build config that way. The ones who do probably are proficient devs and know how to take care of it. Again, provide more detail on *why*/*how* this would help in the context of a long, detailed topic.

**Comment by UncleDave** [comment]
Hi @guardrex, thanks for the response.

With regards to clearing the default providers my main argument is that if the docs are explaining that `CreateDefaultBuilder` will add some default providers then it should also explain how to remove those if they're not desirable. I agree with you on no-ops, it's definitely trivial to leave the defaults alone and just override if needs be, but regardless I think some individuals will prefer to explicitly add sources and have full control. As for the increased length of the document your code example is actually exactly what I would have proposed, for a change of +10 lines when header and one line explanation is included.

On the general topic of document length, for what it's worth, I wouldn't consider it a valid argument for not adding more content. I agree that content must be relevant and you can't document every single use case under the sun, but if I'm visiting the docs page I won't be sitting down to read the whole thing from top to bottom - I'll be clicking on a sub-header and going to a specific section to look something up, in which case I'd much rather the docs be comprehensive than short.

I think these additions would help with what I believe is a pretty common use case: configuring something (most likely logging) before creating the host, then reusing the same config values without building another `IConfiguration`.

> `config` is an `IConfigurationBuilder`, and that can be created anywhere and just assigned.

Could you clarify what you mean here? Are you saying an `IConfigurationBuilder` can be assigned to the `config` argument like so?

```
.ConfigureAppConfiguration((hostingContext, config) =>
{
    config = myConfigBuilder;
})
```

I'm sure I've misunderstood because I don't think that's possible.

If you'd like I can show you my proposed changes and you can decide specifically if they'd be valuable or not.

**Comment by guardrex** [comment]
... and I'm thinking about your remark on the SO post about logging for startup ...

https://docs.microsoft.com/en-us/aspnet/core/fundamentals/error-handling?view=aspnetcore-3.0#startup-exception-handling

... but cross-links to the Web Host topic.

**Comment by UncleDave** [comment]
I understand what you're saying about length of the article, and I agree that maybe the 2nd suggestion does not belong in the _Fundamentals_ node and would be happier in the _advanced_ node you mentioned. I do have further thoughts on the subject, but maybe given that we're talking about changes to the _Fundamentals_ node it would be more appropriate to discuss them in another issue and focus on the "source clearing" subject here as we seem to be on the same page with it.

> A sentence explaining that the providers can be cleared/replaced ... and then something like ...

Yeah your snippet is pretty much verbatim what I'm suggesting, actually the only difference is my comment has slightly different wording but that's neither here nor there.

> I take it that you're suggesting this for the bottom of the Default configuration section?

I was actually going to put it under _ConfigureAppConfiguration_ but it seems like it would fit in either section, maybe more appropriate in the section you suggested but I'll defer to you on that.

My full suggestion was this:

---

### Remove default providers

To remove the providers added by `CreateDefaultBuilder`, call `Sources.Clear()` first:

```csharp
.ConfigureAppConfiguration((hostingContext, config) =>
{
    config.Sources.Clear();
    // Add providers here
})
```

**Comment by guardrex** [comment]
... and I'll just throw this out there. It's also possible for it to go ...

```csharp
.ConfigureHostConfiguration(config =>
{
    config.Sources.Clear();
    // Add providers here
})
.ConfigureAppConfiguration((hostingContext, config) =>
{
    config.Sources.Clear();
    // Add providers here
})
```

... but that is also fairly obvious. Since the host is only configured with `DOTNET_` prefixed env vars and command-line args, it's probably not the main thing on a dev's mind. It's app config ... that's probably the main use case.

**Comment by guardrex** [comment]
Yes ... in the Generic Host topic showing a manually built host that doesn't call `CreateDefaultBuilder` and applies a config ... just spit ball'in here 🤔 ... perhaps it fits well in the *Host configuration* section under the current content of that section. Something like .......

```csharp
public static void Main(string[] args)
{
    var builtConfig = new ConfigurationBuilder()
        .SetBasePath(System.IO.Directory.GetCurrentDirectory())
        .AddJsonFile("hosting.json", optional: true)
        .AddCommandLine(args)
        .Build();

    var host = new HostBuilder();
        .ConfigureHostConfiguration(config =>
        {
            config.AddConfiguration(builtConfig);
        })
        .Build();

    host.Start();
}
```

... I really have a feeling that engineering is going to say why not just place that directly in the `ConfigureHostConfiguration` ...

```csharp
public static void Main(string[] args)
{
    var host = new HostBuilder();
        .ConfigureHostConfiguration(config =>
        {
            config.SetBasePath(System.IO.Directory.GetCurrentDirectory());
            config.AddJsonFile("hosting.json", optional: true);
            config.AddCommandLine(args);
        })
        .Build();

    host.Start();
}
```

Seems like a solution **_in search of a problem!_** :smile: lol

**Comment by UncleDave** [comment]
I think we got our wires crossed a little bit discussing this, when I said the following:

> configuring something (most likely logging) before creating the host

I meant for the purpose of logging errors in `Build()`, but that's not really the important part. My intent there was to show a real world example of building a config before the host, then reusing the same config instead of having the host build a whole new one from the same providers.

I've created a repo that will hopefully explain better than my word salad.

https://github.com/UncleDave/DotNetCorePreBuiltConfigExample

The point is I'm reusing the same config, I can think of at least one other use case besides logging startup errors. I'm not saying the docs need an example that says "Hey if you want to catch errors from `Build()` use a `try-catch` ya dingus", just that there are legitimate examples of building the config before the host, and if I was to do that I'd want to reuse the same config.

I definitely wouldn't call this a fundamental though, so it would probably fit better in the previously mentioned _advanced_ section, I just wanted to clear up what I'm proposing here.

**Comment by guardrex** [comment]
@Tratcher TL;DR ... Would you put a quick :eye: on [this startup 3rd party logging pattern (UncleDave/DotNetCorePreBuiltConfigExample GH repo)](https://github.com/UncleDave/DotNetCorePreBuiltConfigExample/blob/master/PreBuiltConfigExample.Logging.Loud/Program.cs) and determine if you would like the pattern covered in the docs? **_Too advanced/edgy or good to show?_**

**Comment by Tratcher** [comment]
We'll probably need coverage for an advanced logging setup scenario like that. A lot of people are asking how to log in ConfigureServices, which isn't directly supported in 3.0.
https://github.com/aspnet/AspNetCore/issues/9337
