### ISSUE TITLE
How do I use Azure AD B2C authentication with a client-side Blazor app?

### ISSUE THREAD

**Issue by Frakur** [aspnet/AspNetCore.Docs#15386]
When I add a new server-side Blazor project I get the option to add authentication, which lets me enter all my B2C tenant details and then authentication just works. But in a client-side app that is disabled, and it [looks like](https://github.com/aspnet/AspNetCore/issues/10846) it won't be enabled until the .NET 5 preview at least.

It's really unclear how I would go about adding this manually into my client-side Blazor app. I know I can't just copy the equivalent server-side code, since a client-side app would require implicit flow. This doc talks about implementing the custom AuthenticationStateProvider but not how to use the framework to actually do the authentication and get the user's claims.

Could the doc be updated with guidance for some more specific scenarios such as this one? Or is there another doc elsewhere which could help? Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9942b0a-a7fb-0d34-9201-af0963affa9e
* Version Independent ID: 19770710-5225-a1ea-e082-65da6ba4a49a
* Content: [ASP.NET Core Blazor authentication and authorization](https://docs.microsoft.com/en-us/aspnet/core/security/blazor/?view=aspnetcore-3.0&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/security/blazor/index.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/blazor/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @Frakur ... It's under investigation and discussion. There are some approaches (hacks) that you can take until engineering works it forward. See :point_right: https://github.com/aspnet/AspNetCore.Docs/issues/15160#issuecomment-544272193 ... closing this as a duplicate of that issue.

**Comment by Frakur** [comment]
Hi @guardrex. Maybe I'm misunderstanding but I don't think that's the same as what I'm asking. Your linked issue is about a server-side Blazor app, whereas I'm asking about a client-side (WebAssembly) Blazor app. I'm also not trying to use external social identity providers, I'm using my own Azure AD B2C tenant for authentication. I can already implement all this in server-side Blazor as it's completely built in to the framework (as well as being included as an option in the `blazorserver` template).

I believe the framework should support this for client-side Blazor, but presumably with some tweaks to use the implicit flow recommended for SPAs rather than the authorisation code flow used for server-based applications. That's the bit I'm not sure about.

I'm far from an expert on this stuff so maybe I've got some of this wrong, hopefully you can clarify for me. Thanks.

**Comment by guardrex** [comment]
We have no guidance for Blazor WebAssembly from engineering yet. I was just referring to that issue because that (and in one or a few engineering issues) it's **_in-design_** and a workaround/hack of some sort might make its way into the docs soon.

They tend to address *both* Blazor Server and WebAssembly when they design framework scenarios for Blazor, so you can keep an eye on the docs issue and provide feedback to them on engineering issues WRT to the design aspects. They will work it from the engineering issue ... not the docs one. 

We'll just keep the docs issue open for now because they may say "OK" to a workaround approach for the time being. If I get a workaround ... whatever it is ... I'll use that issue to get it into the docs. There will be a new doc issue for the final design when it releases ... 3.1? 5.0? ... not sure when ... but we'll have a new docs issue to cover the released design later. It's also possible that they say "NO" to any kind of workaround/hack at this time. We'll see what they say.

For now, do the following:

* :ear: for their remarks.
* Provide feedback to them (on engineering issues, not the docs one unless you want to talk about how to cover workarounds/hacks temporarily).
* Talk to devs on support forums, such as Stack Overflow, and support chats, such as Slack and Gitter:
  * [Slack](http://tattoocoder.com/aspnet-slack-sign-up/)
  * [Gitter: Blazor](https://gitter.im/aspnet/Blazor)
