### ISSUE TITLE
traffic and bounce rate of aspnet framework doc

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/AspNetCore.Docs#15418]
Get the bounce rate of https://docs.microsoft.com/en-us/aspnet/web-api/overview/testing-and-debugging/troubleshooting-http-405-errors-after-publishing-web-api-applications

I assume it's very high because it's click bait for Web API HTTP 405 errors - not the limited problem the doc describes (deploy to IIS is the cause).

Report results here and close issue.

related [internal issue](https://dev.azure.com/mseng/TechnicalContent/_workitems/edit/1617782)
related [internal issue2](https://dev.azure.com/mseng/TechnicalContent/_workitems/edit/1617784)

**Comment by wadepickett** [comment]
@Rick-Anderson , I know you don't need this yet, but I was blocked on other work for 5 min so I'll do this since it is quick.

**For September** 
Bounce: 12.33%  
Click Through 4.14%
83.87% of audience arrives through organic search.

I'll provide a report by email of details for the topic plus a summary on customer comments.  It seems to break down roughly into two major categories for folks that are unhappy:  
1. Non-developers who have no idea why they saw the error on a page they were browsing to and are looking for a clue to what it all means.
2. Developers who want to get right to fix instruction or at least right to definitive troubleshooting steps.

**Comment by wadepickett** [comment]
Reports sent.  Closing.
