### ISSUE TITLE
HttpMethodAttribute doesn't implement IActionConstraint

### ISSUE THREAD

**Issue by miloszkukla** [aspnet/AspNetCore.Docs#15463]
Section https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/routing?view=aspnetcore-3.1#understanding-iactionconstraint claims that "The [HttpGet] Attribute and similar [Http-VERB] attributes implement IActionConstraint" while looking at the HttpGet/HttMethodAttribute docs/source doesn't confirm that.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ee6ad2f-1667-8d5c-1f36-9d0511e3720f
* Version Independent ID: 7838ccec-c8e8-9baa-2b3e-220b2af5fc58
* Content: [Routing to controller actions in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/routing?view=aspnetcore-3.1#understanding-iactionconstraint)
* Content Source: [aspnetcore/mvc/controllers/routing.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/controllers/routing.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Per the article:

The simplest way to implement an `IActionConstraint` is to create a class derived from `System.Attribute` and place it on your actions and controllers. MVC will automatically discover any `IActionConstraint` that are applied as attributes.

**Comment by Rick-Anderson** [comment]
@serpent5  please comment.

**Comment by serpent5** [comment]
That's correct. These attributes _don't_ implement `IActionConstraint`. They (indirectly) implement `IActionHttpMethodProvider`, which gets mapped over to an implementation of `IActionConstraint` ([`HttpMethodActionConstraint`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.actionconstraints.httpmethodactionconstraint?view=aspnetcore-3.0)) when the [app model](https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/application-model?view=aspnetcore-3.0) is built.

I think that describing `IActionConstraint` in the context of these attributes is no longer a good example since the introduction of endpoint routing, which doesn't use `IActionConstraint` in the same way as the "legacy `IRouter` support" does. I think this is something that should be addressed as part of #13871.

**Comment by Rick-Anderson** [comment]
Moved to #13871
