### ISSUE TITLE
.FirstOrDefaultAsync()  V.S.  .FindAsync() for Details action method

### ISSUE THREAD

**Issue by ExploreNcrack** [aspnet/AspNetCore.Docs#15498]
Hi. I am wondering why using .FirstOrDefaultAsync() instead of .FindAsync() in the Details action method and Delete action method?  Isn't the .FindAsync() supposed to be faster than .FirstOrDefaultAsync()? Or are they the same in this case?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97234f18-4009-0ebf-a379-9b63125529cd
* Version Independent ID: 1bf4792d-dab4-e03d-2021-3dcdcaff6a0f
* Content: [Examine the Details and Delete methods of an ASP.NET Core app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/details?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/tutorials/first-mvc-app/details.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-mvc-app/details.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
See the https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/intro?view=aspnetcore-3.0&tabs=visual-studio for details.

**Comment by ExploreNcrack** [comment]
So using .FirstOrDefaultAsync() in the Detail and Delete Get is because .FirstOrDefaultAsync() is guaranteed to be sent over to the database to check if they exist in the database? But .FindAsync() would check the tracked entity in context first?

**Comment by ExploreNcrack** [comment]
So "FirstOrDefaultAsync has been replaced with FindAsync. When you don't have to include related data, FindAsync is more efficient." But in the example, there is no include related data, why not use FindAsync() for all ?

**Comment by ExploreNcrack** [comment]
And also are there any side effect by using `.Find()` method instead of `.FirstOrDefault()` for the CRUD operations?

**Comment by fayeBabacar78** [comment]
**FirstOrDefaultAsync** returns null if nothing is found; otherwise, it returns the first row found that satisfies the query filter criteria. FirstOrDefaultAsync is generally a better choice than the following alternatives:

**SingleOrDefaultAsync** - Throws an exception if there's more than one entity that satisfies the query filter. To determine if more than one row could be returned by the query, SingleOrDefaultAsync tries to fetch multiple rows. This extra work is unnecessary if the query can only return one entity, as when it searches on a unique key.

**FindAsync** - Finds an entity with the primary key (PK). If an entity with the PK is being tracked by the context, it's returned without a request to the database. This method is optimized to look up a single entity, but you can't call Include with FindAsync. So if related data is needed, FirstOrDefaultAsync is the better choice.

[](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/crud?view=aspnetcore-6.0)
