### ISSUE TITLE
Replacement for WebGrid editing?

### ISSUE THREAD

**Issue by tony-long** [aspnet/AspNetCore.Docs#15526]
We need a replacement to MVC4/5 WebGrid used for inline record editing.   Can you provide more doc info and sample app using a master-detail viewmodel with the detail records as webgrid type of inline editing?   Can Blazor provide this? When?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eef47457-c8cf-74a4-b884-c1fe5c2ef52d
* Version Independent ID: 09a02d10-2834-467d-d8c2-3fd19ceb3863
* Content: [ASP.NET Core Blazor forms and validation](https://docs.microsoft.com/en-us/aspnet/core/blazor/forms-validation?view=aspnetcore-3.0)
* Content Source: [aspnetcore/blazor/forms-validation.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/forms-validation.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @tony-long ... We don't have a similar control in the docs. I doubt that we have the staffing to produce one for the foreseeable future due to many high priority issues and a large backlog of work (see the issue count on this repo). We recommend that you check the Internet for blogs and discuss it with devs on a support chat, such as Stack Overflow, or support chat, such as Slack or Gitter.
