### ISSUE TITLE
Show how to test authentication/authorization using claims

### ISSUE THREAD

**Issue by jelster** [aspnet/AspNetCore.Docs#15653]
Opening new Issue for @guardrex [request](https://github.com/aspnet/AspNetCore.Docs/issues/6882#issuecomment-551893172). 

Although the sample does discuss how to use a mock authentication handler for authentication, I feel it would be helpful to go a bit further and discuss how to use the same for testing claims-based authentication and authorization to resources. 

In [this](https://github.com/aspnet/AspNetCore.Docs/issues/6882#issuecomment-452450469) comment I discuss how this might be approached in [gist form](https://gist.github.com/jelster/6b850d567acef343e59fad70cb20455a) - the `TestAuthenticationOptions` are used to define the specifics of the claims involved, which can be overridden by tests that need to do so. The actual tests are set up in the `ClaimsTests`, but it appears I left the actual assertions as an exercise for the reader, which I'm happy to undertake if it will prove useful.

HTH

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77889d43-fedb-f8b4-8fea-379ec946555c
* Version Independent ID: f499b131-8b14-7e10-1728-543fdd5a5656
* Content: [Integration tests in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-2.1#client-options-1)
* Content Source: [aspnetcore/test/integration-tests.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/test/integration-tests.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-test**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
I've placed this on the Testing docs project for triage. AFAIK at this point, engineering is happy with what's shown, namely setting claims in `HandleAuthenticateAsync`. When they see this, they'll take a look at your approach.

If you want to take that gist down but leave it available, please feel free to cut-'n-paste those code blocks into a comment on this issue. If you want to just leave that up and leave your gist cross-linked here, that's ok, too. Note tho that it might take a long time for engineering to get to this issue ... several months possibly. You might need to leave the gist up for a rather long time if that's ok.

**Comment by jelster** [comment]
I've got no problem leaving the gist up, but here's some snippets that might provide a more cohesive context to what I'm proposing. In the current docs, `HandleAuthenticateAsync` just new-ups an empty set of claims that it uses to construct the auth ticket via the Claims Principal via the Claims Identity, etc. This limits the ability to prove out claims-specific logic that's really crucial, like say, validating that a multi-tenanted application doesn't inadvertently leak access or other such isolation concerns across tenant boundaries. 

What I propose is to subclass the `AuthenticationSchemeOptions` so that we can provide a nicely encapsulated factory for issuing a default set of claims consistent across the test suite. By leveraging the polymorphic nature of how the auth handler pipelines operate in conjunction with the test setup, we can allow individual test fixtures to specify their own sets of claims they're interested in having the test auth middleware populate. Classic inversion of control, if you squint hard enough I suppose :smile: 

Here's what that `TestAuthenticationOptions` subclass looks like. Note the set of basic claim types being populated with test data similar to what you might receive from AAD. 

    public class TestAuthenticationOptions : AuthenticationSchemeOptions
    {
        // ...
        // customize as needed
        public virtual ClaimsIdentity Identity { get; set; } = new ClaimsIdentity(
            new Claim[]
                {
                new Claim("http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier", Guid.NewGuid().ToString()),
                new Claim("http://schemas.microsoft.com/identity/claims/tenantid", "test"),
                new Claim("http://schemas.microsoft.com/identity/claims/objectidentifier", Guid.NewGuid().ToString()),
                new Claim("http://schemas.xmlsoap.org/ws/2005/05/identity/claims/givenname", "test"),
                new Claim("http://schemas.xmlsoap.org/ws/2005/05/identity/claims/surname", "test"),
                new Claim("http://schemas.xmlsoap.org/ws/2005/05/identity/claims/upn", "test"),
                },
            "test");
    // ...

Test fixtures can override these options by passing an array of claims into the `AddTestAuthentication` extension:

  ```
 public ClaimsTests(TestWebApplicationFactory<MyWebApi.Startup> factory)
        {
            _factory = factory;
            _factory = _factory.WithWebHostBuilder(builder =>
            {
                builder.ConfigureServices(services =>
                {
                    services.AddAuthentication(o =>
                    {
                        o.DefaultScheme = "TestAuthenticationScheme";
                    })
                    .AddTestAuthentication("TestAuthenticationScheme", "Test Auth", o =>
                    {
                        o.Identity = new ClaimsIdentity( /* pass in a Claim[] */);
                    });
                });
            });      
```

HTH

**Comment by dhhunter** [comment]
Thanks @jelster for your excellent contribution, you have really helped me.  

When paired with the suggested method of setting up the EfCoreInMemory Database, I noticed two issues with this approach:
1) The Database has to be Setup, and Seeded Twice for every Integration Test.  Once when the Factory is passed into the Constructor and then a second time to create the customized factory that uses the ClaimsIdentity under test, this generally makes an already slow test even more excruciatingly slow.
2) This is a generalized issue with EfCore and Testing (that is made a lot worse due to having to create the InMemory Database twice for every Integration Test).  You VERY quickly run into problems with ManyServiceProvidersCreatedWarning's.  While it is possible to setup EntityFramework to ignore this particular error, I would much rather not having smelly code all over the place to begin with.

Thank you very much and have a very Blessed Day!

**Comment by jelster** [comment]
Hi @dhhunter - 
> a second time to create the customized factory that uses the ClaimsIdentity under test

I don't see why that should be necessary. Can you expand on that? 

The second item you raise may have a similar root relationship with the first; noting that while I'm not familiar with the ManyServiceProvidersCreatedWarning, it might imply inconsistent or incorrect service registrations -- if a service intended to be a singleton is registered instead as a per-instance could that cause this warning?

**Comment by dhhunter** [comment]
@jelster I was really frustrated and had a massive migraine when I wrote my last response; hopefully, I will be able to explain a little better this time.  Thanks for getting back to me!

The documentation has the InMemory Database Creation\Seeding being done in the ConfigureWebHost override of the WebApplicationFactory.  So that it gets automatically setup every time the WebApplicationFactory is created.  This is very convenient in simple scenarios; however, in our more complex authentication testing scenarios it is very inefficient (since most of the time the ready to go WebApplicationFactory that gets injected into our Test Class is basically thrown away after we use it to create a new more customized one.

`
public class CustomWebApplicationFactory<TStartup>
    : WebApplicationFactory<TStartup> where TStartup: class
{
    protected override void ConfigureWebHost(IWebHostBuilder builder)
    {
        builder.ConfigureServices(services =>
        {
            // Remove the app's ApplicationDbContext registration.
            var descriptor = services.SingleOrDefault(
                d => d.ServiceType ==
                    typeof(DbContextOptions<ApplicationDbContext>));

            if (descriptor != null)
            {
                services.Remove(descriptor);
            }

            // Add ApplicationDbContext using an in-memory database for testing.
            services.AddDbContext<ApplicationDbContext>(options =>
            {
                options.UseInMemoryDatabase("InMemoryDbForTesting");
            });

            // Build the service provider.
            var sp = services.BuildServiceProvider();

            // Create a scope to obtain a reference to the database
            // context (ApplicationDbContext).
            using (var scope = sp.CreateScope())
            {
                var scopedServices = scope.ServiceProvider;
                var db = scopedServices.GetRequiredService<ApplicationDbContext>();
                var logger = scopedServices
                    .GetRequiredService<ILogger<CustomWebApplicationFactory<TStartup>>>();

                // Ensure the database is created.
                db.Database.EnsureCreated();

                try
                {
                    // Seed the database with test data.
                    Utilities.InitializeDbForTests(db);
                }
                catch (Exception ex)
                {
                    logger.LogError(ex, "An error occurred seeding the " +
                        "database with test messages. Error: {Message}", ex.Message);
                }
            }
        });
    }
}
`

I ended up refactoring the ConfigureWebHost method and moving the Db Seeding code into a public static method on the WebApplicationFactory that does not automatically get called.  This way I can put off that step until I manually create the custom WebAppicationFactory in my Test Class.  While I do not feel this is an ideal solution, it is the best I have come up with so far.  In simple scenarios, I miss the convenience of having a fully ready to go WebApplicationFactory being injected into my test class; however, the more explicit control is generally more useful in real world scenarios.  I am more than happy to listen to any ideas others may have for more effective solutions.

`        
public static void SeedDatabase(IServiceCollection serviceCollection, Action<IServiceProvider> seedAction)
        {
            // Build the service provider.
            var serviceProvider = serviceCollection.BuildServiceProvider();

            using var scope = serviceProvider.CreateScope();

            // Create a scope to obtain a reference to the database context.
            var scopedServiceProvider = scope.ServiceProvider;
            var context = scopedServiceProvider
                .GetRequiredService<TContext>();

            var logger = scopedServiceProvider
                .GetRequiredService<ILogger<AbstractEfCoreFrameworkWebApplicationFactory<TStartup, TContext>>>();

            // Ensure the database is created.
            context.Database.EnsureCreated();

            try
            {
                // Seed the database with test data.
                seedAction(scopedServiceProvider);
            }
            catch (Exception ex)
            {
                logger.LogError(ex, "An error occurred seeding the database. Error: {Message}", ex.Message);
            }
        }
`

`
public class AuthenticatedEfCoreTestBase<TStartup, TContext> :
        AuthenticatedTestBase<TStartup>
        where TStartup : class, IStartupClass
        where TContext : DbContext
    {
        protected Action<IServiceProvider> SeedAction;

        #region Constructor

        public AuthenticatedEfCoreTestBase(
            AbstractEfCoreFrameworkWebApplicationFactory<TStartup, TContext> factory,
            Action<IServiceProvider> seedAction) :
            base(factory)
        {
            SeedAction = seedAction;
        }

        #endregion Constructor

        protected override WebApplicationFactory<TStartup> CreateFactory(ClaimsIdentity testIdentity)
        {
            return Factory.WithWebHostBuilder(b => b.ConfigureTestServices(serviceCollection =>
            {
                ConfigureTestServices(serviceCollection, testIdentity);

                ConfigureTestDatabase(serviceCollection);
            }));
        }

        protected virtual void ConfigureTestDatabase(IServiceCollection serviceCollection)
        {
            AbstractEfCoreFrameworkWebApplicationFactory<TStartup, TContext>.SeedDatabase(serviceCollection, SeedAction);
        }
    }
`

Per Tracking Issue [#14608](https://github.com/aspnet/EntityFrameworkCore/pull/14608), it appears that the proper solution for dealing with the ManyServiceProvidersCreatedWarning **in testing scenarios** is to register the InMemory DbContext using the new ServiceProviderCachingEnabled option.  Thus the Integration Docs should probably be updated as follows:

`
            DbRoot = new InMemoryDatabaseRoot(); // Create the DbRoot and store it in a protected field.
            // Add ApplicationDbContext using an in-memory database for testing.
            services.AddDbContext<ApplicationDbContext>(options =>
            {
                options.UseInMemoryDatabase("InMemoryDbForTesting", DbRoot);
                options.ServiceProviderCachingEnabled (false);
            });
`

It would be really nice if they could explain under what conditions it is more appropriate to use an external service provider explicitly versus disabling the service provider caching.  Also, has something changed in 3.0 such that the DbRoot creation step is no longer required or was that another oversight in the documentation?

**Comment by jelster** [comment]
Thanks for sharing your approach. It seems solid - I wouldn't spend all that much time worrying about your approach vis a vis factoring the database seeding code into a separate method. It seems like it leads to an improvement in the design since you can now easily make changes to those two areas without necessarily affecting the other.

@guardrex -- it sounds like docs updates to address ManyServiceProvidersCreatedWarning could be something to track as a separate issue. Would that be your recommendation for @dhhunter?

**Comment by Rick-Anderson** [comment]
Moved to #16341: Integration tests MASTER issue

**Comment by rvplauborg** [comment]
It would be very nice to be able to change the given claims on a per-method basis, such that for a given test class, one could have one test where user is a certain role, and another test where the user is another role. I do not see a trivial way of doing this using a test auth handler as suggested earlier in this issue, which is across the board and does not enable very granular claim setup.

**Comment by jelster** [comment]
>It would be very nice to be able to change the given claims on a per-method basis

Might it be possible to have a test class for each discrete set or combination of roles you are looking to exercise code against instead of the test methods all grouped together in the same class?

If not, perhaps you could consider pivoting those tests to be at a lower level (e.g., unit tests) instead of at the current, higher level of abstraction? It seems like you may be wanting to test the specific code that accepts a claim and makes a decision based on it, not necessarily everything surrounding it.

HTH

**Comment by rvplauborg** [comment]
> If not, perhaps you could consider pivoting those tests to be at a lower level (e.g., unit tests) instead of at the current, higher level of abstraction? It seems like you may be wanting to test the specific code that accepts a claim and makes a decision based on it, not necessarily everything surrounding it.

This makes a lot of sense, I guess it could be enough to unit test that specific logic and not worry about it on the higher level. We will go with this alternative I think. It would still be nice to change the user more dynamically for integration tests, i.e. if you have a _very_ commonly used flow, you can have a scenario testing of this exact flow, where multiple users/roles/.. may be involved :)
Thanks 👍

**Comment by guardrex** [comment]
Related remarks :point_right: https://github.com/dotnet/AspNetCore.Docs/pull/15340#issuecomment-593966651
