### ISSUE TITLE
3.1 new doc: Migrate from 3.0 to 3.1

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/AspNetCore.Docs#15678]
Outline what's needed here. Add a link when possible.

* [SameSite changes](https://review.docs.microsoft.com/en-us/aspnet/core/security/samesite?view=aspnetcore-3.0&branch=pr-en-us-15618)

**Comment by Tratcher** [comment]
The only change from the 3.0.1 patch to 3.1.0 is the addition of the enum value `SameSiteMode.Unspecified = -1`.

**Comment by danroth27** [comment]
We didn't make any breaking changes in MVC/Blazor for 3.1 so the upgrade should be as simple as targeting your app to netcoreapp3.1 and updating package versions to the 3.1 versions.

For Blazor apps, we did introduce a [new component tag helper](https://devblogs.microsoft.com/aspnet/asp-net-core-updates-in-net-core-3-1-preview-2/), which is easier to use than the previous component HTML helper. We could provide some migration guidance to suggest users use the tag helper instead of the HTML helper, but it's optional and not required. The HTML helper is still supported.

**Comment by guardrex** [comment]
> new component tag helper

Not fully covered at this point in the regular topics. I still have ~3 spots that need a touch of work, the most important being in the *Components* topic. I'll work on that today on the existing *Components* PR. I'll mark that PR briefly with a **HOLD** until it's ready for review.

**Comment by scottaddie** [comment]
I'm going to start working on this doc now.

**Comment by guardrex** [comment]
Destination confirmed live at ...

```
<xref:blazor/components#integrate-components-into-razor-pages-and-mvc-apps>
```

https://docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.0#integrate-components-into-razor-pages-and-mvc-apps

... and there will be significant enhancements coming soon to cover hybrid apps. For now tho ... for this issue, you're good to link there. The Component TH is covered at 3.1 today.
