### ISSUE TITLE
Set environment variables with PropertyGroup issue

### ISSUE THREAD

**Issue by eduardoxvii** [aspnet/AspNetCore.Docs#15682]
"An alternative to setting the environment directly in web.config is to include the &lt;EnvironmentName&gt; property in project file"
My config:
  &lt;PropertyGroup&gt;
    &lt;TargetFramework&gt;netcoreapp3.0&lt;/TargetFramework&gt;
    &lt;EnvironmentName&gt;Development&lt;/EnvironmentName&gt;
  &lt;/PropertyGroup&gt;
But "dotnet App.dll" run aways in Production environment 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe69b3a9-896f-e189-0c2c-f87ff735df9c
* Version Independent ID: 97c8549b-66ad-0a23-1971-784fb923042a
* Content: [ASP.NET Core Module](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/aspnet-core-module?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/host-and-deploy/aspnet-core-module.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/host-and-deploy/aspnet-core-module.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @eduardoxvii ... I'll get back to you within 24 hours. I'm 🏃😅 at the moment.

**Comment by guardrex** [comment]
ok ... I'm back!

...... so the deal here is that running the assembly with `dotnet` isn't the same as when the app starts under IIS/ANCM and the env var is set. If you publish an app with the `<EnvironmentName>` in the project file set to the `GreenDino` environment 🐲, you'll end up with the env var set in the *web.config* generated by the SDK ...

```xml
<aspNetCore ...>
  <environmentVariables>
    <environmentVariable name="ASPNETCORE_ENVIRONMENT" value="GreenDino" />
  </environmentVariables>
</aspNetCore>
```

So when the app is started in IIS, that's going to set its environment. It's covered at ...

https://docs.microsoft.com/en-us/aspnet/core/fundamentals/environments?view=aspnetcore-3.0#environment-variable-or-platform-setting

... down under **Project file or publish profile** > **For Windows IIS deployments:**.

If you want to run the app locally from a command shell (`dotnet run` is the usual way), set the env var in the *launchSettings.json* file. All of the approaches are explained out in the *Multiple Environments* topic ...

https://docs.microsoft.com/en-us/aspnet/core/fundamentals/environments

Since this topic pertains only to the IIS/ANCM hosting scenario, the topic doesn't require any changes.
