### ISSUE TITLE
Scaffolding identity in v3.0 for MVC project

### ISSUE THREAD

**Issue by Legends** [aspnet/AspNetCore.Docs#15706]
Related [section](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-3.0&tabs=visual-studio#scaffold-identity-into-an-mvc-project-without-existing-authorization):

Shouldn't the folder be named **Views** when scaffolding identity from inside an MVC project ???
![image](https://user-images.githubusercontent.com/966368/68946963-88de5000-07b4-11ea-8335-862100c16d9c.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 804e24dd-7e30-8cf5-2c99-1ffacb4582f6
* Version Independent ID: 3e25547b-e2c9-6634-2c38-2a77207f17d4
* Content: [Scaffold Identity in ASP.NET Core projects](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-3.0&tabs=visual-studio#scaffold-identity-into-an-mvc-project-without-existing-authorization)
* Content Source: [aspnetcore/security/authentication/scaffold-identity.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/scaffold-identity.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by eavonius** [comment]
I'm also experiencing this. It seems the scaffolding uses Razor pages instead of MVC regardless of what I try.

Could you add something to the documentation to help us understand how the code generator determines whether to generate Razor Pages or MVC Pages, or perhaps add a UI option in Visual Studio (and corresponding flag in the command line) to make an explicit choice?

**Comment by Rick-Anderson** [comment]
No, that's how it works. It uses Razor Pages.

**Comment by Legends** [comment]
Razor files `.razor`, Razor Class Libraries, Razor Pages, Razor syntax..... looks like someone was drunk...

If I scaffold something inside an MVC project, I want it to be MVC project compliant and I don't want a Razor Pages Scaffolding which doesn't work inside my MVC project.

It's only logical...

**Comment by eavonius** [comment]
I have a client who is moving from ASP.NET WebPages to ASP.NET MVC.

Just so I'm understanding, they will now have to learn both ASP.NET MVC and Razor Pages to work with Identity? There is no Identity scaffolding for ASP.NET MVC projects anymore?

I'm just mentioning this because it creates a pretty significant extra learning curve for my client now. I'll need to decide whether to move them to Razor Pages instead even though they've been studying ASP.NET MVC.

**Comment by Rick-Anderson** [comment]
>  I want it to be MVC project compliant 

We don't have a concept of MVC project compliant 

> and I don't want a Razor Pages Scaffolding which doesn't work inside my MVC project.

RP was architected to work with controllers and views

**Comment by Rick-Anderson** [comment]
> I'm just mentioning this because it creates a pretty significant extra learning curve for my client now. I'll need to decide whether to move them to Razor Pages instead even though they've been studying ASP.NET MVC.

RP is could be a better choice. Our high school interns picked up RP in one day, it's not a significant extra learning curve

**Comment by Legends** [comment]
@Rick-Anderson 

> ASP.NET Core 2.1 and later provides ASP.NET Core Identity as a Razor Class Library.

Where can we find this library in order to use Identity scaffolding with MVC ? Is it a nuget package?

**Comment by DiomedesDominguez** [comment]
@Rick-Anderson

Is not about the learning curve, it's about having consistency in our code, just like we already have in .NET Framework. The only thing I can think is to rewrite the controllers to use MVC in a MVC project instead of using Razor Pages in a MVC project.
