### ISSUE TITLE
SqlClient in "Migrate from ASP.NET Core 2.2 to 3.0"

### ISSUE THREAD

**Issue by firstasync** [aspnet/AspNetCore.Docs#15760]
The document should indicate the needed of include a package reference to System.Data.SqlClient since some third-party library (like Dapper) may stop working properly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76f39eec-9dd1-6167-56ec-47b26e0b5063
* Version Independent ID: f9f2b0f3-01eb-cf58-8767-194fe0fc0e44
* Content: [Migrate from ASP.NET Core 2.2 to 3.0](https://docs.microsoft.com/en-US/aspnet/core/migration/22-to-30?view=aspnetcore-3.0&tabs=visual-studio)
* Content Source: [aspnetcore/migration/22-to-30.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/migration/22-to-30.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-migration**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by scottaddie** [comment]
Because this is an implementation detail for Dapper, we won't be adding it to our docs. It's already mentioned in the release notes for Dapper v2.0.4 (see https://stackexchange.github.io/Dapper/). If possible, you may want to consider using `Microsoft.Data.SqlClient` as a drop-in replacement for `System.Data.SqlClient`. Reasons are outlined here: https://devblogs.microsoft.com/dotnet/introducing-the-new-microsoftdatasqlclient/.
