### ISSUE TITLE
Get started tutorial invalid URL

### ISSUE THREAD

**Issue by CeciAc** [aspnet/AspNetCore.Docs#15832]
@mikamboo commented on [Fri Nov 22 2019](https://github.com/aspnet/AspNetCore.Docs.fr-fr/issues/238)

After testing this doc, it's appear that Blazor ids running on localhost:5000 not on  localhost:5001.

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: c07e57dc-526f-9479-4695-de7d8f06eb9a
* Version Independent ID: 8226ed72-69b2-3c93-a931-218bd11cf9c8
* Content: [Prise en main de ASP.NET Core Blazor](https://docs.microsoft.com/fr-fr/aspnet/core/blazor/get-started?view=aspnetcore-3.0&tabs=netcore-cli#feedback)
* Content Source: [aspnetcore/blazor/get-started.md](https://github.com/aspnet/AspNetCore.Docs.fr-fr/blob/live/aspnetcore/blazor/get-started.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

---

@srvbpigh commented on [Fri Nov 22 2019](https://github.com/aspnet/AspNetCore.Docs.fr-fr/issues/238#issuecomment-557510334)

Hello, @mikamboo
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by guardrex** [comment]
The URL is correct, so I can't explain why this might happen outside of the [development certificate not being trusted](https://docs.microsoft.com/aspnet/core/security/enforcing-ssl#trust-the-aspnet-core-https-development-certificate-on-windows-and-macos).

@mikamboo You can get help on a support forum, such as Stack Overflow, or a support chat, such as [Slack](http://tattoocoder.com/aspnet-slack-sign-up/) or [Gitter](https://gitter.im/aspnet/Home).

If you find out what the problem is and it is something that we need to cover, please respond back here, and we'll re-open this issue.
