### ISSUE TITLE
File type for listings

### ISSUE THREAD

**Issue by sergtk** [aspnet/AspNetCore.Docs#15903]
Since this is a tutorial, please clarify what you mean in the code listing. Two times you first refer to .razor file, then just above the listing you title it as CSHTML. Is the code in the listing should be in .razor-files or in .cshtml-files?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bc28995-6784-a7d2-5c0b-9811a8d19c1a
* Version Independent ID: 1668c8fb-024c-c86d-d4d5-e22e3355c04b
* Content: [Introduction to ASP.NET Core Blazor](https://docs.microsoft.com/en-us/aspnet/core/blazor/index?view=aspnetcore-3.0&source=docs#feedback)
* Content Source: [aspnetcore/blazor/index.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello ... that's because we don't have a "razor" code block designation yet. Razor components are written with Razor syntax but have a *.razor* file extension. I'll take a look at the way these files are described and see what can be done here. btw - We just put up a topic to describe the files in the template. That may assist you in understanding the anatomy of a Blazor app.

https://docs.microsoft.com/en-us/aspnet/core/blazor/templates?view=aspnetcore-3.0

**Comment by guardrex** [comment]
@scottaddie Was the code language name "razor" approved, or is that still in the works?

**Comment by guardrex** [comment]
I *guess* we're approved to use the "razor" code language now ... going by the build system not choking on it anyway :point_up:.

I'll use this issue to track updating *ALL* of the Blazor topics. Thanks again @sergtk for asking.

**Comment by sergtk** [comment]
@guardrex IMHO the issue with the page https://docs.microsoft.com/en-us/aspnet/core/blazor/index?view=aspnetcore-3.0 is deeper. In fact, I can't get the example working. Note, this is for a newbie for the technology. It would be good if some expert checks the info on the page. And either fix the errors or add a description so it would be easier to use by newbies.

E.g. as for now I use `Index` with `cshtml` extension, and I got some reasonable output. When I used `razor` extension, I didn't get any output.

I still can't get button working.
Well, I think it would be better if somebody review that page, I just can't get the code working as described.
Probably file locations should be specified.
Probably this should be described in a new issue.

Probably I should describe my issue better to create a new issue. But as for now I can't do this, I am triying diffection options.
So this is up to you whether to create new issue or not

**Comment by guardrex** [comment]
Don't start with this page other than just for a general overview of Blazor. This page isn't designed to get you started ... it's truly just a broad overview.

I can see what you mean tho ... you see these code examples and expect to be able to immediately drop them into an app and have them work, but that's not the case. These are just code examples for developers coming in with some experience with ASP.NET or other client-side frameworks so that they can see in a general way how these components are composed.

Our topics are generally placed into the TOC (table of contents) in order that we feel a reader should gain knowledge, and that's certainly the case here in the *Blazor* node.

Hit the exercise in the *Get Started* doc first ...

https://docs.microsoft.com/aspnet/core/blazor/get-started

... read about the *Hosting models* next ...

https://docs.microsoft.com/aspnet/core/blazor/hosting-models

... and then the *Build Your First* tutorial after that ...

https://docs.microsoft.com/aspnet/core/tutorials/build-your-first-blazor-app

... while referring to the new *Templates* topic as you go, which explains what the various files are ...

https://docs.microsoft.com/aspnet/core/blazor/templates

That's the best path to take ... right down the line. The entire node builds knowledge and experience with Blazor one topic at a time for the most part. Cross-linking within these topics helps otherwise.

**Comment by guardrex** [comment]
Fixed by ...

* https://github.com/aspnet/AspNetCore.Docs/pull/16035 - Now, we're using the "razor" code language in the topics for Razor components (*.razor* files).
* The new [Templates](https://docs.microsoft.com/en-us/aspnet/core/blazor/templates?view=aspnetcore-3.1) topic, which helps readers understand the anatomy of a Blazor app.
