### ISSUE TITLE
Compare validator doesn't show validation error

### ISSUE THREAD

**Issue by sarathlalsaseendran** [aspnet/AspNetCore.Docs#15915]
Hi, I have checked with Compare validator in viewmodel for Email field. It is not showing any error in validation summary. Can you please check that?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eef47457-c8cf-74a4-b884-c1fe5c2ef52d
* Version Independent ID: 09a02d10-2834-467d-d8c2-3fd19ceb3863
* Content: [ASP.NET Core Blazor forms and validation](https://docs.microsoft.com/en-us/aspnet/core/blazor/forms-validation?view=aspnetcore-3.0)
* Content Source: [aspnetcore/blazor/forms-validation.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/forms-validation.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @sarathlalsaseendran ... It looks like this is a 🐞 *bug* that will be fixed for 3.1.

https://github.com/aspnet/AspNetCore/issues/10643

I'll take a look at this topic next week to see about placing a 3.0-only note to cover this for 3.0. Thanks for writing in.

**Comment by guardrex** [comment]
If you try 3.1 and it isn't fixed, open an issue on the engineering repo for them to look at it. Show them the exact code that you're using. If you want, you can add a "cc: @guardrex" to the bottom of your issue over there so that I can track it. Otherwise, open a new issue here on this topic after you find out what they say if this topic requires more work.

For this issue and the bug fix that they've put in, I'll ping you on the PR next week. Leave this open ... it will automatically close when the PR merges.

**Comment by sarathlalsaseendran** [comment]
Hello @guardrex, thank you very much for the quick reply. I will check with 3.1 and update you.
