### ISSUE TITLE
Defer causes script tag to download CDN and also the Fallback script

### ISSUE THREAD

**Issue by offirpeer** [aspnet/AspNetCore.Docs#15932]
[EDIT by guardrex to add the metadata]

This code forces the browser to download the CDN and also the fallback file.
I am guessing it's because of the `<script defer`
```
  <script defer src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
            asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
            asp-fallback-test="window.jQuery"
            crossorigin="anonymous"
            integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
    </script>
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c90104e1-65b1-0007-e56d-0dffef4b1a44
* Version Independent ID: 5c95e5dc-dc10-8658-91fd-1d55d3959c37
* Content: [Script Tag Helper in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/tag-helpers/built-in/script-tag-helper?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/mvc/views/tag-helpers/built-in/script-tag-helper.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/views/tag-helpers/built-in/script-tag-helper.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @offirpeer ... I don't think it's due to the presence of `defer`. If you take that off, you'll get the same behavior. Given the [Script Tag Helper](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/tag-helpers/built-in/script-tag-helper) description, it doesn't seem correct ... I agree.

> The URL of a Script tag to fallback to in the case the primary one fails.

https://docs.microsoft.com/dotnet/api/microsoft.aspnetcore.mvc.taghelpers.scripttaghelper.fallbacksrc

Therefore, this should go to the product unit for an answer. Open an issue on it at :point_right: https://github.com/aspnet/AspNetCore/issues.

If you think to add a ping for me, put a "cc: @guardrex" at the bottom of your opening comment so that I can track the discussion. Otherwise if the doc needs work based on their response, open a new issue here with the **This Page** feedback button+form at the bottom of the [Script Tag Helper](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/tag-helpers/built-in/script-tag-helper) topic and cross-link the engineering issue.

**Comment by guardrex** [comment]
Let me check one more thing real fast tho before you do that. BRB .....

**Comment by Rick-Anderson** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script

defer
This Boolean attribute is set to indicate to a browser that the script is meant to be executed after the document has been parsed, but before firing DOMContentLoaded.

Scripts with the defer attribute will prevent the DOMContentLoaded event from firing until the script has loaded and finished evaluating.
