### ISSUE TITLE
Options topic review

### ISSUE THREAD

**Issue by xenophilios** [aspnet/AspNetCore.Docs#15987]
This article would make much more sense to me if it started with a realistic example.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed39cb0e-aa85-8bba-ffb4-859b56a60723
* Version Independent ID: dc7e3449-650b-d117-5eac-69e5ccb250cb
* Content: [Options pattern in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/options?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/fundamentals/configuration/options.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/configuration/options.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Can you explain what you mean by "realistic" in the context of the scenarios provided by the sample? It shows each of the common scenarios for implementing the Options patterns that the framework offers.

**Comment by xenophilios** [comment]
Hi Luke,

 

Thank you for such a fast reaction.

 

First of all, try to imagine that the person reading this article may have no prior knowledge of its subject matter. That is the case with me and it may be the case with other people too.

 

My recommendation would be to start out with a specific, common problem that can be best solved by the use of options. Then show how to solve it with options. If there are other ways of solving the problem, show how solving it with options would be better. Only explain the generalities, as in the section "Options interfaces", after providing enough examples to make the use of options clear.

 

In general, the concrete should precede the abstract and the abstract should always be supported with examples that arise frequently in practice.

 

The MyOptions class given near the beginning of the section "General options configuration" makes no sense to me. What would I ever want to do with it? That is what prompted me to ask for a more realistic example.

 

I would be happy to talk with you on the phone, if you would like to discuss any issues in more detail.

 

I greatly appreciate the online documentation and prefer it, in general, to some of the books I have studied. Thank you and your colleagues for your hard work!

 

With best regards,

 

Eric Weinberger

Eau Claire, Wisconsin, USA

 

Phone: 1-715-514-4710

**Comment by guardrex** [comment]
Thanks for providing your feedback. A little backstory on this one ...

What you see here is practically the *first version* of the topic. It was written from scratch after the Options API was built out by the engineering team several releases ago, and it's only been updated for API changes with framework releases since then. We don't get many complaints about this topic. Prior to your remarks here, I think we've had two readers write in with concerns about it ... that's **two issues** (maybe three) out of **_several thousand_** views.

We must be a little guarded about making major changes to topics that receive thousands of views and only a few negative remarks. A possible outcome of reacting to a few general concerns with major updates is that we would rewrite a topic only to aggravate **_many more readers_** from the updates than the number of readers who didn't care for the topic in the first place.

I put this in the context of having taught several dozen courses at college and universities over the years: Would you radically change a course if 5% of your students said that they hated it and 70% said that they loved it and encouraged you to not change a thing?? Probably not. We must be careful. It's expensive 💰, too! (*Praise be to the company!*) :smile: lol

I'd like to take a look at this topic for updates based on your feedback and remarks of other devs who have written in. We're a bit 🏃😅 at the moment, so this would likely be in January. Improvements can likely be made here, and I'll ping u on the PR. Thanks again for writing in.

**Comment by guardrex** [comment]
Cross-link :point_right: https://github.com/aspnet/AspNetCore.Docs/issues/13910

**Comment by xenophilios** [comment]
Hi Luke,

 

Thank you for taking the time to write at such length.

 

In the comment I posted on your site, I was only asking for a more realistic example of the class MyOptions, something that should not take more than five minutes of effort. I was not asking for anything remotely approaching a complete or radical rewrite of the article. So far I have only read the beginning of it, because at the moment I have no idea whether it is relevant to my needs or not.

 

I cannot imagine that such a minor improvement would antagonize thousands of readers. However, if you try it and discover that it does in fact upset thousands of people, you can always go back to the original version.

 

Whatever the case may be, I do not wish to be understood as making any personal criticisms. The only reason why I even bother to make any comments on the online documentation in the first place is that I find it a very useful and helpful tool, much better, as I have already said, than some of the books I have studied on the subject matter.

 

Thank you again for your hard work and your kind messages.

 

With all best wishes,

 

Eric

**Comment by guardrex** [comment]
This example covers all of the scenarios in the topic. Although we can't have several samples, we certainly could have **_several classes_** in the sample ... one per scenario. The simplest class might be best for the opener ... then a more advanced class for more advanced scenarios. It was just expedient at the time to have one class to demo all of the scenarios. Also, I hear you on making the Options pattern more relevant. I'll take a look at that, too.

I'll take a look and see what's what in January. Right now, we're focused on wrapping up the 3.1 release that landed today. **_Vacations start soon!_** ... including mine. **_WOOT!_** After the holidays 🎁⛄️, I'll do a full review on this topic taking into account all of the remarks that we've received. I'll use this issue to track that work.

**Comment by Rick-Anderson** [comment]
Moved to #10553

**Comment by xenophilios** [comment]
Thank you, Luke. Enjoy your vacation.

 

With best regards,

 

Eric

**Comment by guardrex** [comment]
It's scheduled for a :eyes: look in January. This issue is cross-linked, so our discussion here won't get lost. I kind'a think that the other issue was addressed by engineering on a commit that one of the engineers made over there, but I'll take a look. We'll use that one to track work. Thanks for writing in.
