### ISSUE TITLE
AllowCredentials and no authentication

### ISSUE THREAD

**Issue by codingsteff** [aspnet/AspNetCore.Docs#16003]
Why do the credentials need to be enabled even if authentication is not used?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8af11946-ea05-3be2-6fa1-c4c01aa76d8c
* Version Independent ID: 58e87eb0-240b-ab00-c5f4-32a0ab2e0028
* Content: [Security considerations in ASP.NET Core SignalR](https://docs.microsoft.com/en-us/aspnet/core/signalr/security?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/signalr/security.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/signalr/security.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-signalr**
* GitHub Login: @bradygaster
* Microsoft Alias: **anurse**

**Comment by Rick-Anderson** [comment]
Where does it say that's required?

**Comment by codingsteff** [comment]
Line 31
"* Credentials must be enabled, even when authentication is not used."

**Comment by BrennanConroy** [comment]
We can clarify this a little probably. In 3.1 and below this has to be enabled because there is no customization in the browser client to not use credentials.
However, in 5.0 we have provided an option in the Typescript client to not use credentials.
That option should only be used when you know 100% that credentials like Cookies are not needed in your app (cookies are used by azure app service when using multiple servers).
