### ISSUE TITLE
JSRuntime.Current no longer exists

### ISSUE THREAD

**Issue by LaughingJohn** [aspnet/AspNetCore.Docs#16118]
See this sentence:
Multiple user requests are processed by the Blazor Server app. Don't call JSRuntime.Current in a component to invoke JavaScript functions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49807900-0d56-e23c-1aef-d79099caeffb
* Version Independent ID: feff434f-912c-0985-d575-4a23a629057d
* Content: [ASP.NET Core Blazor JavaScript interop](https://docs.microsoft.com/en-us/aspnet/core/blazor/javascript-interop?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/blazor/javascript-interop.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/javascript-interop.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @LaughingJohn ...

🤔 It was reviewed by engineering for the 3.0 release (not sure if it changed for 3.1). I'll put this up for triage so that engineering can respond. Stand-by tho if it takes a while to get an answer ... we're **_very_** close to the holidays 🎁⛄️, so they might not remark on it until January.

**Comment by mkArtakMSFT** [comment]
@guardrex JSRuntime.Current is indeed gone. The JSRuntime services are available only through DI now. This is true for both 3.0 and 3.1.

**Comment by guardrex** [comment]
Fixed by https://github.com/aspnet/AspNetCore.Docs/pull/16246.
