### ISSUE TITLE
Small improvement in az keyvault set-policy script

### ISSUE THREAD

**Issue by jeroenwo** [aspnet/AspNetCore.Docs#16117]
When copied, modified and run, the following command contains a small error:
`az keyvault set-policy --name '{KEY VAULT NAME}' --object-id {OBJECT ID} --secret-permissions get list`

The `{KEY VAULT NAME}` parameter is surrounded by quotes, where the `{OBJECT ID}` is not.

Running the script:
`az keyvault set-policy --name 'myvaultname' --object-id insert-guid-here --secret-permissions get list`

Results in the following error:
The Resource 'Microsoft.KeyVault/vaults/'myvaultname'' not found within subscription. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2cc0b77a-df21-7007-5cec-4399d98c6dc6
* Version Independent ID: efe5ae5e-ff64-f1c7-6920-4512fc8f36d1
* Content: [Azure Key Vault Configuration Provider in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/key-vault-configuration?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/security/key-vault-configuration.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/key-vault-configuration.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @jeroenwo ... AFAICT, I took that from here ...

https://docs.microsoft.com/en-us/azure/key-vault/tutorial-net-windows-virtual-machine#assign-permissions-to-the-vm-identity

... and it did work at the time. I think that they changed the format of the command since then, but their topic wasn't updated. I see a different topic that shows the command without quotes ...

https://docs.microsoft.com/en-us/azure/key-vault/quick-create-net#give-the-service-principal-access-to-your-key-vault

... soooooo I'll fix this up here. Next, I'll alert them to that discrepancy. Thanks for writing in about it.
