### ISSUE TITLE
Add documentations on applying filters and inheritance

### ISSUE THREAD

**Issue by hoksource** [aspnet/AspNetCore.Docs#16111]
I want to make all my page inherit a class or a component that does a custom filter and behavior when filter is not met. Is this the way to do this on blazor or there is another style of doing this? Also there is no documentation for @inherit and @attribute for inheriting custom component pages, @attribute also is not documented for filters. This also makes lifecycle code reusable.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be4c4d0c-149c-bde1-c7fa-f082916390ca
* Version Independent ID: 9d945996-ad02-bd4b-58ea-c465cc5cc74c
* Content: [Create and use ASP.NET Core Razor components](https://docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.1)
* Content Source: [aspnetcore/blazor/components.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/components.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
`@inherits` was covered for base class support prior to the release of partial class support. If you select the 3.0 version of the topic, you'll see the prior section *Specify a component base class*. I'm thinking now that we should keep that section. @danroth27, bring that section back?

Otherwise, there's some coverage in the DI topic in the [Request a service in a component](https://docs.microsoft.com/en-us/aspnet/core/blazor/dependency-injection?view=aspnetcore-3.1#request-a-service-in-a-component) section. A little more in the next section there, *Utility base component classes to manage a DI scope*. The most prominent example across the Blazor docs is for `LayoutComponentBase` in the [Layouts](https://docs.microsoft.com/en-us/aspnet/core/blazor/layouts) topic.

`@attribute` is primarily covered for security (authorization) in the [Authn & Authz topic](https://docs.microsoft.com/en-us/aspnet/core/security/blazor/?view=aspnetcore-3.1&tabs=visual-studio#authorize-attribute). It perhaps should be covered in a more general way in the *Components* topic.

I'll mark this for triage, and engineering can specify what they'd like to add or clarify. Thanks for your feedback.

**Comment by hoksource** [comment]
I would like to know more about routing guards for navigation.
Is there a documentation for like a filter or route guard when going to a certain page?
Or a way to implement life cycle on a layout (for multiple page with the same filter)?
Or do i have to create a base component class and implement the on initialize then @inherit the base component class to do the filter?
Or can i apply @attribute filter for all the pages?
I'm not sure how this will affect the server and webassembly design. But I need this feature as of now (Or atleast a documentation for them). Thanks in advance

**Comment by mkArtakMSFT** [comment]
@guardrex let's bring back the sectio nabout parent component.
Also, it would be great to document the usage of the `@attribute` on component level.

@hoksource it looks like you're confused about filters applicability. Filters are applicable to Controllers and Pages in some cases. They're not intended to be used on Components. Razor Pages and Components with a `@page` directive attribute are different things.

**Comment by hoksource** [comment]
I think my question is more on the routing part. how to prevent users from going to a set of pages where resources or parameters not met. I will post my question there. thanks.
