### ISSUE TITLE
EnumeratorCancellation attribute

### ISSUE THREAD

**Issue by tafia** [aspnet/AspNetCore.Docs#16202]
When building the server to client, I have a warning saying that the `CancellationToken` is missing a `EnumeratorCancellation` attribute or else it would remain unconsumed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a02b4e7d-971a-670b-02eb-89c5456ec8f2
* Version Independent ID: 5f2f089e-310d-83a1-9c56-9cb441b9914a
* Content: [Use streaming in ASP.NET Core SignalR](https://docs.microsoft.com/en-us/aspnet/core/signalr/streaming?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/signalr/streaming.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/signalr/streaming.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-signalr**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

**Comment by Rick-Anderson** [comment]
What `dotnet --version` ?

**Comment by tafia** [comment]
3.1

**Comment by bradygaster** [comment]
That's a bit odd - adding @anurse here FYI. I've not seen that warning prior to this issue.

**Comment by anurse** [comment]
I think it's OK to do this in our docs. I don't think it's required that you apply `EnumeratorCancellation` to streaming SignalR methods because that warning is designed for cases where `foreach await` is being used to enumerate (and that's not the case with SignalR methods) but unit tests may do that and it's benign.

We should update the doc to include the `EnumeratorCancellation` attribute on `CancellationToken` parameters whenever we're returning an `IAsyncEnumerable`.
