### ISSUE TITLE
404 broken link on documentation site 

### ISSUE THREAD

**Issue by freemstr** [aspnet/AspNetCore.Docs#16257]
Broken link to https://azure.microsoft.com/documentation/samples/active-directory-dotnet-webapp-openidconnect-aspnetcore/
From the menu, this seems to have been already reported in #15139

**Comment by guardrex** [comment]
Hello @freemstr ... I can't find that link, including doing a search on our entire repo locally.

If you're referring to this page ...

* https://docs.microsoft.com/en-us/aspnet/core/security/authentication/azure-active-directory/?view=aspnetcore-3.1
* https://github.com/aspnet/AspNetCore.Docs/edit/master/aspnetcore/security/authentication/azure-active-directory/index.md

... that first link in the list was changed to ...

https://github.com/Azure-Samples/active-directory-dotnet-webapp-openidconnect-aspnetcore

If that's the page/link that you're asking about, try refreshing the page in your browser ... you may have a cached version of it showing the old link.

btw -- Please use the **This page** feedback button+form at the bottom of the topic so that we can see which topic you're looking at. It adds metadata to the issue and automatically pings the author.

**Comment by freemstr** [comment]
@guardrex I was able to find/repro the error in your repo, so here it is:
If you start here https://docs.microsoft.com/en-us/aspnet/core/security/authentication/azure-active-directory/?view=aspnetcore-3.1

Left menu item "Integrate Azure AD into a web app" goes 404, in chrome with disabled cache
the url of the 404 page https://azure.microsoft.com/en-us/resources/samples/active-directory-dotnet-webapp-openidconnect-aspnetcore/

Ever since this https://github.com/aspnet/AspNetCore.Docs/pull/10603
in this repo left menu corresponds to https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/toc.yml

so there is nothing in the .md, its the menu builder code

btw -- **Please use the This page feedback button** is not present on the 404 page

**Comment by guardrex** [comment]
Oh! You mean sidebar TOC ... ah, gotcha ... that's actually not in a topic then. No worries. I'll fix it. Thanks for reporting this.
