### ISSUE TITLE
Browser Link in .NET Core 3 and later?

### ISSUE THREAD

**Issue by xudonax** [aspnet/AspNetCore.Docs#16297]
The start of the page talks about .NET Core 2.0 and 2.1, and the referenced package (Microsoft.VisualStudio.Web.BrowserLink) hasn't been updated since March 2018. Is this still a thing in .NET Core 3 and later?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1fcc1fa9-004b-0be3-6148-e8c075e5b2bc
* Version Independent ID: 78a1947e-dea7-65b4-2376-05c7795e4bf9
* Content: [Browser Link in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/client-side/using-browserlink?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/client-side/using-browserlink.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/client-side/using-browserlink.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-clientside**
* GitHub Login: @ncarandini
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@mkArtakMSFT can we retire this browser link article?

**Comment by scottaddie** [comment]
@jodavis What's the current state of BrowserLink?

**Comment by softlion** [comment]
Why no answer ... hard question ?

**Comment by softlion** [comment]
Answer here: https://stackoverflow.com/questions/59140127/browserlink-in-net-core-3-0

**Comment by jodavis** [comment]
@scottaddie Browser Link still works in .NET Core 3. 

The package hasn't been updated because it only contains the hooks that Visual Studio uses to interact with the server. All the functional updates and bug fixes that have been needed are in Visual Studio itself.

Please don't remove the article. Visual Studio has fwlinks to it.

**Comment by softlion** [comment]
I confirm that it works fine.
You must add the NuGet package ```Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation```
and a call to ```services.AddMvc().AddRazorRuntimeCompilation();``` and ```app.UseBrowserLink();```

**Comment by scottaddie** [comment]
@softlion That makes sense because Razor runtime compilation is an opt-in feature as of ASP.NET Core 3.0. It was removed from the shared framework because of the dependency on Roslyn, which was also removed from the shared framework. See https://docs.microsoft.com/aspnet/core/migration/22-to-30?view=aspnetcore-3.1&tabs=visual-studio#opt-in-to-runtime-compilation for more info.

I'll apply the necessary 3.0 updates to the doc.

**Comment by scottaddie** [comment]
@jodavis FYI, BrowserLink isn't working for me at all. See the issue I've logged at https://github.com/aspnet/BrowserLink/issues/104.

**Comment by jodavis** [comment]
@scottaddie I'll follow up on your issue in aspnet/BrowserLink#104.

**Comment by Tidy1** [comment]
I used @softlion method and it fixed my browser link.
