### ISSUE TITLE
ASP.NET Core: Add recommended DI configurations for IFileProviders

### ISSUE THREAD

**Issue by mdarefull** [aspnet/AspNetCore.Docs#16338]
The different instances of IFileProvider aren't already registered in the services when the application start up, meaning services referencing a provider through DI will require the developer to register it.

I would add a section about recommended ways to register it: As Instance, Scoped or Singleton, and also recommended ways to instantiate it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d8787c1-1a02-ae68-aa59-7c0e2e823dde
* Version Independent ID: 3e799e5d-a89c-cd03-999f-92ae431f4657
* Content: [File Providers in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/file-providers?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/fundamentals/file-providers.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/file-providers.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
#### OOF for the :gift: *holidays* :snowman: and will return on January 6.

If you need support, we recommend contacting devs on support channels and chat:

* [Stack Overflow](https://stackoverflow.com/questions)
* [ASP.NET Core Slack](http://tattoocoder.com/aspnet-slack-sign-up/)
* [ASP.NET Gitter](https://gitter.im/aspnet/Home)

Potential bugs in the ASP.NET Core framework and product feedback can be reported at [aspnet/AspNetCore issues](https://github.com/aspnet/AspNetCore) (include full repro steps and cross-link to a repro project in GH when appropriate). For Visual Studio, use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) gesture or [Suggest a Feature](https://docs.microsoft.com/en-us/visualstudio/ide/suggest-a-feature?view=vs-2019) gesture within VS, which open internal issues for the VS team. For Visual Studio Code, you can open an issue at [microsoft/vscode issues](https://github.com/Microsoft/vscode/issues).

:dancer::man_dancing: **_Happy New Year! See you in 2020!_** :balloon::champagne:

**Comment by guardrex** [comment]
Hello @mdarefull ... I'm back from vacation now.

> different instances of IFileProvider aren't already registered in the services when the application start

`IWebHostEnvironment` provides a [WebRootFileProvider](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.hosting.iwebhostenvironment.webrootfileprovider?view=aspnetcore-3.1#Microsoft_AspNetCore_Hosting_IWebHostEnvironment_WebRootFileProvider), and it also (due to implementing `IHostEnvironment`) has a [ContentRootFileProvider](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.hosting.ihostenvironment.contentrootfileprovider?view=dotnet-plat-ext-3.1#Microsoft_Extensions_Hosting_IHostEnvironment_ContentRootFileProvider). These providers end up being singletons.

> recommended ways to register it

Engineering recommends a singleton registration for a `CompositeFileProvider`. However, we didn't explicitly call that out. It's by demonstration in the topic+sample.

I'm not aware of any specific advice to offer. @Tratcher, do u think that there's any additional guidance to add to the topic?

**Comment by Tratcher** [comment]
Why do they need to be registered? IFileProvider is a case where an app is likely to have several different instances for different purposes and DI doesn't cleanly support that (e.g. named instances). Instead we put the file providers on other registered services like IWebHostEnvironment WebRootFileProvider and ContentRootFileProvider so you can distinguish between them.

**Comment by guardrex** [comment]
Closing due to lack of response.
