### ISSUE TITLE
I'm using the authentication in .net core 3.1. I tried to log in the user but got nothing

### ISSUE THREAD

**Issue by EmilyEdna** [aspnet/AspNetCore.Docs#16361]
In the Configuration,I used `services.AddAuthentication(CookieAuthenticationDefaults.AuthenticationScheme).AddCookie();             app.UseStaticFiles();
app.UseRouting();
app.UseAuthentication();
app.UseEndpoints(endpoints => endpoints.MapControllers());` 
and in the controller I Use `List<Claim> claims = new List<Claim>
                {
                    new Claim(ClaimTypes.NameIdentifier, RoleAdmin.RolePermissionId.ToString()),
                    new Claim(ClaimTypes.Name, RoleAdmin.AdminName),
                    new Claim(ClaimTypes.Role, RoleAdmin.HandlerRole)
                };
                var claimIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
                await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(claimIdentity), new AuthenticationProperties { 
                    IsPersistent = true,
                    ExpiresUtc = DateTimeOffset.UtcNow.AddMinutes(60),
                    AllowRefresh = true
                });`  but last I got `HttpContext.User.Claims.Count=0`

**Comment by guardrex** [comment]
Hello @EmilyEdna ... Looks like you're trying to use cookie auth without Identity. https://docs.microsoft.com/en-us/aspnet/core/security/authentication/cookie?view=aspnetcore-3.1

This seems to be a general "*how to*" support question for the cookie auth without Identity. Try that topic and see if it helps. Due to time and staffing constraints, we can't troubleshoot individual developer apps. We only work on the docs, so we focus on doc enhancements and bugs. Your best bet is to ask for help on a support forum, such as Stack Overflow, or a support chat, such as Slack or Gitter. If you find a doc bug, we definitely want to hear about it.
