### ISSUE TITLE
Insufficient Information  on how error handling should be implemented.

### ISSUE THREAD

**Issue by CoolDadTx** [aspnet/AspNetCore.Docs#16372]
This page doesn't really provide a clear explanation of how error handling should be implemented. It talks about "API does this, MVC does that, here's how to customize" but never really clarifies anything. If API out of the box behaves the way it should then this page would be about the defaults, customizing them and when you might. As it stands now it is completely unclear whether we need to do this for API projects or not, out of the box.

This is greatly complicated by the fact that many apps that are migrated from ASP.NET will have a mix of MVC and API controllers and the customizations/behavior discussed on this page doesn't apply to both. So it is very unclear how you can have an MVC controller return back a standard HTML error page (or the dev page) while having your APIs return the ProblemDetails information. I'm not aware of any API anywhere that would want the dev/error page returned (in any environment) for API requests. At the same time ProblemDetails is not for users so I'm not aware of any case where an MVC controller should return ProblemDetails. This page doesn't remotely touch this seemly common situation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f6504cd-a059-c5d4-73fb-61222ef1c6e0
* Version Independent ID: 1b42352c-a34f-7703-aa3e-d7e3156bd0bd
* Content: [Handle errors in ASP.NET Core web APIs](https://docs.microsoft.com/en-us/aspnet/core/web-api/handle-errors?view=aspnetcore-3.1)
* Content Source: [aspnetcore/web-api/handle-errors.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/web-api/handle-errors.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-webapi**
* GitHub Login: @pranavkm
* Microsoft Alias: **prkrishn**

**Comment by pcellis** [comment]
I had the same reaction coming here to look up information on correct exception handling just now.

However, I dug a bit further, and if I interpret this section of the documentation correctly:

https://docs.microsoft.com/en-us/aspnet/core/fundamentals/error-handling?view=aspnetcore-3.1#exception-filters

The answer to the problem is exception filters, since you have to customize based on whether the API was requested or the main MVC app was requested. Curious as to whether one of the Microsoft documentation maintainers would agree with that interpretation, or whether the answer lies with using one of the lambdas available with exception page handling:

https://docs.microsoft.com/en-us/aspnet/core/fundamentals/error-handling?view=aspnetcore-3.1#exception-handler-lambda

**Comment by Rick-Anderson** [comment]
Moved to #16385
