### ISSUE TITLE
Microsoft.AspNetCore.Identity.UI package always publish its static assets

### ISSUE THREAD

**Issue by mmarinchenko** [aspnet/AspNetCore.Docs#16482]
Please, see:
for explanation - https://github.com/dotnet/aspnetcore/issues/18184#issuecomment-572143348
for solution - https://github.com/dotnet/aspnetcore/issues/16862#issuecomment-550438934

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a7e622e9-c567-00b9-3788-d6a01934b314
* Version Independent ID: 8e663029-63b9-2622-f852-9f8a2ec70db3
* Content: [ASP.NET Core fundamentals](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/?view=aspnetcore-3.1&tabs=windows#feedback)
* Content Source: [aspnetcore/fundamentals/index.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by mmarinchenko** [comment]
This is a continuation of #15556.

**Comment by guardrex** [comment]
This will be a probable _addition_ (not reversion) following updates on https://github.com/aspnet/AspNetCore.Docs/pull/15584, because I think (based on a quick glance), which is still valid in other scenarios.

Since this deals specifically with an Identity scenario, it might be best to place this in a suitable Identity topic spot ... maybe with a cross-link from the *Webroot* section for visibility ... maybe.

**Comment by mmarinchenko** [comment]
Completely agree)

**Comment by guardrex** [comment]
@Rick-Anderson If you're busy, I can do this one within a day (or *a few* 🏃😅) ... assign me if you want.

**Comment by mmarinchenko** [comment]
**Add**: the solution provided must be applied to "main" project - the one `dotnet publish` command executed for. But not the one which contains actual `Microsoft.AspNetCore.Identity.UI` package reference.
