### ISSUE TITLE
More than one app per server

### ISSUE THREAD

**Issue by mrlife** [aspnet/AspNetCore.Docs#16528]
The docs don't speak much to deploying and configuring multiple apps on one server. We have Windows with Apache and have one ASP.NET Core app running successfully. We have another app in development that we are trying to deploy to the same server. Everything is set up correctly in Apache, but we're not sure what to do with Kestrel for this to work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cfd9a1f0-c1b6-4443-0700-4c5beafeed03
* Version Independent ID: c22ca7a0-d1d4-200d-fc36-a9798d350c6e
* Content: [Host ASP.NET Core on Linux with Apache](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/linux-apache?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/host-and-deploy/linux-apache.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/host-and-deploy/linux-apache.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @guardrex
* Microsoft Alias: **shboyer**

**Comment by guardrex** [comment]
Hello @mrlife ... I'm not a *super whiz* on Apache, but you should be able to:

1. Configure Kestrel in the 2nd app for a different port than the one you're using the first app. Follow the guidance in the Kestrel topic. If the first app is using 5000, then perhaps make the 2nd app proxy on 5001.
1. Go from there following the instructions in the topic for the 2nd app:
   * Create another configuration file (*.conf*) with the new proxy address for the 2nd app.
   * Have another service definition file (*.service*) for it.

AFAIK, you're just duplicating the instructions in the topic for another app that doesn't have the same proxy address on the server.

I haven't heard anything from engineering otherwise, but I also haven't tried to host two apps on the same server.

Given how busy engineering is, I recommend that you take a stab at it that way ... then ask on support forums ... and then if all else fails (especially if you hit an error following the topic's guidance) to ping me back here.

I'll put the cross-links to support forums here. I know a lot of devs on these channels have a lot of experience in this area, so they should be able to answer any questions. 
 
* [Stack Overflow](https://stackoverflow.com/questions) (`asp.net-core` tag)
* [ASP.NET Core Slack](http://tattoocoder.com/aspnet-slack-sign-up/)
* [ASP.NET Gitter](https://gitter.im/aspnet/Home)

If you do find something really lacking in the doc ... a **_Gotcha!_** scenario that we should call out ... indeed, please do ping me back on this issue. I'll re-open and work it or contact engineering for further support on it.
