### ISSUE TITLE
UseKestrel is not Used

### ISSUE THREAD

**Issue by computamike** [aspnet/AspNetCore.Docs#16678]
Kestrel in ASP.NET Core apps
ASP.NET Core project templates use Kestrel by default. In Program.cs, the ConfigureWebHostDefaults method calls UseKestrel:

Code sample - and exmaple used in Visual Studio doesn't call UseKestrel - it calls UseStartup.  It might be that UseStartup calls UseKestrel - but this isn't explained.  I was staring at the example code - looking for UseKestrel - and it's not there.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f22dcddb-0c25-be1a-9a02-9e71dce86bdb
* Version Independent ID: 3e0e12c2-e544-5655-e001-d2ec180b11a8
* Content: [Kestrel web server implementation in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel?view=aspnetcore-3.1&tabs=aspnetcore2x#how-to-use-kestrel-in-aspnet-core-apps-1)
* Content Source: [aspnetcore/fundamentals/servers/kestrel.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/servers/kestrel.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @computamike ... The statement is accurate because `ConfigureWebHostDefaults` is a method. Inside the method, Kestrel is configured. See the *Remarks* at ...

https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.hosting.generichostbuilderextensions.configurewebhostdefaults?view=aspnetcore-3.1#remarks

... and the reference source at ...

https://github.com/dotnet/aspnetcore/blob/33eb8ba552c7452f441e2a223457d39f271d01b7/src/DefaultBuilder/src/GenericHostBuilderExtensions.cs#L29

... followed by ...

https://github.com/dotnet/aspnetcore/blob/1480b998660d2f77d0605376eefab6a83474ce07/src/DefaultBuilder/src/WebHost.cs#L217
