### ISSUE TITLE
More information-clarification needed.

### ISSUE THREAD

**Issue by ekalyvio** [aspnet/AspNetCore.Docs#16743]
At the top of the page you state (the following) that an ASP.NET Core Blazor app is needed for that page:
"To create a project for the hosting models described in this article, see Get started with ASP.NET Core Blazor."

In the paragraph "Integrate Razor components into Razor Pages and MVC apps" you state about adding a &lt;base&gt; tag to a layout file (_Layout.cshtml). 
That file does not exist on a Blazor app (either Server one or WebAssembly).

Either that paragraph is not related to a Blazor app and has to be moved to probably the Razor Pages or it has to be given a reference to an example tutorial to be followed by the reader before proceeding with that paragraph (where are the sources of it ???).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 542f38c4-1502-f739-372a-80c86c377491
* Version Independent ID: 72c2a844-ffb2-4799-2c7a-a7a73d3b6833
* Content: [ASP.NET Core Blazor hosting models](https://docs.microsoft.com/en-us/aspnet/core/blazor/hosting-models?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/blazor/hosting-models.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/hosting-models.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @ekalyvio ... I'll check as soon as I get home from the gym. :muscle:

**Comment by guardrex** [comment]
@ekalyvio ... the statements are accurate and covered in the right spot (for now at least).

> To create a project for the hosting models described in this article, see Get started with ASP.NET Core Blazor.

Yes, either type (hosting model) of Blazor app can be created following that guidance.

> Integrate Razor components into Razor Pages and MVC apps

Starts by saying ...

> An existing Razor Pages or MVC app can integrate Razor components into pages and views:

... because that whole section pertains to integrating **Razor components** into a **Razor Pages/MVC app**, not a Blazor app.

> has to be moved to probably the Razor Pages 

Thus far, we're keeping Blazor- and Razor component-related content in the Blazor node. There's some Razor syntax content in the Razor syntax doc, but we're trying to keep the vast majority of Blazor/Razor components coverage here. There is *overlap* among the framework models, and that's bound to lead to this challenge.

Not directly related to your concern is the cross-linkage to this section from RP/MVC. This section should be in the *Additional resources* of the RP and MVC overviews. I'll use this issue to track that and knock it out right now.

Thanks for writing in on this. I'll keep an :ear: open for feedback on this point. That section pertaining to using Razor components in RP/MVC apps is relatively new. No doubt, there will be updates as we go.
