### ISSUE TITLE
Where is manifest && works with controllers/views but not static content - CSS

### ISSUE THREAD

**Issue by DominikAmon** [aspnet/AspNetCore.Docs#16837]
I could get the example working with Controllers and Views, but not with static content, such as CSS. It would be great to improve the existing sample code on github with static content exmaples.
Regarding: "When the RCL is built, a manifest is produced that describes the static web asset locations." - How can I verify this / Where to find it? 

I posted already a message on Stackoverflow:
[404 with static content in Razor Class Library (RCL) - StackOverflow](https://stackoverflow.com/questions/60040793/404-with-static-content-in-razor-class-library-rcl)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9fd019c7-ceb7-6ef3-26ba-6b44341b6fc5
* Version Independent ID: fd116d00-0dc7-efaf-c714-34d77b345a05
* Content: [Reusable Razor UI in class libraries with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/razor-pages/ui-class?view=aspnetcore-3.1&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/razor-pages/ui-class.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/razor-pages/ui-class.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-razorpages**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@DominikAmon  can you create the simplest possible solution (RCL + consuming app) that demonstrates this problem? Post the GitHub link here.

Did you follow **Create an RCL with static assets**?

> "When the RCL is built, a manifest is produced that describes the static web asset locations."

@pranavkm how do we access the manifest?

**Comment by pranavkm** [comment]
It's an implementation detail so I wouldn't necessarily rely on using it in any way outside of what the framework does. But if you'd like to inspect it's contents, it's an xml default that's produced in the `obj\Debug\netstandard2.1\staticwebassets` directory.

**Comment by DominikAmon** [comment]
@Rick-Anderson I created a small sample app and published it on GitHub https://github.com/DominikAmon/RclIssueDemo/ 

I clearly made something wrong, but it is hard to figure out, as I am not getting any details other than 404.

**Comment by Rick-Anderson** [comment]
Did you follow https://docs.microsoft.com/en-us/aspnet/core/razor-pages/ui-class?view=aspnetcore-3.1&tabs=visual-studio#create-an-rcl-with-static-assets

Did you look in the manifest?

**Comment by Rick-Anderson** [comment]
> I placed a css file in the library at the following location: wwwroot\css\Base.css and I tested the following path: https://localhost:44300/_content/OurIt.Cockpit/css/Base.css, 

That's not the right URL.

Create a web app, put a static resource in wwwroot, and access it.

**Comment by Rick-Anderson** [comment]
> I could get the example working with Controllers and Views, but not with static content, such as CSS

The views are pulling static assets. You're just using the wrong path.

**Comment by cesarsouza** [comment]
> > I could get the example working with Controllers and Views, but not with static content, such as CSS
> 
> The views are pulling static assets. You're just using the wrong path.

What would be the correct path? I am afraid I am facing the same issue, but not even the MVC views are being found.

I am also getting many `CSC : warning AD0001: Analyzer 'Microsoft.AspNetCore.Mvc.Analyzers.TopLevelParameterNameAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.` as soon as I build the consumer app, but I may report this in another issue.

**Comment by cesarsouza** [comment]
Nevermind, I finally got it working. I am not completely sure yet what did the trick for me, but I had to configure my RCL project differently from what is shown [in the demonstration code](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/razor-pages/ui-class/samples/cli/RazorUIClassLib/RazorUIClassLib.csproj) from [the docs](https://docs.microsoft.com/en-us/aspnet/core/razor-pages/ui-class?view=aspnetcore-3.1&tabs=visual-studio#create-an-rcl-with-static-assets). Maybe those examples need to be updated.

The relevant parts of my now working .csproj are:
```
<Project Sdk="Microsoft.NET.Sdk.Razor">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc
    <GenerateMvcApplicationPartsAssemblyAttributes>true</GenerateMvcApplicationPartsAssemblyAttributes>
    <RazorCompileOnBuild>true</RazorCompileOnBuild>
    <IncludeRazorContentInPack>false</IncludeRazorContentInPack>
    <GenerateEmbeddedFilesManifest>true</GenerateEmbeddedFilesManifest>
    <EnableDefaultRazorGenerateItems>true</EnableDefaultRazorGenerateItems>
  </PropertyGroup>

 <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.Extensions.FileProviders.Embedded" Version="2.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.StaticFiles" Version="2.1.1" />
  </ItemGroup>

  <PropertyGroup>
    <StaticWebAssetBasePath Condition="$(StaticWebAssetBasePath) == ''">/</StaticWebAssetBasePath>
  </PropertyGroup>
</Project>
```

Maybe not all of those settings above are required, but since it is working, I do not want to touch it too much :grin:

Now, here are other issues that were getting in the way:

 - Because I wanted to test my NuGet packages locally, I wanted to first push the packages to a local repository folder so I could consume them from a test application. However, no where it is documented that dotnet nuget can also push to local directories, so I thought I would have to use the standalone nuget.exe to achieve this. Well, apparently [it is not a good idea to use nuget.exe with RCL libraries](https://github.com/dotnet/AspNetCore.Docs/issues/13951). Instead, you can use:
```
dotnet nuget push .\bin\Release\DynamicVML.1.0.32.nupkg -s c:\Projects\nuget
```
(note that the -s option is described as a `server URL` in the [documentation](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-nuget-push) but it can actually be a local folder, and this is not explained)

 - There are so many outdated articles and StackOverflow answers around that could set you up in the wrong path. What happened with me was that at some point I was trying to follow [tutorials](https://www.learnrazorpages.com/advanced/razor-class-library) from [different](https://dotnetstories.com/blog/How-to-Include-static-files-in-a-Razor-library-en-7156675136) [sources](https://weblog.west-wind.com/posts/2019/Sep/30/Serving-ASPNET-Core-Web-Content-from-External-Folders) which turned out to be outdated for .NET Core 3.1. I ended up messing a little my project files and forgot to undo some of the changes I had made. To get it all working, make sure that:

 - The views / .cshtml files have to be set to "Build Action: Content";
 - The static files / js files have to be set to "Build Action: Content";

Now, to the consumer application part:

- I did not have to add `webBuilder.UseStaticWebAssets();` in Program.cs as for a moment I thought I had. So my CreateHostBuilder simply looks like this:
```
        public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.UseStartup<Startup>();
                });
```

I did not have to add any of the FileProvider functionality that is described in the outdated tutorials. My ConfigureServices is as clean as this:
```
        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddControllersWithViews();

            services.AddDbContext<ApplicationDbContext>(options =>
                options.UseInMemoryDatabase("BookAuthors"));
        }
```
and my Configure is just the baseline one:
```
 public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            else
            {
                app.UseExceptionHandler("/Home/Error");
                // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
                app.UseHsts();
            }
            app.UseHttpsRedirection();
            app.UseStaticFiles();

            app.UseRouting();

            app.UseAuthorization();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllerRoute(
                    name: "default",
                    pattern: "{controller=Home}/{action=Index}/{id?}");
            });
        }
```

With the above settings, everything works. I can include js files from the RCL library *even though they are not physically present on the consumer project wwwroot* (I know that this is documented in the current documentation, but at some point I was trying to debug the issue by adding a [UseDirectoryBrowser to my configure ](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/static-files?view=aspnetcore-3.1) and inspecting the contents of the served folders - this does not work, the static files from the RCL will not show up).

**Comment by Rick-Anderson** [comment]
@cesarsouza thanks for the update.

**Comment by mkalinski93** [comment]
@cesarsouza I followed your instructions, but have you tried running multiple RCL´s simultaneously? 
In my case, I have had two rcl´s with the exact same configurations. 
After building, I´ve received the following errors: 

"Duplicate base paths '/' for content root paths 'projectA' 'projectB'

**Comment by cesarsouza** [comment]
> @cesarsouza I followed your instructions, but have you tried running multiple RCL´s simultaneously? 
> In my case, I have had two rcl´s with the exact same configurations. 
> After building, I´ve received the following errors: 
> 
> "Duplicate base paths '/' for content root paths 'projectA' 'projectB'
> 

Hi @mkalinski93, 

Not at all. To be honest I had only tested with a library I built mylsef (dynamic view model lists / dvml / dynamic-vml.github.io/ ) 

I don't know what would happen when multiple libraries would have been loaded at the same time.

César
