### ISSUE TITLE
Clarification about OnInitializedAsync in a pre-rendered Blazor Server app

### ISSUE THREAD

**Issue by Webreaper** [aspnet/AspNetCore.Docs#16860]
The comment [here](https://docs.microsoft.com/en-us/aspnet/core/blazor/lifecycle?view=aspnetcore-3.1#lifecycle-methods) states "These methods are only called one time when the component is first instantiated." This is not actually true in a Pre-rendered scenario, which is the default for Blazor Server. Therefore, people may inadvertently put initialisation logic such as data loading, or delegate hooks, into this method, and not realise that it gets called twice.

It might make sense to put an info box with the caveat explaining that it can get called twice, and link to [this page](https://docs.microsoft.com/en-us/aspnet/core/blazor/hosting-models?view=aspnetcore-3.1#stateful-reconnection-after-prerendering) - and it may be useful to have a full example explaining an approach to loading initialisation data in this context.
See this issue for background: https://github.com/dotnet/aspnetcore/issues/18815

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4bae853d-80e3-ef81-69eb-e8276eb853fe
* Version Independent ID: 01216f14-b45c-73b0-9f1f-300e7ddd788f
* Content: [ASP.NET Core Blazor lifecycle](https://docs.microsoft.com/en-us/aspnet/core/blazor/lifecycle?view=aspnetcore-3.1#lifecycle-methods)
* Content Source: [aspnetcore/blazor/lifecycle.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/lifecycle.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@Webreaper ... Thanks for writing in on this. I'm in the process of moving content **out** of the hosting models topic (where this scenario is covered) simply because it's too distracting there for early coverage on hosting models. The idea is to move the *hosting model configuration* coverage out into a new topic called ... *drum roll plz* 🥁 ... *Hosting model configuration*.

You inquired on this scenario at the perfect time. I also now believe that the coverage on *Stateful reconnection after prerendering* and *Detect when the app is prerendering* should be in the *Lifecycle methods* topic. However, they shouldn't IMO be shoehorned right in at the top of the doc where `OnInitializedAsync` is covered. I think they should be covered at the end of the topic with both sections cross-linked into the *Component initialization methods* (`OnInitializedAsync`) section.

I'm doing that right now, and I'll ping u on that PR shortly. Thanks again for writing in on this.

**Comment by Webreaper** [comment]
Thanks for the quick turnaround. Timing is everything!

**Comment by gmkado** [comment]
Other areas of the blazor documentation recommend using `OnInitializedAsync` and `Dispose` as a reliable way to subscribe and unsubscribe from events, see [StateContainerExample](https://learn.microsoft.com/en-us/aspnet/core/blazor/state-management?view=aspnetcore-6.0&pivots=server#in-memory-state-container-service-server).  Should these be updated to point to the new documentation or changed to use `OnAfterRender` as described [here](https://learn.microsoft.com/en-us/aspnet/core/blazor/components/lifecycle?view=aspnetcore-6.0#after-component-render-onafterrenderasync)?
