### ISSUE TITLE
Display full queued background task example in topic content

### ISSUE THREAD

**Issue by KeeganFargher** [aspnet/AspNetCore.Docs#16905]
The **queued background tasks** example does not work correctly for me. I expect the monitor loop to start but it never runs as this method is never called (I don't see any references to it either):
  
```
public void StartMonitorLoop()
    {
        _logger.LogInformation("Monitor Loop is starting.");

        // Run a console user input loop in a background thread
        Task.Run(() => Monitor());
    }
```

I have tried setting a breakpoint in the constructor but it is never hit either. This is my `Program.cs` file:
```
    public class Program
    {
        public static void Main(string[] args)
        {
            CreateHostBuilder(args).Build().Run();
        }

        public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureServices((hostContext, services) =>
                {
                    services.AddSingleton<MonitorLoop>();
                    services.AddHostedService<QueuedHostedService>();
                    services.AddSingleton<IBackgroundTaskQueue, BackgroundTaskQueue>();
                });
    }
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3460b0d-9c60-3a06-ac63-18cf990e53c3
* Version Independent ID: b2dece1f-15b8-03af-6d52-7cc070432b4b
* Content: [Background tasks with hosted services in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/hosted-services?view=aspnetcore-3.1&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/fundamentals/host/hosted-services.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/host/hosted-services.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Did you see the sample app ...

https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/host/hosted-services/samples/3.x/BackgroundTasksSample/Program.cs#L35-L37

Let me complete the coverage there on this. We have found over the last couple of years that devs are hit-and-miss on looking at the sample for additional less-relevant code to the main concepts. I probably need to move the **full** example into the text so that looking at the sample is optional.

Leave this issue open. It will close when the PR merges later. I'll ping u on the PR when I put it up within a week or two.
