### ISSUE TITLE
Add connection string example for Env Var Config Provider

### ISSUE THREAD

**Issue by MP7373** [aspnet/AspNetCore.Docs#16933]
I've been at this for 2-3 hours and can't find a simple example.
It would only take a single good example.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0eb4d762-3910-2c57-8741-3306c15537b6
* Version Independent ID: ba2254a0-ea8e-9b28-e94b-edd0fc58c043
* Content: [Configuration in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-3.1)
* Content Source: [aspnetcore/fundamentals/configuration/index.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/configuration/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @MP7373 ... The Environment Variable Configuration Provider is explained in the topic ...

https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-3.1#environment-variables-configuration-provider

If it seems complex, it's because the provider, along with most other aspects of the framework, is flexible and meets the needs of many scenarios.

Any config from env vars read by the provider goes into configuration as key-value pairs. In general, the env var *name* (prefix stripped if you supply a prefix to `AddEnvironmentVariables`) is the *key* of the key-value pair stored in configuration. The sample app does it with some filtering because the app reads all of the environment variables (due to the app's use of `CreateDefaultBuilder` to build the host) ...

https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/configuration/index/samples/3.x/ConfigurationSample/Pages/Index.cshtml.cs#L30-L42

Since your use case is for connection strings, see the bit on **Connection string prefixes** at the end of that topic section. It's been long time since I've used it myself, but try this:

Set up your env var as:

* Name: `CUSTOMCONNSTR_{KEY}`, where "{KEY}" is whatever key you want to use.
* Value: {Your Connection String}

Then, read it from configuration as ...

```
_config["ConnectionStrings:{KEY}"]
```

... where "{KEY}" was what you used in the env var name and assuming you assign your injected `IConfiguration` to a field named `_config` wherever you're using it.

I think what would help here is if a sample snapshot (code example) shows the connection string example. I'll whip that up and put it into the topic. Thanks for commenting. Leave this issue open. It will close automatically when the PR merges.

**Comment by MP7373** [comment]
Thanks for this! I was really frustrated and am almost embarrassed about making that complaint.
