### ISSUE TITLE
"Run the app."

### ISSUE THREAD

**Issue by AskYous** [aspnet/AspNetCore.Docs#17029]
Am I reading this correctly? The documentation says that once I make changes to my code for the font-end, I have to "Run the app." But my apps is already running? Does this mean I have to restart the server? If so, that's very bad because that means front-end changes require the server to restart every time. So if I changed the text in an &lt;h1&gt;, I have to restart the entire server? The documentation isn't clear. Currently, I have to restart the server every time I make a front-end change. I hope I misread or that's a bug.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c07e57dc-526f-9479-4695-de7d8f06eb9a
* Version Independent ID: 8226ed72-69b2-3c93-a931-218bd11cf9c8
* Content: [Get started with ASP.NET Core Blazor](https://docs.microsoft.com/en-us/aspnet/core/blazor/get-started?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/blazor/get-started.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/get-started.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @AskYous ... I assume that since you're asking about a "server" that you're asking about a **_deployed app_** (hosted by IIS), not merely running the app locally. You don't *restart the server* to restart an app. Just re-deploy the app and make a new request to it.

If you're not referring to use of a server but merely asking about developing locally. Visual Studio has a feature called *Browser Link* that should do the trick for you. Otherwise, you just click the app restart button in VS to restart the app.

btw - All of the host and deploy info for servers/CDNs is in the *Host and Deploy* node, starting with :point_right: https://docs.microsoft.com/aspnet/core/host-and-deploy/blazor/

**Comment by gavimoss** [comment]
I'm using VS Code, any way we can see real time updates without having to do a re-deploy?  In ASP.Net we could just make changes to the client side html/js, hit F5 in the browser and see the changes; having to re-deploy each time now seems like a step back!
