### ISSUE TITLE
No documentation on handling return values from calling a hub method from client

### ISSUE THREAD

**Issue by tomzorz** [aspnet/AspNetCore.Docs#7628]
Title basically says it all. E.g. what if "SendMessage" would return a bool indicating success? Where can I handle the return value?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3cf283c9-5cd2-a9ff-b8c8-372d8a04356d
* Version Independent ID: 729fddcf-24e4-b563-4952-a8045b231868
* Content: [ASP.NET Core SignalR JavaScript client](https://docs.microsoft.com/en-us/aspnet/core/signalr/javascript-client?view=aspnetcore-2.1)
* Content Source: [aspnetcore/signalr/javascript-client.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/signalr/javascript-client.md)
* Product: **aspnet-core**
* GitHub Login: @rachelappel
* Microsoft Alias: **rachelap**

**Comment by tomzorz** [comment]
Meanwhile I managed to figure out that if I have `async Task<string> MethodWithReturnValue()` in the Hub I need to use  `connection.invoke("MethodWithReturnValue").then(function(retval){/*do thing*/});`,  but it'd be nice if there would be a code sample for this.

**Comment by Rick-Anderson** [comment]
@anurse Should we add this?

**Comment by Rick-Anderson** [comment]
@anurse 	let me know when you have sample code and we'll get this added.

**Comment by davidfowl** [comment]
Yes we should add this.

**Comment by Rick-Anderson** [comment]
@anurse 	can you provide a sample that @tdykstra 	can add?

**Comment by anurse** [comment]
Same is needed in .NET (which also doesn't include specific info about catching exceptions)

JavaScript:

```javascript
connection.invoke("Add", 40, 2)
    .then((result) => alert("40 + 2 = " + result))
    .catch((err) => alert("An error occurred: " + err));
```

.NET:

```csharp
try
{
    result = await connection.InvokeAsync("Add", 40, 2);
}
catch(Exception ex)
{
    // Handle exceptions
}
```

**Comment by CarlosTorrecillas** [comment]
I've been following all the documentation to implement the JavaScript client in one of the solutions I have and I think it is not clear what to do in terms of registration and existing handlers when a disconnection occurs. It's really good the start example but in my opinion it is not enough since I'm not entirely sure what's the best practice here to either reconnect or start a fresh connection by de-registering everything and start all over again. I take from the docs that a simple start would be sufficient?

Thanks,
Carlos.

**Comment by anurse** [comment]
Filed https://github.com/aspnet/AspNetCore.Docs/pull/12015 for the JS docs.
