### ISSUE TITLE
Should be updated to use the new {tenant}.b2clogin.com endpoint

### ISSUE THREAD

**Issue by ericbeaudry** [aspnet/AspNetCore.Docs#8998]
After numerous hours trying to make this sample work, I've finally found out that using b2clogin.com endpoint is Postman was the solution. Using login.microsoftonline.com like the sample suggests turns out to cause problems with redirections in my case. I'm using a custom OpenID Connect to authenticate against an Azure AD Tenant and I was always getting an error stating the redirecturl was invalid. Switching the Auth Url to https://{tenant}.b2clogin.com/{tenant}.onmicrosoft.com/oauth2/v2.0/authorize?p=b2c_1_sign-up-in solved that. 
BTW using login.mocrosoftonline.com is getting deprecated, so why even propose that in the samples?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ebb27a5-41cc-b64f-de68-2f0df6b02f8d
* Version Independent ID: 31de5338-ace5-b8c4-88e8-54863428fc61
* Content: [Cloud authentication in web APIs with Azure Active Directory B2C in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/azure-ad-b2c-webapi?view=aspnetcore-2.1)
* Content Source: [aspnetcore/security/authentication/azure-ad-b2c-webapi.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authentication/azure-ad-b2c-webapi.md)
* Product: **aspnet-core**
* GitHub Login: @CamSoper
* Microsoft Alias: **casoper**

**Comment by CamSoper** [comment]
@ericbeaudry - Totally agree, but I think we need to wait until Visual Studio's boilerplate that it inserts uses that endpoint.  Otherwise it adds extra steps and make the walkthrough more complicated.

@Rick-Anderson just merged a PR yesterday that should clarify it (hopefully - I'd love some feedback if you've got it!)

**Comment by ericbeaudry** [comment]
Agreed, it might be early to change the procedure. But at the same time not doing so will drive some people in the wrong direction. Maybe simply add a mention regarding deprecation and when/where to use which url. Adding a reference here could also help people trying to resolve their issues : https://docs.microsoft.com/en-us/azure/active-directory-b2c/b2clogin.

**Comment by jasongerstorff** [comment]
This article could use some clarifications. Took me several hours to get this working.  First of all by Default the .NET Core api app lists login.microsoft in the AzureAdB2C instance setting in appsettings. You have to go in and change this to the tenant instance name. Which is also confusing because there are also {mytenant}.b2clogin.com and {mytenant}.onmicrosoft.com both listed as "domains" depending what screen you are on in azure b2c dashboard, for example overiew vs user flows screen.  Your AuthUrl for postman is hard coded to login.microsoftonline.com but actually this should be b2clogin.com instance name followed by the onmicrosoft.com "domain" name. There should really be some more ubiquitous language used for these also fix the hard code issue and clarify the need to change the instance name in the appsettings.

**Comment by Prorobot09** [comment]
@jasongerstorff
Did you go with .b2c or .microsoft to solve the problem? Can not get it working...

**Comment by jasongerstorff** [comment]
Core project app settings - domain: <yourtenant>.omnimicrosoft.com , instance: <yourtenant>.b2clogin.com

postman authurl: https://<yourtenant>.b2clogin.com/<yourtenant>.onmicrosoft.com/oauth2/v2.0/authorize?p=B2C_1_DevTesting

postman scope: https://<yourtenant>.onmicrosoft.com/<yourapiname>/user_impersonation openid offline_access

**Comment by jasongerstorff** [comment]
dropped my placeholder tags sorry, should be whatever your tenant name is before .omnimcrosoft and .b2clogin 

and whatever your api name is between the double slashes in postman scope

**Comment by jasongerstorff** [comment]
Core project app settings - domain: yourtenant.omnimicrosoft.com , instance: yourtenant.b2clogin.com

postman authurl: https://yourtenant.b2clogin.com/yourtenant.onmicrosoft.com/oauth2/v2.0/authorize?p=B2C_1_DevTesting

postman scope: https://yourtenant.onmicrosoft.com/yourapiname/user_impersonation openid offline_access

Where your api name is the app name you set in azure b2c.

**Comment by Prorobot09** [comment]
Thanks its up and running! Last Problem left: I get a token but and "500 internal server Error" if i want to Get the default values? Maybe you got a similar problem?

**Comment by jasongerstorff** [comment]
Keep in mind you will get that when you launch the api because of the authorize attribute, the browser is not authenticate to view the data. So you cannot see the values from the browser page. If you can query them from postman you are in good shape. 

if you don't want to see the 500 error you would have to add some kind of front end, otherwise don't worry about it. 

if you are getting the 500 in postman you will need to dig into the response or the output in visual studio so try and figure out exactly what is wrong. If you got the token, perhaps something might not be configured right your b2c api app.

**Comment by Rick-Anderson** [comment]
Moved to #16186
