### ISSUE TITLE
Youtube Series of video tutorials? Maybe?

### ISSUE THREAD

**Issue by eduFDiaz** [aspnet/AspNetCore.Docs#9766]
It'd be nice for this section to have a video version, so beginners like myself have a better understanding of every step. The [Razor section videos](https://github.com/aspnet/Docs/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+youtube+in%3Atitle+label%3A%22Source+-+Docs.ms%22) were extremely helpful and didactic, I don't see any reason for this extremely complicated topic to not have them.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: faf18d20-d28f-1efa-d329-181fff3630fa
* Version Independent ID: 46a7c2e0-4871-491f-02c2-54f7df2237b1
* Content: [Get started with ASP.NET Core MVC and Visual Studio](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/start-mvc?view=aspnetcore-2.1)
* Content Source: [aspnetcore/tutorials/first-mvc-app/start-mvc.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/first-mvc-app/start-mvc.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
He may eventually do this series, we're not doing them.

**Comment by ArsalanWahid** [comment]
@krchome please do the series <3

**Comment by Lexiebkm** [comment]
For me, this textual tutorial is enough. I have been used to reading the documentation since I used Foxpro 2.6 for DOS which was accessed from its Help Utility (via F1 function). I used MSDN Library for learning more on VB6, Office Automation (Word and Excel COM); I used Books Online for learning SQL Server 2000. So far I only use videos for leaning how to drive a car and parking and some automotive DIY things. :)
